edgelesssys/contrast

coordinator/userapi.go
coordinator/userapi_test.go
docs/docs/architecture/observability.md

This adds a metric for the current manifest generation set at the Coordinator.

coordinator: add manifest generation metric

---

packages/by-name/genpolicy-msft/genpolicy_msft_rules_coordinator.patch
packages/by-name/genpolicy-msft/genpolicy_msft_settings_dev.patch
packages/by-name/genpolicy-msft/package.nix

This release is what's currently available on AKS.

genpolicy-msft: bump version to 3.2.0.azl1.genpolicy0

---

internal/kuberesource/mutators.go
internal/kuberesource/sets.go

This PR changes the implementation of `PatchImages` to use `MapPodSpec`. That way, we only implement the big switch statement once (in `MapPodSpec`) and automatically get support for all types that have a `PodSpec` - including `StatefulSet`, which is currently not supported.
Drive-by fixes:
* Move `Patch*` functions to mutators (as they are not sets).
* Remove leftover comments.

resourcegen: support StatefulSet in PatchImages

---

coordinator/meshapi.go
docs/docs/architecture/observability.md
internal/attestation/snp/validator.go

This adds a metrics for attestation failures from workloads to the Coordinator when calling NewMeshCert on the initial startup. If the attestation fails, the metric counter `coordinator_attestation_failures` increases with the label `error` which stores the error string.

coordinator: add metric for attestation failures with error string

---

e2e/openssl/openssl_test.go
e2e/servicemesh/servicemesh_test.go
internal/kuberesource/resourcegen/main.go
internal/kuberesource/sets.go
packages/scripts.nix

We currently have a `Coordinator` (only deployment) and a `CoordinatorRelease` (with service and LB annotation), both in use. Since 
1. there is no release-specific information in the `CoordinatorRelease` set,
2. the coordinator definition is functionally identical and
3. the coordinator is always used with its service
settle on one `CoordinatorBundle` that's used everywhere.

resourcegen: settle on one set for the Coordinator

---

e2e/internal/contrasttest/contrasttest.go
e2e/openssl/openssl_test.go
e2e/servicemesh/servicemesh_test.go
internal/kuberesource/mutators.go
internal/kuberesource/mutators_test.go
internal/kuberesource/resourcegen/main.go
internal/kuberesource/sets.go
packages/scripts.nix

Our sets are known at compile time and thus creating them should never cause an error. This PR changes the implementation of a couple of mutators to be error-less, by switching them to `MapPodSpec`, and adds tests to ensure that this mapping still works. As a byproduct, `AddInitializer` and `AddServiceMesh` can now be used with any pod-creating resource.

resourcegen: don't return errors when creating sets

---

e2e/internal/kubeclient/deploy.go
e2e/internal/kubeclient/kubeclient.go
internal/kuberesource/mutators.go
internal/kuberesource/parts.go
internal/kuberesource/wrappers.go

This is a preparation for changing the Coordinator kind to StatefulSet, but should be useful on its own for dealing with StatefulSets in e2e.

e2e: support StatefulSet

---

docs/docs/getting-started/install.md

* Force >=TLS1.2
* Force HTTPS
Inspired by the rustup.sh installation instructions: https://rustup.rs

docs: harden curl invocation in installation instruction

---

docs/versioned_docs/version-0.6/getting-started/install.md

Backport of #498 to versioned docs of v0.6

docs: add curl hardening flags for released version

---

coordinator/meshapi.go
coordinator/userapi.go
docs/docs/architecture/observability.md

This adds a histogram to the metrics exposed by the Coordinator to track request times of the user API and the mesh API.

coordinator: add grpc latency metrics

---

coordinator/meshapi.go
coordinator/userapi.go
docs/docs/architecture/observability.md

This adds the additional `contrast_` prefix to all exposed metrics from the Coordinator.

coordinator: prefix metrics with contrast

---

packages/by-name/genpolicy-msft/package.nix

This is essentially kata-containers/kata-containers#9706, but adopted to Microsoft's fork.
Since the patch touches `rules.rego`, we can't take the one from the URL anymore, so I changed the rules to small derivations that extract the patched `rules.rego` and `genpolicy-settings.json` files, respectively.

genpolicy-msft: add support for volumeDevices

---

coordinator/main.go
docs/docs/architecture/observability.md
e2e/internal/contrasttest/contrasttest.go
e2e/openssl/openssl_test.go
internal/kuberesource/mutators.go
internal/kuberesource/parts.go

This makes the Coordinator metrics endpoint configurable via an environment variable. If `CONTRAST_METRICS_PORT` is set, the metrics server will start on that port. If the variable is not set, the metrics server will not start.
For CI, the endpoint is activated through the `PatchCoordinatorMetrics` function.

coordinator: make metrics endpoint configurable

---

docs/docs/getting-started/cluster-setup.md
docs/versioned_docs/version-0.6/getting-started/cluster-setup.md

When doing cluster setup from start you will set the variables. However, if you revisit the guide later and forget to set the variables in question you might get weird (missleading) az error messages like: The api-version '2024-03-02-preview' is invalid.
This will probably save you guys some support issues

docs: better error message when forgetting to set variables

---

.github/workflows/release.yml
e2e/release/release_test.go

Failed release run on PR #510 : https://github.com/edgelesssys/contrast/actions/runs/9346382093
`contrast set` failed because the Coordinator policy hash was not correctly generated due to the Coordinator now being a StatefulSet.
Rerun: https://github.com/edgelesssys/contrast/actions/runs/9349135584

release: fix coordinator policy hash

---

e2e/internal/kubeclient/kubeclient.go
e2e/openssl/openssl_test.go
internal/kuberesource/sets.go
justfile

This adds 
* a new test to verify that the root CA is still accepted after certificate rotation. 
* another run of the certificate rotation test that restarts the other deployment
I want these tests to prepare for RFC004 changes to meshauth/ca.
To make these changes easier, I introduced
* a helper function to exec in a random pod of a deployment
* a helper function to construct `s_client` arguments
While I was looking into the test, I noticed that there are a couple of leftovers in the OpenSSL deployment originating from when we used it for manual testing. I don't think we need the OpenSSL pods to communicate without user interaction - Emojivoto should be sufficient to test this kind of thing.

e2e: test verify with root CA after cert rotation

---

coordinator/history/fsstore.go
coordinator/history/history.go
coordinator/history/history_test.go

This is the history storage module and part of the implementation of RFC 004.

coordinator: implement history with fs store backend

---

cli/cmd/generate.go
packages/by-name/genpolicy-msft/genpolicy_msft_runtime_class_filter.patch
packages/by-name/genpolicy-msft/package.nix

Uses https://github.com/kata-containers/kata-containers/pull/9725 adapted so it successfully applies to the msft fork.

genpolicy: add patch to filter for runtime class

---

e2e/internal/kubeclient/deploy.go

Example of an unhelpful message: https://github.com/edgelesssys/contrast/actions/runs/9403829370/job/25901282612?pr=535#step:12:116.

e2e: correctly report unexpected watch events

---

coordinator/history/aferostore.go
coordinator/history/aferostore_test.go
coordinator/history/history.go
coordinator/history/history_test.go

* Export hash size because it is part of the API (via hashRef arguments).
* Export `store` and allow it as an argument for creating `History` (useful for `authority` tests).
* Same for the fs-based implementation.
* Add tests for AferoStore and fix a bug in the implementation (when run on `OsFs`).

coordinator: usability improvements to the history package

---

coordinator/internal/authority/authority.go
coordinator/main.go
coordinator/userapi_test.go
internal/ca/ca.go
internal/ca/ca_test.go

This PR adds a SeedEngine instance to the Authority and moves certificate rotation out of the CA object, which is now an instance dedicated to a single manifest generation. For now the SeedEngine is initialized with ad-hoc random bytes and the mesh key is created at random, which should yield the same observable behaviour as before this change. After switching to `history` we can use `LatestTransition` to seed the mesh key, and later on we can recover from an input seed.

coordinator: rotate certs in authority

---

internal/kuberesource/reader.go
internal/kuberesource/reader_writer_test.go

This checks for unknown fields in the user's YAML files. Before this change, any unknown fields would be silently discarded in the `generate` step. This does not check for required fields in the resources.

cli: check yaml for unknown fields

---

cli/cmd/set.go

Did a bunch of tests and it often takes >30s before the coordinator is routable after a fresh deployment (and valid public IP).
Best to set a conservative timeout here otherwise non-interactive use-cases will bump into this for sure.
This fixes #517.
Tested in `westeurope`.
Tested hammering with this script (based on [burgerdev's instructions][1]. 
```shell
#!/bin/sh
set -ex
mkdir -p deployment
for _ in $(seq 20); do
kubectl delete -f deployment/coordinator.yml || :
rm -rf -- verify *.sha256 *.json *.pem *.rego deployment/*
cp coordinator.yml deployment/
contrast --log-level debug generate deployment/
kubectl apply -f deployment/coordinator.yml
while sleep 1; do # wait for IP
coordinator=$(kubectl get svc coordinator -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
[ "$coordinator" = …
```

setLoop: wait 180s for the coordinator

---

docs/docs/deployment.md

This adds an example Initializer configuration to the docs, if a user does not want to automatically inject the Initializer.

docs: manual initializer setup

---

cli/cmd/generate.go
internal/kuberesource/mutators.go

During `contrast generate`, the parsed YAML file is not guaranteed to be valid. This checks for all struct fields that are necessary for the generation process if they are nil or not, to avoid runtime panics on an invalid YAML file.

cli: error checking for struct fields

---

flake.nix

Previously, genpolicy would fail as the files were read-only.

flake: fix demodir file permissions

---

.github/workflows/release.yml
packages/scripts.nix

This patches the download links and container images in the released versioned docs to be tagged with the release version and hash instead of `latest`.

release: patch latest references in versioned docs

---

e2e/internal/kubeclient/deploy.go
e2e/release/release_test.go

This brings us closer to the documented instructions (we had a broken release before because of this discrepancy).
Drive-by: use the appropriate way to determine whether an unstructured object is namespaced or not. This allows applying/deleting resources with no (or empty) namespace using kubeclient.

release: test in the default namespace

---

internal/attestation/snp/validator.go
internal/logger/handler.go
internal/logger/handler_test.go

This enables the all log subsystems at `warn` level or above. These logs will be get printed regardless of the `CONTRAST_LOG_SUBSYSTEMS` list. The `CONTRAST_LOG_LEVEL` variable is also considered, so when the global log level is set to `error`, only error messages will get printed from the subsystems

logging: enable subsystem warn level by default

---

internal/kuberesource/sets.go

Only add the necessary environment variables in the case where the Service Mesh is disabled.

resourcegen: cleanup emojivoto env variables

---

packages/by-name/microsoft/genpolicy/package.nix
packages/by-name/microsoft/kata-igvm/package.nix

The microsoft.kata-igvm package was using an outdated branch that didn't reflect the build process in Microsoft's upstream branch very well, even though building almost the same image. This updates our build process of the image to the new upstream build. Tested to be reproducible and work in a Contrast cluster.

packages: update kata-igvm to microsoft upstream

---

internal/kuberesource/parts.go

This adds a startup probe to the Service Mesh sidecar container. It probes on the port the Envoy proxy listens on for incoming traffic. Envoy only starts after the iptables rules have been updated, which is when the regular containers should start.

resourcegen: add startup probe to service mesh

---

coordinator/internal/authority/authority.go
coordinator/internal/authority/authority_test.go
coordinator/main.go
coordinator/userapi.go
coordinator/userapi_test.go

This change swaps the in-memory persistence for a filesystem-backed KV store wrapped by `History`.  
Through the use of an internal atomic state pointer, the `Authority` struct is now thread-safe and responds with the correct state (esp. CA certs) even under concurrent calls to `SetManifest`. It also anticipates out-of-band modifications of persistence and syncs accordingly, which should make it ready for a distributed setup.

coordinator: use history in authority

---

.github/workflows/release.yml
packages/contrast-releases.json

`contrast-releases.json` is not updated with the correct version on release (e.g. `0.7.0` instead of `v0.7.0`). This breaks `just demodir`.
- PR generated by the new release workflow with correct versioning: https://github.com/edgelesssys/contrast/pull/579

packages/contrast-releases: fix v0.7.0 and update workflow on release

---

packages/by-name/microsoft/cloud-hypervisor/package.nix
packages/by-name/runtime-class-files/package.nix
packages/default.nix

Previously, we relied on a cloud-hypervisor-cvm artifact that we fetched from the AKS nodes once. This enables us to reproducibly build the cloud-hypervisor fork of Microsoft that's deployed on Kata-enabled AKS VMs ourselves, and uses it in the runtime-class-files we deploy through the node-installer.

packages: package cloud-hypervisor-cvm

---

.github/workflows/e2e_getdents.yml
.github/workflows/e2e_openssl.yml
.github/workflows/e2e_servicemesh.yml
e2e/getdents/getdents_test.go
e2e/internal/contrasttest/contrasttest.go
e2e/openssl/openssl_test.go
e2e/servicemesh/servicemesh_test.go

Adds an extra cleanup step to both the OpenSSL and Service Mesh test to clean up the resources in the CI cluster if the test was cancelled.

e2e: cleanup when test is cancelled

---

cli/main.go

cli: fix autocomplete

---

.github/workflows/rpm_updates.yml
packages/by-name/kata/kata-image/buildimage.sh
packages/by-name/kata/kata-image/package-index.json
packages/by-name/kata/kata-image/package.nix
packages/by-name/rpm-pin-vendor/package.nix
packages/by-name/rpm-pin-vendor/update_lockfile.sh

This packages a CBL-Mariner-based UVM image, resembling what's used upstream by Kata. For now, it uses almost the same build instructions as the Microsoft image, but eventually, we'll might want to adapt it as per the specific requirements of AKS and bare-metal appliances.
It also enables the CI to update the RPM packages inside the root filesystem for both the AKS and bare-metal UVM images.

packages: package Kata upstream UVM image

---

internal/manifest/crypto.go
internal/manifest/crypto_test.go

This centralizes the algorithms used for managing seed shares and owner keys.

manifest: add utilities for encrypted SeedShares

---

e2e/getdents/getdents_test.go
e2e/internal/contrasttest/contrasttest.go
e2e/internal/kubeclient/deploy.go
e2e/internal/kubeclient/kubeclient.go
e2e/openssl/openssl_test.go
e2e/release/release_test.go
e2e/servicemesh/servicemesh_test.go

The functions `WaitForDeployment`, `WaitForDaemonSet` and `WaitForStatefulSet` are combined into one `WaitFor` function, which takes the resource kind as an input and performs all the logic that the previous functions had.
Additionally, the context error is now checked when receiving from the watcher channel, which is closed when the context expires, so you don't get error messages like this: https://github.com/edgelesssys/contrast/actions/runs/9522518982/job/26252214876#step:12:118

kubeclient: combine duplicate code for WaitFor* functions

---

coordinator/internal/authority/authority.go
coordinator/internal/authority/authority_test.go
coordinator/internal/authority/recoveryapi.go
coordinator/internal/authority/userapi.go
coordinator/internal/authority/userapi_test.go

This PR consolidates `Authority.setManifest` (authority) and `Authority.SetManifest` (userapi) after the refactoring in #583. This is more or less a move of the function body from one file to another, except that the generated seed could now be returned to the user (for that to work, however, bae8e7f needs to change the `Manifest` definition first). 
I tried to ensure that all test cases removed from `authority_test.go` are reflected in `userapi_test.go`, and it turned out we already covered most of it there.

coordinator: enable returning seed to user

---

cli/cmd/common.go
cli/cmd/set.go
cli/cmd/verify.go
coordinator/internal/authority/authority.go
e2e/internal/contrasttest/contrasttest.go
internal/manifest/manifest.go
justfile

This changes the Coordinator validate options to use the reference values from the local manifest in the `set` and `verify` command. The verify command takes an additional flag `--manifest` for this to provide the path to the manifest.
The default workspace directory for the `verify` command is no longer `./verify`, because the manifest lies in the current directory. Instead, the output files for the `verify` command are always written to the `verify` directory in the current workspace directory.

cli: use manifest reference values for attestation

---

packages/by-name/microsoft/genpolicy/genpolicy_msft_revert_special_symlink_names.patch
packages/by-name/microsoft/genpolicy/genpolicy_msft_runtime_class_filter.patch
packages/by-name/microsoft/genpolicy/package.nix

(cherry picked from commit c490d2db36a78866eb36f40dfd9e2f5905a50f6e)

[release/v0.7]: genpolicy-msft: revert problematic tarindex commit

---

packages/by-name/contrast-node-installer-image/package.nix
packages/by-name/runtime-class-files/package.nix

Previously we used the timestamp of the binary backup from our S3 bucket. Not that we build all the components from source, we can use the correct versioning from kata-image. Also renaming the cl attr as it no longer is binary-based.

packages/runtime-class-files: use version of kata-igvm

---

.github/workflows/release.yml

Fixes the bug observed in https://github.com/edgelesssys/contrast/commit/9b3cdb2638d56e2b3feb710a35fcfe800b5dd54c (https://github.com/edgelesssys/contrast/pull/622). Previously, we would update the json file on the release branch and then send it to the main branch update. But as we never commit the updated file there, patch releases would always overwrite the minor version.

release: update contrast-releases.json on main branch; minor improvements

---

cli/cmd/generate.go
coordinator/internal/authority/authority_test.go
e2e/internal/contrasttest/contrasttest.go
internal/manifest/constants.go
internal/manifest/manifest.go
internal/manifest/manifest_test.go
justfile

This allows for fields in the manifest to have the value `"null"`, in which case the attestation will fail when trying to parse the validation options from the manifest. This is helpful when generating the manifest for the first time with `contrast generate` where the SNP reference values are now left empty (`"null"`) by default. The default reference values used for AKS can then optionally be generated with the `--reference-values aks` flag.

generate: add flag for aks reference values

---

docs/docs/deployment.md
docs/docs/examples/emojivoto.md

The `verify` command now takes in the manifest file for attestation to the Coordinator, as well as verifying the active manifest at the Coordinator.

docs: verify command takes in manifest file

---

cli/cmd/generate.go
cli/cmd/set.go
cli/cmd/verify.go
internal/manifest/manifest.go
internal/manifest/manifest_test.go

This adds a function `Validate()` to the manifest to check if every field in the manifest struct contains a reasonable value or if any required fields are missing.

manifest: validate manifest fields

---

cli/cmd/generate.go
cli/cmd/generate_test.go

Previously, we would collect the output with `RUST_LOG=info`, but only print it in case the invocation failed, thus swallowing any warnings. This PR introduces a log translator, that parses the output of genpolicy line by line and filters the output with regard to the currently configured log level. As a consequence, warnings are now shown by default, and when we configure debug logging in the Contrast CLI, the info logging of genpolicy is shown. However, in case genpolicy fails and the CLI debug level is info, we will now get slightly less output.
Example output (CLI loglevel info):
```
✔️ Patched targets
time=2024-06-26T08:03:50.284+02:00 level=WARN msg="Skipping symlink with long link name (NetLock_Arany_=Class_Gold=_Főtanúsítvány.pem, 48 bytes, …
```

generate: translate genpolicy logs, show warnings

---

node-installer/platforms/platforms.go

This adds a sub-package "platforms" to the Contrast node-installer, the purpose of which it is to distinguish the different deployment scenarios of Contrast. It's accomodated best in the node-installer, as this is the component in Contrast with the most conditional behaviour depending on the platform. Additionally, this layout lets the Contrast main module consume the node-installer module if it needs the platforms, and not the other way around. This is desirable since the main module likely undergoes more change than the node-installer.

node-installer: add platforms

---

cli/cmd/common.go
cli/cmd/generate.go
cli/cmd/recover.go
cli/cmd/set.go
cli/main.go

This introduces a new command `recover` that let's you recover the Coordinator state after a restart.
TODO: link doc page about recovery.

cli: add recover command

---

cli/cmd/generate.go
cli/cmd/verify.go

The `verify` command already takes the manifest file as an input. On `verify`, the CLI will now check if the local manifest matches the active manifest on the Coordinator.

verify: verify active manifest at Coordinator

---

cli/cmd/common.go
cli/cmd/generate.go
cli/main.go
internal/manifest/constants.go
packages/by-name/contrast/package.nix

Instead of injecting the runtime handler into the CLI, we can directly derive it from the trusted measurement.

cli: derive runtime class name from launch digest

---

.github/workflows/release.yml
docs/docs/examples/emojivoto.md
e2e/release/release_test.go
packages/contrast-releases.nix
packages/update-contrast-releases.sh

This changes the released Emojivoto deployment from a zip file to a single YAML file.

release: publish emojivoto as yml instead of zip

---

.github/workflows/runtime-reproducibility.yml

This tests whether the Contrast runtime components are reproducible between two distinct ubuntu-{20.04,22.04} systems.
Example Runs: https://github.com/edgelesssys/contrast/actions/runs/9644569372, https://github.com/edgelesssys/contrast/actions/runs/9646306170

ci: add reproducibility test for runtime components

---

cli/cmd/generate.go
e2e/internal/contrasttest/contrasttest.go

Improve debug logging for by setting `RUST_BACKTRACE=1` for genpolicy and using `--log-level debug` in e2e tests.

ci: improve debug logging for e2e tests

---

flake.nix

These packages are used in some Just targets. To make onboarding easier they should be part of the devshell.

flake: add more packages to dev shell

---

node-installer/internal/constants/configuration-qemu-tdx.toml
node-installer/internal/constants/constants.go
node-installer/node-installer.go
node-installer/node-installer_test.go
node-installer/testdata/expected-aks-clh-snp.toml
node-installer/testdata/expected-bare-metal-qemu-tdx.toml

This adds support for the K3s- / RKE2-based bare-metal TDX deployment platforms in the node-installer. Depending on which platform is provided to the node-installer command line, different units are restarted, configs are written, etc. This does not yet add support of writing the appropriate commandline in the node-installer deployment, as this will be done in a follow-up PR. Thus, for now, to keep main healthy and deploy-able, we default to AKS-CLH-SNP in the node-installer if no platform is specified.

node-installer: support bare-metal platforms

---

internal/manifest/manifest.go

This tries to parse the seed share owner keys when validating the manifest.

manifest: validate seed share owner pubkeys

---

e2e/openssl/openssl_test.go
internal/ca/ca.go
internal/ca/ca_test.go

We accidentally used the certificate templates instead of the final certificates for signing intermediate and leaf, which caused the `*KeyId` fields to be missing. These fields are mandatory in TLSv3, and our certs did not pass strict verification accordingly.
This PR also adds additional tests for the recovery scenario, enforces `x509_strict` on the OpenSSL tests and removes unnecessary CA and template fields.

ca: include SubjectKeyId and AuthorityKeyId in certificates

---

cli/cmd/common.go
cli/cmd/generate.go
packages/by-name/microsoft/genpolicy/genpolicy_msft_cache_path.patch
packages/by-name/microsoft/genpolicy/package.nix

Upstream PR: https://github.com/kata-containers/kata-containers/pull/9864
For now, this should have no change to the user. 
The question is, how we now want to use this option. Also have a similar flag in our CLI or just have a general home/.config path.
TODO:

genpolicy: add flag for cache path

---

e2e/openssl/openssl_test.go
internal/ca/ca.go
internal/ca/ca_test.go

Backport of #655 to `release/v0.7`.
---
We accidentally used the certificate templates instead of the final certificates for signing intermediate and leaf, which caused the `*KeyId` fields to be missing. These fields are mandatory in TLSv3, and our certs did not pass strict verification accordingly.
This PR also adds additional tests for the recovery scenario, enforces `x509_strict` on the OpenSSL tests and removes unnecessary CA and template fields.

[release/v0.7] ca: include SubjectKeyId and AuthorityKeyId in certificates

---

docs/docs/deployment.md
docs/docs/examples/emojivoto.md

Without the --reference-values flag, the generate command will produce an invalid manifest.

docs: use --reference-values aks flag on generate

---

cli/cmd/generate.go
cli/cmd/recover.go
cli/cmd/set.go
internal/manifest/crypto.go
internal/manifest/crypto_test.go

This PR removes code related to workload and seedshare key handling from the CLI subcommands and consolidates it into the manifest package. This PR also adds some unit tests for the new functions.

cli: move workload & seedshare owner key handling into manifest

---

.github/workflows/release.yml
e2e/internal/contrasttest/contrasttest.go
go.mod
internal/kuberesource/parts.go
internal/kuberesource/resourcegen/main.go
internal/kuberesource/sets.go
justfile
node-installer/node-installer.go
packages/by-name/contrast/package.nix

This is the follow-up mentioned in https://github.com/edgelesssys/contrast/commit/b324c2f29113a4e449bb2d358e46d4e1232f3ecd which adds the proper templating support for the runtime deployment to the resourcegen tool. The tool now takes a platform flag, which is used to define which node-installer should be included in the runtime deployment.
As the runtime deployment now provides the node-installer with the correct platform flag, the fallback to AKS-CLH-SNP is not required anymore and can be removed.

resourcegen: deploy platform-specific node-installer 

---

cli/cmd/generate.go

This makes it more obvious to the user that this flag only ever adds keys and never removes existing keys.
This change was made following the discussion in https://github.com/edgelesssys/contrast/pull/650#pullrequestreview-2145590619.

generate: rename --workload-owner-key to --add-workload-owner-key

---

cli/cmd/generate.go

If you call `generate` twice with the same seed share owner public key, the public key would just have been appended to the list instead of checking if the public key is already present in the manifest. Now, calling `generate` twice will result in the same manifest.

generate: check for existing public key in manifest

---

.git-blame-ignore-revs

You might need to run `git config blame.ignoreRevsFile .git-blame-ignore-revs`.

git: add formatting commits to blame ignore

---

internal/kuberesource/parts.go

A typo caused the Microsoft node-installer to be included in the bare-metal TDX deployment. This fixes it by using the Kata bare-metal node-installer image URL.

kuberesource: fix image URL typo

---

node-installer/internal/constants/constants.go
packages/by-name/kata/contrast-node-installer-image/package.nix
packages/by-name/kata/runtime-class-files/package.nix

Specifying separate OVMF EFI variables and code is not possible on TDX since pflash devices are unsupported. This fixes this by specifying a full bundled OVMF image.
related-to: https://github.com/kata-containers/kata-containers/commit/3e158001993cc2356d6ac084e6c82714210c9f24

node-installer: use full OVMF image on bare-metal TDX

---

packages/by-name/kata/contrast-node-installer-image/package.nix
packages/by-name/kata/kata-runtime/package.nix
packages/by-name/kata/runtime-class-files/package.nix
packages/default.nix

This packages a statically compiled version of the `kata-runtime` command line tool that's especially useful for debugging into Kata CVMs. On AKS, this is not necessary as of now, as the nodes contain the upstream version of the tool, and including the statically compiled version woul only bloat the node-installer image.

packages: package bare-metal kata-runtime tool

---

packages/by-name/kata/kata-agent/package.nix
packages/by-name/kata/runtime-class-files/package.nix

This adds an upstream patch mounting the configfs for CC report querying into the guest container through the Kata agent.

packages: mount configfs into bare-metal kata agent

---

internal/attestation/snp/issuer.go

We only used that device to query the Product, but we don't actually need the device to do that. Not opening the device devices saves us from having to mount it in the first place.

issuer: don't open sev-guest device

---

internal/kuberesource/mutators.go
internal/kuberesource/resourcegen/main.go
internal/kuberesource/sets.go

We sometimes see EOF or other connectivity problems in e2e tests, which suggest server unavailability. It turns out that we don't have a lot of readiness probes in the emojivoto demo, so the `WaitFor` calls in the e2e test are not quite sufficient to ensure availability. My suspicion is that this started getting visible after #573, which had the (side) effect of serializing container startup.
* Adds HTTP readiness probe to the Emojivoto frontend.
* Adds TCP readiness probes to the Emojivoto backends. 
- Ideally, these would be gRPC probes, but the demo does not register a health server.  
- Next preferred would be HTTP probes on the metrics endpoint, but the service mesh enforces mTLS and I can't easily change that because we rely on that in tests.
* Removes the egress-only service mesh …

e2e: add readiness probes to emojivoto pods

---

packages/by-name/kata/genpolicy/package.nix
packages/by-name/kata/kata-runtime/0001-govmm-Directly-pass-the-firwmare-using-bios-with-SNP.patch
packages/by-name/kata/kata-runtime/0002-emulate-CPU-model-that-most-closely-matches-the-host.patch
packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
packages/by-name/kata/kata-runtime/package.nix

This PR adds some patches required for running kata-containers on bare metal and make it work with our attestation flow.

kata: add patches for bare metal SNP

---

cli/cmd/generate.go
docs/docs/deployment.md
docs/docs/examples/emojivoto.md
e2e/genpolicy/genpolicy_test.go
e2e/getdents/getdents_test.go
e2e/internal/contrasttest/contrasttest.go
justfile
node-installer/platforms/platforms.go

For consistency, we should use the platform string for the reference-values flag in the CLI.

cli: use platform string for reference-values flag

---

internal/attestation/snp/cached_client_test.go

Nothing in the implementation of `CachedHTTPSGetter` guarantees that parallel access to the getter does not result in parallel backend calls. This is a source of sporadic test failures, e.g. https://github.com/edgelesssys/contrast/actions/runs/9641091365/job/26586044940?pr=620#step:11:322.
I'd suggest to just remove the final check and keep the parallel test for race detection.

snp: don't test properties that are not guaranteed

---

cli/cmd/generate.go

Right now, not passing the flag leads to an undescriptive error as we try to parse the empty value as platform. As the upcoming release will still only support aks-clh-snp, mark the flag as required for now.

generate: mark `--reference-values` flag as required

---

cli/cmd/generate.go

The file permissions were previously configured in a way that every user could read the keys that were written to disk. This PR sets the correct file permissions so that only the file owner can read the key.

cli: change key file permissions to 0600

---

.github/actions/bump_version/action.yml

The action was missing an initialization of the `current` variable.
This leads to the current version being omitted from the commit message.
See https://github.com/edgelesssys/contrast/commit/f7c10e613c8b495b744cb3e377008bd57531bf41 for example.
Load current version from `version.txt` before writing the new version to fix this.

ci: fix missing "current version" in commit message from `bump_version` action

---

packages/by-name/kata/runtime-class-files/package.nix
packages/by-name/qemu-static/0001-avoid-duplicate-definitions.patch
packages/by-name/qemu-static/0001-fix-static-build.patch
packages/by-name/qemu-static/0002-add-options-for-library-paths.patch
packages/by-name/qemu-static/package.nix
packages/default.nix

This is based on nixpkgs PRs #30070, #309929, and #314998.

nix: build static QEMU

---

.github/workflows/static.yml

This PR fixes a typo in the CI pipeline name.

ci: fix typo

---

.github/workflows/e2e_policy.yml
e2e/policy/policy_test.go
go.mod
packages/by-name/contrast/package.nix

Add an e2e test that confirms that a pod cannot join again after it was removed from the policy and manifest.
A successful test run can be found [here](https://github.com/edgelesssys/contrast/actions/runs/9778895950/job/26996776008?pr=672).

ci: add an e2e test for policy changes

---

packages/by-name/qemu-static/package.nix

This PR adds support for building qemu-static with the SEV-SNP [patches](https://github.com/AMDESE/linux/tree/snp-guest-req-v3).

nix: add support for building QEMU with SEV-SNP patches

---

coordinator/meshapi.go
docs/docs/architecture/observability.md
e2e/policy/policy_test.go

Counters should have a _total suffix, so we are renaming
`contrast_meshapi_attestation_failures` -> `contrast_meshapi_attestation_failures_total`.
This will also be enforced by https://github.com/edgelesssys/contrast/pull/721 in the future.

meshapi: follow best practice for metric names

---

internal/kuberesource/parts.go
justfile
node-installer/internal/constants/constants.go
node-installer/node-installer.go
node-installer/node-installer_test.go
node-installer/testdata/expected-aks-clh-snp.toml
packages/by-name/microsoft/genpolicy/0004-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
packages/by-name/microsoft/genpolicy/package.nix
packages/containers.nix

With this change, we improve the stability of Contrast by deploying our own tardev-snapshotter on the host as part of the node-installer deployment. Previously, the Contrast runtime would use the tardev-snapshotter installed on the host, which is managed by Azure. However, the snapshotter is highly coupled with the guest image, and breaking changes to the snaphotter led to workload pods not being able to start in Contrast. Therefore, we are shipping a pinned snapshotter as part of the runtime. This will also allow running multiple Contrast runtime next to each other that require different versions of the snapshotter.

node-installer: configure and run tardev-snapshotter

---

packages/destroy-coco-aks.sh

When changing the region in justfile.env, the resource group must be deleted as there cannot be 2 groups with the same name. Skip that step in CI, as the creds are only scoped to the rg in that case.

scripts/destroy-coco-aks: delete resource group if not in ci

---

go.mod
go.sum
internal/kuberesource/parts.go
internal/kuberesource/sets.go
node-installer/internal/constants/configuration-qemu-snp.toml
node-installer/internal/constants/constants.go
node-installer/node-installer.go
node-installer/node-installer_test.go
node-installer/platforms/platforms.go
node-installer/testdata/expected-bare-metal-qemu-snp.toml
node-installer/testdata/expected-bare-metal-qemu-snp.toml.tmpl
node-installer/testdata/expected-bare-metal-qemu-tdx.toml.tmpl
node-installer/testdata/input-bare-metal-qemu-snp.toml.tmpl
node-installer/testdata/input-bare-metal-qemu-tdx.toml.tmpl
packages/by-name/OVMF-SNP/package.nix
packages/by-name/contrast-node-installer/package.nix
packages/by-name/contrast/package.nix
packages/by-name/kata/contrast-node-installer-image/package.nix
packages/by-name/kata/genpolicy/package.nix
packages/by-name/kata/kata-kernel-uvm/package.nix
packages/by-name/kata/runtime-class-files/package.nix

This PR implements the first required steps for bare-metal SNP support and some drive-by fixes for the node-installer.

work on bare-metal SNP support in node-installer

---

internal/manifest/crypto_test.go
packages/by-name/contrast/package.nix

Makes test of manifest package ~70% faster (12.5s -> 3.5s).

manifest: use constant keys for faster tests; contrast: skip fixup phase

---

renovate.json5

The node-installer Go package is replaced locally in the go.mod and thus should not be updated by renovate.

renovate: ignore node-installer

---

coordinator/main.go
initializer/main.go
internal/atls/atls.go
internal/atls/atls_test.go
internal/atls/issuer.go
internal/attestation/oid.go

Our aTLS code needs to be adjusted to allow for multiple attestation variants. While we did allow one to have multiple validators before, we tried to validate the first matching one and instantly errored out if validation for that validator failed. Now, we can have multiple matching validators and try all until one successfully validated the document, or until the list of applicable validators is exhausted, where we can return an error.

atls: try to attest with all validators

---

packages/by-name/kata/kata-image/package.nix
packages/by-name/kata/kata-runtime/0001-govmm-Directly-pass-the-firwmare-using-bios-with-SNP.patch
packages/by-name/kata/kata-runtime/0002-emulate-CPU-model-that-most-closely-matches-the-host.patch
packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
packages/by-name/kata/kata-runtime/package.nix

There's a bug in patch 0003 which causes wrong arguments for QEMU and thus prevents starting VMs ~- patch 0004 in this PR fixes that bug. Since 0003 corresponds to an open upstream PR, I'd rather not integrate the patch here into 0003, so that we have a clear history of the modifications.~
There was another bug in the upstream PR, which assumed hex encoding for MRCONFIGID where it should have been base64.
I amended 0003 to fix these, and subsequently changed to a restrictive default policy.

kata: use restrictive default policy

---

cli/cmd/policies.go

We only wrote the `coordinator-policy.sha256` file if the coordinator hash did not correspond to the embedded hash. This behavior is inconsistent and can cause problems, for example when users anticipate a diffferent hash but the policy happens to be the same as the default one. With this change, we're always writing the file.

cli: always write the coordinator policy hash file

---

packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
packages/by-name/kata/kata-runtime/package.nix

This PR changes the kata patches to always use sha-256 - even on TDX. Previously we used sha-384 on TDX, but this lead to problems because we'd need to store two different hashes in the manifest. The init-data proposal in upstream kata will also allow hashes with sizes that don't match the host-data/mrconfigid fields.
This PR also fixes some of the surrounding TODOs to ensure that the policy hash is always enforced.

kata-agent: always use 256-bit hashes and never skip policy validation

---

coordinator/main.go

Previously, the errgroup would wait for all goroutines to terminate, causing the error of one failing server to never be logged.

coordinator: correct shutdown, report serve errors

---

packages/by-name/microsoft/genpolicy/genpolicy_msft_settings_prod.patch
packages/by-name/microsoft/genpolicy/package.nix

Logs may contain sensitive data and so they should be hidden by default. Upstream kata hides logs by default, but the Microsoft fork made them visible. This patch reverts back to hiding the logs. This won't affect the coordinator though because it uses a different set of settings. Note that this settings file is only included in release builds (.#cli-release).
Logs can be re-enabled by changing the `ReadStreamRequest` in settings.json to `true`.

genpolicy: hide logs by default

---

cli/cmd/policies.go
coordinator/internal/authority/authority.go
coordinator/internal/authority/authority_test.go
coordinator/internal/authority/userapi_test.go
e2e/openssl/openssl_test.go
e2e/policy/policy_test.go
internal/manifest/manifest.go
internal/manifest/manifest_test.go

This field will be used as part of the workload secret feature (RFC 007) to generate secrets.

manifest: add WorkloadSecretID field

---

nodeinstaller/internal/constants/constants.go
nodeinstaller/node-installer.go
packages/by-name/kata/contrast-node-installer-image/package.nix
packages/by-name/microsoft/contrast-node-installer-image/package.nix

This allows using the runtime name as replacement in paths outside of opt/edgeless.

node-installer: only replace runtimeName in paths

---

internal/kuberesource/sets.go

The non-service-mesh emojivoto deployment still uses HTTPS and not HTTP. This is implemented in the web container itself.
This fixes the deployment of `just default emojivoto` in which previously the web pod did not get ready, now it does.

resourcegen: always use https startup probe for web pod

---

justfile
packages/scripts.nix

Packaging the script with nix makes it work even if `gcloud` is not in the path.

just: credential getter as nix script

---

coordinator/internal/authority/authority.go
coordinator/internal/authority/authority_test.go
coordinator/internal/authority/credentials.go
coordinator/internal/authority/userapi.go
coordinator/main.go
coordinator/meshapi.go

This fixes a race condition between `SNPValidateOpts`, `ValidateCallback` and `SetManifest`. It should also make it easier to evolve validation logic based on state. 
Now that we have the current state available in the meshapi handler, we can move the certificate issuance there and not deal with that in the validation path.

coordinator: pass state as AuthInfo to meshapi

---

coordinator/internal/authority/authority.go

This struct no longer is used since https://github.com/edgelesssys/contrast/pull/791.

authority: remove unused Bundle struct

---

cli/cmd/common.go
cli/cmd/recover.go
cli/cmd/set.go
cli/cmd/verify.go
coordinator/internal/authority/authority.go
coordinator/internal/authority/authority_test.go
coordinator/internal/authority/credentials.go
initializer/main.go
internal/atls/atls.go
internal/attestation/snp/validator.go
internal/grpc/dialer/dialer.go
internal/manifest/constants.go
internal/manifest/manifest.go
internal/manifest/manifest_test.go
internal/manifest/referencevalues.go
packages/by-name/contrast/package.nix

This changes the attestation (as of now, only SEV-SNP) to be passed
multiple validators. The aTLS code already handles multiple validators,
but the code previously passed only one. This way, attestation will now
work by being handed a list of validators, and returning success as soon
as one can successfully validate a report. Furthermore, the
`atls.NoValidator` is now obsolete, and semantically represented by
passing an empty list of validators.

treewide: allow multiple validators

---

cli/main.go
internal/constants/constants.go
packages/by-name/contrast/package.nix

This PR changes the JSON dump back into a human readable version dump :)

cli: switch back to human readable version information

---

.github/actionlint.yaml
.github/workflows/e2e_kubernetes.yaml
.github/workflows/e2e_openssl_baremetal.yml
.github/workflows/e2e_regression.yml
cli/cmd/generate.go
e2e/genpolicy/genpolicy_test.go
e2e/getdents/getdents_test.go
e2e/internal/contrasttest/contrasttest.go
e2e/internal/kubeclient/deploy.go
e2e/internal/kubeclient/portforward.go
e2e/openssl/openssl_test.go
e2e/policy/policy_test.go
e2e/servicemesh/servicemesh_test.go
justfile
nodeinstaller/internal/config/config.go
nodeinstaller/internal/constants/constants.go
nodeinstaller/node-installer.go
packages/by-name/contrast/package.nix
packages/by-name/kata/contrast-node-installer-image/package.nix
packages/by-name/kata/kata-kernel-uvm/package.nix
packages/by-name/kata/snp-launch-digest/package.nix
packages/by-name/qemu-static/package.nix

This PR implements all the necessary changes to run CI on our baremetal machine in the office.

preparations for e2e tests on baremetal SNP

---

nodeinstaller/internal/constants/constants.go

This was moved before the unmmashal of the default config, which would lead to the default config taking precedence.

node-installer: fix debug config

---

e2e/openssl/openssl_test.go

The openssl test now additionally uses multiple reference values to test attestation with multiple validators. Only the second one of the provided validators should successfully validate the attestation document.

e2e: specify multiple reference values in openssl test

---

cli/cmd/recover.go
cli/cmd/set.go
cli/cmd/verify.go
coordinator/internal/authority/credentials.go
coordinator/main.go
initializer/main.go
internal/atls/atls.go
internal/attestation/snp/validator.go
internal/grpc/atlscredentials/atlscredentials.go
internal/grpc/dialer/dialer.go

Previously we reported every single validator error even if there's one validator that passes. This lead to noisy logs and incorrect metrics.

atls: only report attestation error if all validators fail

---

.github/actions/setup_nix/action.yml
.github/workflows/static.yml

github hosted runners have a second disk under /mnt that we can use for the builder volume.

ci: always cleanup runner, create nix builder volume under /mnt

---

justfile

As undeploy will now delete the namespace including the node-installer we must re-deploy it when calling deploy.

just: fix deploy after undeploy

---

docs/docusaurus.config.js

Enable docusaurus's broken anchor detection. (Currently detects none.)

docs: enable broken anchor detection

---

cli/cmd/common.go
cli/main.go
coordinator/internal/authority/credentials.go
internal/attestation/tdx/validator.go
internal/manifest/manifest.go
internal/manifest/referencevalues.go
packages/by-name/contrast/package.nix

This PR implements the necessary functions to generate validation options for TDX and adds the TDX validators to the list of validators. This is enough to make `set` work.
Some caveats/TODOs:
- We don't cache certificates yet.
- We don't validate the launch measurements (we only validate the TCB).
- The coordinator doesn't add the certificate extensions yet.

manifest: use tdx validator

---

packages/by-name/nydus-snapshotter/0001-disable-database-flock-timeout.patch
packages/by-name/nydus-snapshotter/package.nix

Removing this timeout prevents the nydus-snapshotter from erroring out if there's already another instance running.

nydus-snapshotter: disable database flock timeout

---

packages/by-name/contrast/package.nix

We observed these new TCB values in a report on 08/14/2024.
For safety, we shouldn't merge this until 08/28/2024.

nix: bump reference values for SNP on AKS

---

.github/workflows/e2e_kubernetes.yaml
.github/workflows/e2e_openssl_baremetal.yml
.github/workflows/e2e_regression.yml

The matrix strategy defaults to failing fast: If any one of the test cases fails all other cases get cancelled as well. The problem with this is that sometimes tests fail not because the code is bad, but because the test is flaky. In an ideal world, we'd make the tests less flaky, but until then we shouldn't abort all other tests in the matrix. The advantage of not failing fast is that when we inevitably have to manually push the re-run button, we don't have to wait for all test cases to complete, but only for the one that failed.

ci: don't fail fast

---

packages/by-name/contrast/package.nix

Some regions (e.g. `NorthEurope`) still use older TCBs, so we can't increase the default without breaking deployments in those regions.
Reverts edgelesssys/contrast#811

Revert "nix: bump reference values for SNP on AKS"

---

e2e/regression/regression_test.go

Fix the cleanup of the regression e2e tests by wrapping it in a `t.Cleanup()`. Previously, the cleanup could fail if the test panicked or exited early.

e2e: fix regression cleanup

---

packages/by-name/kata/kata-image/package.nix

This fixes a reproducibility issue, as the db contained timestamps.

kata.kata-image: don't include tdnf/history.db

---

packages/by-name/cloud-api-adaptor/package.nix

Packaging the CAA binaries, based on https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/Makefile

packages/cloud-api-adaptor: init at 0.9.0

---

e2e/internal/kubeclient/deploy.go
e2e/openssl/openssl_test.go

We've seen a lot of spurious errors when connecting to various resources. If we wait just a little longer the vast majority of these errors go away. This is not clean, but it works well.
I ran all e2e tests three times with these changes and only saw two failures: One of them was a timeout in the `certificate rotation and ... restart` test (probably because of the artificial delay introduced here), so I raised the timeout for that test. The other test failure was related to a DNS error while pulling the images. I didn't do anything to prevent that from happening again because I haven't seen this error occur much. All other test jobs succeeded on the first try.
The downside of this change is that all e2e tests now run a bit longer, but I'd say we'd likely want to prioritize CI stability …

e2e: always sleep for 5 more seconds after resource is up

---

docs/docs/components/runtime.md
docs/docs/deployment.md
docs/docs/examples/emojivoto.md
docs/docs/features-limitations.md
docs/docs/getting-started/bare-metal.md
docs/sidebars.js

This PR updates the documentation to include setup guides for SNP on bare metal and updates the architecture section for the changes regarding VMMs and snapshotters.
This PR doesn't include any documentation on TDX on bare metal.

docs: update docs to include bare metal SNP

---

docs/docs/getting-started/cluster-setup.md
packages/create-coco-aks.sh
packages/scripts.nix

It is not necessary to create secondary node pool if you create the AKS with KataCcIsolation enabled.

Simplify Azure cluster setup

---

packages/by-name/contrast/package.nix
packages/by-name/kata/kata-image/package.nix
packages/by-name/kata/kata-kernel-uvm/package.nix
packages/by-name/kata/snp-launch-digest/package.nix
packages/by-name/kata/tdx-launch-digests/package.nix
tools/tdx-measure/main.go
tools/tdx-measure/rtmr/rtmr.go

This PR upgrades the kernel to version 6.11. This new kernel will measure the kernel command line into RTMR[2], so we also update tdx-measure to consider the kernel command line when calculating RTMR[2].

include kernel command line in TDX measurement

---

docs/docs/getting-started/bare-metal.md
tools/vale/styles/config/vocabularies/edgeless/accept.txt

If this limit isn't raised, kata will fail with `failed to create containerd task: failed to create shim task: Creating watcher returned error too many open files: unknown` when running many containers.

docs: add instructions to raise user.max_inotify_instances limit

---

packages/by-name/kata/kata-kernel-uvm/package.nix

This config option enables signing of kernel modules. This is a source of non-reproducability. Disable it.

kata.kata-kernel-uvm: disable CONFIG_MODULE_SIG

---

.github/workflows/e2e.yaml
e2e/volumestatefulset/volumestatefulset_test.go
internal/kuberesource/sets.go
packages/by-name/kata/kata-runtime/0001-govmm-Directly-pass-the-firwmare-using-bios-with-SNP.patch
packages/by-name/kata/kata-runtime/0002-emulate-CPU-model-that-most-closely-matches-the-host.patch
packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
packages/by-name/kata/kata-runtime/0004-virtcontainers-allow-specifying-nydus-overlayfs-bina.patch
packages/by-name/kata/kata-runtime/0005-genpolicy-deny-UpdateEphemeralMountsRequest.patch
packages/by-name/kata/kata-runtime/0006-genpolicy-validate-create-sandbox-storages.patch
packages/by-name/kata/kata-runtime/0007-genpolicy-enable-sysctl-checks.patch
packages/by-name/kata/kata-runtime/0008-genpolicy-read-bundle-id-from-rootfs.patch
packages/by-name/kata/kata-runtime/0009-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
packages/by-name/kata/kata-runtime/0010-genpolicy-settings-bump-OCI-version.patch
packages/by-name/kata/kata-runtime/0011-genpolicy-settings-change-cpath-for-Nydus-guest-pull.patch
packages/by-name/kata/kata-runtime/0012-genpolicy-allow-image_guest_pull.patch
packages/by-name/kata/kata-runtime/0013-runtime-agent-mounts-Mount-configfs-into-the-contain.patch
packages/by-name/kata/kata-runtime/0014-genpolicy-bump-oci-distribution-to-v0.12.0.patch
packages/by-name/kata/kata-runtime/0015-agent-bump-image-rs-version.patch
packages/by-name/kata/kata-runtime/0016-genpolicy-support-mount-propagation-and-ro-mounts.patch
packages/by-name/kata/kata-runtime/package.nix

This PR enables mounting block devices onto `emptyDir` volumes on bare metal by changing the policy to understand mount propagation.
In our bare metal CI the cryptsetup calls OOMed, leading to corrupted LUKS devices. As far as I understand, this is due to the memory requirements of the PBKDF, which are limited by total VM memory, but not container cgroup limits[^1]. On bare metal, we currently have much more memory than the limit, which probably leads to an optimistic choice of PBKDF memory. I'm manually restricting `--pbkdf-memory` to 10M to work around this.
Only tangentially related, I'm setting the retention policy of the test volume claims to `DELETE`. This is not necessary for regular CI operations, but helps when manually working with this resource.
[^1]: …

bm: enable persistent volumes on block devices

---

tools/tdx-measure/rtmr/rtmr.go

It's always nicer to see how a value is constructed/structured rather than just hard-coding it. Now that we know how that value is derived, we can also be more confident that it won't change in the future (it's mostly comprised of constants).

tdx-measure: assemble Boot0000 by hand

---

justfile

We've recently recreated the k3s on the TDX server in our office, so new credentials are needed.

justfile: bump secret version for tdxbm

---

.gitignore
infra/azure-peerpods/main.tf
infra/azure-peerpods/vars.tf
justfile
packages/by-name/azure-no-agent/no-agent.sh
packages/by-name/cloud-api-adaptor/package.nix
packages/by-name/image-podvm/debug.nix
packages/by-name/image-podvm/image.nix
packages/by-name/image-podvm/kata.nix
packages/by-name/image-podvm/package.nix
packages/scripts.nix

This adds the kata components to the peerpod image and makes it usable with the upstream coco operator setup for peerpods.
To test, you can create a cluster and deploy with:
```sh
just create AKS-PEER-SNP
just get-credentials-peerpod 
just node-installer AKS-PEER-SNP
```

image-podvm: add kata components

---

.github/workflows/e2e.yaml
cli/cmd/common.go
coordinator/internal/authority/credentials.go
coordinator/meshapi.go
e2e/policy/policy_test.go
internal/attestation/snp/validator.go

*BREAKING*: The Prometheus counter `contrast_meshapi_attestation_failures_total` is not incremented anymore if a workload has matching reference values but an untrusted policy hash. These rejections are now visible in the `contrast_grpc_server_handled_total` counter with field `grpc_code=PermissionDenied`. 
---
The policy hash is passed as `HOSTDATA` on SNP and as `MRCONFIGID` on TDX. In the SNP validation, we used to check the `HOSTDATA` too, but we did not introduce this for TDX. As a consequence, the metrics observed on SNP and TDX are different: on SNP, an unknown hash ends up in `attestation_failures_total`, while on TDX it ends up in `grpc_server_handled_total` with an internal error status. Thus, we could not have a simple portable policy test that relied on the metrics.
This PR …

Align policy hash verification between SNP and TDX 

---

e2e/genpolicy/genpolicy_test.go
e2e/getdents/getdents_test.go
e2e/internal/contrasttest/contrasttest.go
e2e/internal/kubeclient/deploy.go
e2e/internal/kubeclient/kubeclient.go
e2e/openssl/openssl_test.go
e2e/policy/policy_test.go
e2e/regression/regression_test.go
e2e/release/release_test.go
e2e/servicemesh/servicemesh_test.go
e2e/volumestatefulset/volumestatefulset_test.go
e2e/workloadsecret/workloadsecret_test.go

This adds the ability to wait for different conditions using the `kubeclient.WaitFor` function. Supported conditions are:
- `Ready`: This has the same functionality as the old `kubeclient.WaitFor`.
- `Running`: Waits until all containers of all pods of the corresponding resource are running or until the context timeouts.
- `InitContainersRunning`: Same as `Running`, but only check the initial containers of all pods of the corresponding resource.
- `Added`, `Bookmark`, `Deleted`, `Modified`: Those are synonymous for waiting on the corresponding `watch.EventType` found in `k8s.io/apimachinery/pkg/watch`.

e2e: add ability to wait for different conditions in `kubeclient.WaitFor`

---

docs/docs/architecture/security-considerations.md
docs/docs/deployment.md
docs/sidebars.js

Outlines a couple of DOs and DON'Ts when writing apps for Contrast. The idea is that, after reading the recommendations, an author of a Kubernetes app can tell what's safe to do in YAML and what needs scrutiny.

docs: add security considerations

---

.github/workflows/e2e.yaml
.github/workflows/e2e_manual.yml
.github/workflows/e2e_nightly.yml
.github/workflows/e2e_openssl.yml
.github/workflows/e2e_regression.yml
.github/workflows/e2e_service_mesh.yml

This achieves the following goals:
1. Only run the openssl tests for PRs.
2. Only run the servicemesh tests when its files have been touched.
3. Run all other tests every day at night (and send notifications on failure).
4. Keep the manual dispatch workflow.
I don't think it's possible to reasonably achieve all of those with a single workflow file (though I'm open to suggestions), so I've turned `e2e.yaml` into a reusable workflow that's invoked by other workflow files with different parameters.

ci: rework e2e tests

---

docs/docs/deployment.md
docs/docs/examples/emojivoto.md
e2e/internal/contrasttest/contrasttest.go
e2e/release/release_test.go
justfile
packages/by-name/contrast/package.nix

We don't ship minimum default SVNs for bare metal, so we shouldn't have a default for minimumTeeTcbSvn. Having a default for mrSeam is problematic because it legitimately can change as a customer updates their firmware.

contrast: remove default SVNs for TDX

---

e2e/internal/contrasttest/contrasttest.go
e2e/policy/policy_test.go

This tests that the `contrast verify` command does not verify a coordinator with a different policy by changing the expected coordinator policy hash before calling `verify`.

e2e: test verify on coordinator with different policy

---

justfile

We had to do a reinstall of the k3s cluster on our SNP server. The new config is available under version 2 of the secret.

justfile: bump version for snp kubeconfig secret

---

e2e/policy/policy_test.go

The policy hash is hex-encoded and unfortunately, XORing 1 into hex digits doesn't always yield valid hex digits:
```
>>> [chr(ord(hex(i)[2:])^1) for i in range(16)]
['1', '0', '3', '2', '5', '4', '7', '6', '9', '8', '`', 'c', 'b', 'e', 'd', 'g']
```
Instead, decode the hex-encoded hash and XOR 1 into that.

e2e/policy: ensure that modified policy hash is valid hex

---

internal/kuberesource/sets.go

Use a StartUp probe so that the application container afterwards does not start until the probe has finished. Also use an explicit file that is written to the volume-init container so that we only continue after the script has been fully executed.

sets: add StartupProbe to vss deployment

---

packages/nixos/image.nix

image-podvm: drop assertion supression

---

packages/cleanup-bm.sh
packages/containers.nix
packages/scripts.nix
tools/bm-maintenance/deployment_tdx_snp.yml

This adds a cronjob to clean up the runtime classes on the bare-metal servers. All unused runtime classes get deleted and the containerd config is updated, and the corresponding folder in `/opt/edgeless` gets deleted as well.

tools: periodically clean up bare-metal servers

---

internal/kuberesource/parts.go

There's no strong reason for having resource limits on the node-installer and given the unpredictable nature of the kernel's resource accounting, we should remove the resource limits so that we don't run into unexpected OOMs.
Fixes f5da52d
Cc @blenessy

node-installer: remove resource limits

---

docs/docs/troubleshooting.md

seperated -> separated
afterward -> afterwards

docs/troubleshooting: fix typo

---

justfile

The default platform for the justfile is now configured from the `justfile.env` file instead of from within the justfile itself. However, it is still possible to pass different platforms as an argument, e.g., `just node-installer K3s-QEMU-TDX`.

just: configure platform from jusfile.env file

---

packages/by-name/contrast/package.nix

Change back to version strings of the form "v1.2.3", instead of just "1.2.3". Only relevant for the version string processed by the CLI.

packages/contrast: prefix version string with v

---

infra/azure-peerpods/main.tf
infra/azure-peerpods/vars.tf

Improve the default values in the deployment a little:
- Free-tier clusters are not always available, so this makes the deployment default to using a standard-tier cluster.
- GPU instances (which are the only ones we provide a working image for at the moment) are unavailable in germanywestcentral. Therefore, default to a GPU-enabled region here. This should not have any disadvantages compared to germanywestcentral for non-GPU use.

infra: better default values

---

.github/workflows/e2e.yml
.github/workflows/e2e_aks_runtime.yml
e2e/aks-runtime/aks_runtime_test.go
e2e/internal/az/aks.go
e2e/internal/az/confcom.go
e2e/internal/contrasttest/contrasttest.go
flake.nix
overlays/nixpkgs.nix
packages/by-name/contrast/package.nix

Add a test that checks if something in azure upstream is broken by deploying a simple container with the `kata-cc-isolation` runtime class. You can view a successful workflow run [here](https://github.com/edgelesssys/contrast/actions/runs/11386327564/job/31678275073?pr=939).

e2e: add a test for checking AKS upstream

---

overlays/erofs-utils-reproducibility.patch
overlays/nixpkgs.nix

Please verify reproducibility on your local system with 
```
nix build .#image-podvm --builders "" &&
nix build .#image-podvm --builders "" --rebuild && 
[[ $(sha256sum result/image-podvm-gpu_1-rc1.raw | cut -d' ' -f1) == f1f9c021b2aae46771b138b603e269032e9fc6369a7ce17391cc54899e359d0f ]]
```
If you face reproducibility issues, try to optimise your nix store, as the issue might be related to hard linking. There is a (soft) improvement on that already in unstable (but we are currently a bit behind), but it is also a topic of future work.
```
nix store optimise
```

erofs: improve reproducibility of podvm images

---

packages/by-name/kata/kata-runtime/0001-govmm-Directly-pass-the-firwmare-using-bios-with-SNP.patch
packages/by-name/kata/kata-runtime/0002-emulate-CPU-model-that-most-closely-matches-the-host.patch
packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
packages/by-name/kata/kata-runtime/0004-genpolicy-validate-create-sandbox-storages.patch
packages/by-name/kata/kata-runtime/0005-genpolicy-enable-sysctl-checks.patch
packages/by-name/kata/kata-runtime/0006-genpolicy-read-bundle-id-from-rootfs.patch
packages/by-name/kata/kata-runtime/0007-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
packages/by-name/kata/kata-runtime/0008-genpolicy-settings-bump-OCI-version.patch
packages/by-name/kata/kata-runtime/0009-genpolicy-settings-change-cpath-for-Nydus-guest-pull.patch
packages/by-name/kata/kata-runtime/0010-genpolicy-allow-image_guest_pull.patch
packages/by-name/kata/kata-runtime/0011-runtime-agent-mounts-Mount-configfs-into-the-contain.patch
packages/by-name/kata/kata-runtime/0012-genpolicy-bump-oci-distribution-to-v0.12.0.patch
packages/by-name/kata/kata-runtime/0013-genpolicy-support-mount-propagation-and-ro-mounts.patch
packages/by-name/kata/kata-runtime/0014-tools-don-t-clean-build-root-when-generating-rootfs.patch
packages/by-name/kata/kata-runtime/0015-kata-agent-fixing-bug-of-unable-setting-hostname-cor.patch
packages/by-name/kata/kata-runtime/0016-agent-Correct-rustjail-device-filemode-permission-ty.patch
packages/by-name/kata/kata-runtime/package.nix

Fixes https://github.com/edgelesssys/contrast/issues/953

kata.kata-runtime: cherry pick 3.10.1 bug fixes

---

flake.nix
overlays/nixpkgs.nix

overlay: remove azure-cli with confcom extension

---

.github/workflows/e2e_runtime-reproducibility.yml

Follow up of #947. New successful run can be found [here](https://github.com/edgelesssys/contrast/actions/runs/11502616673).

e2e: fix runtime reproducibility test and also check `kata.contrast-node-installer-image`

---

.github/workflows/asciinema.yml
.github/workflows/e2e.yml
.github/workflows/release.yml
justfile

Instead of having multiple commands like `get-credentials-tdxbm` or `get-credentials-snpbm`, the platform can simply be read from the `justfile.env` file.

just: use default platform for get-credentials

---

.gitignore
cli/genpolicy/config.go
cli/main.go
infra/azure-peerpods/main.tf
internal/kuberesource/parts.go
internal/platforms/platforms.go
justfile
nodeinstaller/internal/constants/configuration-peerpod.toml
nodeinstaller/internal/constants/constants.go
nodeinstaller/node-installer.go
nodeinstaller/node-installer_test.go
nodeinstaller/testdata/expected-aks-peer-snp.toml
packages/by-name/contrast/package.nix
packages/scripts.nix

This PR adds support for peerpods on SEV-SNP AKS to the node-installer and adjusts our justfile to use the node-installer instead of the coco-operator-based runtime steps.

add peerpods support for the node-installer

---

packages/nixos/gpu.nix

The `production` nvidia driver in nixpkgs got updated to a version that's incompatible with H100s. This pins the nvidia driver to the specific version needed for H100s by using the upstream `mkDriver` abstraction that builds a driver compatible with the used kernel from exact driver sources.

packages/nixos: pin nvidia driver

---

.github/workflows/check_patches.yml
dev-docs/patches.md
packages/by-name/kata/kata-runtime/0001-govmm-Directly-pass-the-firwmare-using-bios-with-SNP.patch
packages/by-name/kata/kata-runtime/0002-emulate-CPU-model-that-most-closely-matches-the-host.patch
packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
packages/by-name/kata/kata-runtime/0004-genpolicy-enable-sysctl-checks.patch
packages/by-name/kata/kata-runtime/0005-genpolicy-read-bundle-id-from-rootfs.patch
packages/by-name/kata/kata-runtime/0006-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
packages/by-name/kata/kata-runtime/0007-genpolicy-settings-bump-OCI-version.patch
packages/by-name/kata/kata-runtime/0008-genpolicy-settings-change-cpath-for-Nydus-guest-pull.patch
packages/by-name/kata/kata-runtime/0009-genpolicy-allow-image_guest_pull.patch
packages/by-name/kata/kata-runtime/0010-runtime-agent-mounts-Mount-configfs-into-the-contain.patch
packages/by-name/kata/kata-runtime/0011-genpolicy-bump-oci-distribution-to-v0.12.0.patch
packages/by-name/kata/kata-runtime/0012-genpolicy-support-mount-propagation-and-ro-mounts.patch
packages/by-name/kata/kata-runtime/0013-tools-don-t-clean-build-root-when-generating-rootfs.patch
packages/by-name/kata/kata-runtime/0014-kata-sys-util-remove-obsolete-cgroups-dependency.patch
packages/by-name/kata/kata-runtime/0015-kata-sys-util-move-json-parsing-to-protocols-crate.patch
packages/by-name/kata/kata-runtime/0016-protocols-only-build-RLimit-impls-on-Linux.patch

The patch workflow we document is unfortunately not yet idempotent across committers: 
1. Commits created by `git am` are recorded with a `Committer: ` tag which depends on who is doing the committing. Since this tag is part of the commit, the commit hash changes and the leading `From <commit>` line of the patch file differs. The committer can't be overridden by a command line arg, afaik.
2. It seems like the number of characters in the `index <hash>..<hash>` lines created by `git format-patch` depends on the git version. 
Overall, the current workflow does not meet its original goal: a patch cherry-picked on the existing stack should not cause a diff in the existing patches.
I suggest the following changes to keep this clean in the future:
* Work around the idempotency by
* masking the …

ci: check for unclean patches

---

justfile

This ensures the `cloud-api-adaptor` cleanly deletes the created VMs by waiting until the deletion of all other resources has been completed before deleting the node installer and namespace.

just: ensure peerpod vms are cleaned up on undeploy

---

packages/by-name/mkNixosConfig/package.nix
packages/by-name/nvidia-ctk-oci-hook/package.nix
packages/by-name/nvidia-ctk-with-config/config.toml
packages/by-name/nvidia-ctk-with-config/package.nix
packages/nixos/gpu.nix

This enables the `podvm-image` package for use in GPU peer pods by doing the following:
- Adding a preconfigured `nvidia-ctk` package for use with peer pods GPU containers.
- Adding a package for the OCI hook required to start peer pods GPU containers.
- Placing the OCI hook in the expected path in the podvm-image if GPU use is configured.

packages: add nvidia OCI hook for peer pods

---

packages/scripts.nix

The current (default) info is 
"Contoso :: Linux :: contrast-1"
change that to
"edgelesssys :: contrast :: peer-pods"

scripts: add publisher info for peer pods image

---

packages/by-name/kata/genpolicy/genpolicy_rules_coordinator.patch
packages/scripts.nix

This fixes a bug where we would publish a coordinator deployment with a policy that can only be deployed in the default namespace.
Bug found by @3u13r

scripts: use coordinator rules/settings for bare metal

---

.github/workflows/cleanup.yml
tools/bm-maintenance/deployment_tdx_snp.yml

We had a lot of e2e regression failures because of pulling the same image with different snapshotters. This PR increases the run frequency of the cleanup job to daily, which should ensure we're running it before the weekly, and not only after.

ci: clean up images more often

---

coordinator/internal/authority/credentials.go

The gRPC stack does not log errors from the `Credentials`, and if the TLS session is not established the error won't be sent back to the client, either. With this commit, the error shows up at least in the server logs.

coordinator: add log messages for handshake failures

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Add 3 Github issue templates for:
1.  opening bug reports
2.  feature request 
3.  Q&A redirect

github: add issue template

---

go.work

This was missed in https://github.com/edgelesssys/contrast/commit/d1ea612a5024e7e39f4950cb3317fbe26e7b37a8.

go.work: update go version

---

flake.nix

This has been broken after https://github.com/edgelesssys/contrast/commit/f089bf039ebf91d207aa38f345ccfa1c5e97063c

flake: add comment to workaround renovate bug

---

.github/workflows/e2e.yml
.github/workflows/e2e_aks_runtime.yml
packages/by-name/k8s-log-collector/package.nix
packages/log-collector.yaml
packages/scripts.nix

Improve the log collection to also collect init container logs. This is done by adding a `log-collector` daemon set to every e2e cluster that saves logs from the host node which then are downloaded to the local machine through the updated `get-logs` script.

e2e: improve log collection

---

e2e/internal/kubeclient/deploy.go
e2e/policy/policy_test.go

Podvms come with a default policy, which should usually be a "SetPolicy only" policy.  The implemented e2e test ensures that no wrong default policy (i.e. allow-all) is included, by starting a container without any policy annotation and waiting for the Kata runtime event FailedCreatePodSandBox, which indicates that the container start failed as expected.
1.  waitForEvent() was added to deploy.go, following the same pattern as waitFor(), but focusing on watching the eventList and no resource
2. checkIfStartingBlocked() checks if the FailedCreatePodSandBox event with the expected message occurred

e2e: default policy test

---

.github/workflows/e2e_openssl.yml

We run e2e tests with a `pull_request` trigger and an explicit list of ignored paths. This makes it tedious to work on code that can't be excluded easily, like other workflows that don't touch e2e.
Moving to a mix of included and excluded paths should fix this issue. In particular, this commit is intended to trigger e2e on PRs that touch anything that's not in the existing ignorelist and not an unrelated Github workflow.

e2e: don't require e2e on unrelated PRs

---

dev-docs/serial-console.md
packages/kata-debug-shell.sh

This adds a little helper script to get a shell into a bare-metal Kata pod VM with a single command.

packages/kata-debug-shell: init

---

dev-docs/coco/tdx-measurements.md
packages/by-name/OVMF-TDX/0001-verify-Hobs-instead-of-measuring-them.patch
packages/by-name/OVMF-TDX/package.nix
packages/by-name/mkNixosConfig/package.nix
packages/by-name/tdx-tools/package.nix
packages/debug-qemu-tdx.sh
packages/nixos/debug.nix
tools/vale/styles/config/vocabularies/edgeless/accept.txt

This adds a suite of debugging utilities for low-level TDX problems such as mismatching RTMRs, as well as documentation on how to perform the debugging.
This includes:
- `tdx-tools` in our debug images, which is a Python utility to view RTMRs and their event log.
- A debug switch in `OVMF-TDX`, allowing to debug the TDX virtual firmware.
- A script to launch a TDX QEMU like Kata would, which can then be used with the debug build of OVMF, as Kata doesn't support it.
Additionally, some documentation is added on how to perform debugging on TDX measurements.

Add TDX debugging tools and documentation

---

.github/workflows/e2e_manual.yml
.github/workflows/e2e_nightly.yml
.github/workflows/e2e_on_pull_request.yml
.github/workflows/e2e_service_mesh.yml

Our actions tab has a lot of workflows called `e2e test`, making it hard to navigate. 
* Make the names more descriptive.
* Rename the openssl test so that the intent (execute on PR) is clear.

ci: descriptive names for tests

---

docs/docusaurus.config.js
docs/package.json
docs/static/gtagman.js

change gtag integration as requested by marketing department

docs: refactor gtag

---

packages/kata-debug-shell.sh

bash doesn't perform expansion in variables, thus the `*` in `config_file` wasn't expanded correctly (i.e. at all). Go back to the `ls -1` approach, which fixes that. Also, don't template the config path into another path, which is redundant and fails, as it's an absolute path already.

packages/kata-debug-shell: fix templating

---

internal/attestation/snp/validator.go
internal/attestation/tdx/validator.go

Validation errors are currently swallowed somewhere in the TLS stack. Debugging [e.g. this](https://github.com/edgelesssys/contrast/actions/runs/11984883207/job/33416168380#step:11:158) would be easier if we saw which step failed and why.
This commit also converts the hex-encoded reports in logs to JSON, in an attempt to make them easier to work with.

attestation: log Validate errors

---

infra/azure-peerpods/main.tf
packages/by-name/cloud-api-adaptor/0001-netops-replace-routes-instead-of-adding-them.patch
packages/by-name/cloud-api-adaptor/package.nix
packages/test-peerpods.sh

Changes to the network configuration of Azure pod VMs require a NAT gateway in the subnet. Having that is desirable anyway, because default outbound access is deprecated and scheduled for removal in 2025.
Side note: this bumps peer-pods Kata to 3.9.0, which should make it easier to integrate CAA into the node-installer.

caa: upgrade to v0.10.0

---

packages/by-name/kata/kata-agent/package.nix

The `sev` crate specifies a crate type of `dylib`, which results in a libsev.so library in the output of makeRustPackage. The library is intended for use under FFI (i.e., from C) and not necessary for the agent binary.
Removing the library sheds some 800MiB of rustc from the agent's closure and reduces the podvm-image size by 1.4GiB.
```
$ nix-store --query --size /nix/store/aw6s09mwmbifnxbm6587kgwm46jgmaa6-image-podvm-gpu-1-rc1 # before
2694330064
$ nix-store --query --size /nix/store/z14q27diajh5x3iqkbckcnvp6gb7bkr7-image-podvm-gpu-1-rc1 # after
1264297680
```

kata: remove rustc from agent closure

---

e2e/policy/policy_test.go

This fixes a bug introduced into the policy test in PR #1007, because of dependence of the policy test on the default policy test executed prior. Restarting the applied resources cleans up the containers being in FailedToCreatePodSandbox state, which takes place when started with the default policy annotation and thus allows to continue the test workflow with the generated manifest.

e2e: fix policy test dependence on default policy test

---

cli/genpolicy/genpolicy.go
cli/genpolicy/genpolicy_test.go

This allows 
* running `contrast generate` with `HTTP_PROXY` and friends
* using registry credentials from various filesystem paths supported by the `docker_credential` crate (this is not enough for full private registry support!)

cli: pass environment variables to genpolicy

---

e2e/regression/testdata/mongodb.yml
e2e/regression/testdata/prometheus.yml
e2e/regression/testdata/redis.yml
packages/by-name/microsoft/genpolicy/0001-genpolicy-add-rules-and-types-for-volumeDevices.patch
packages/by-name/microsoft/genpolicy/0002-genpolicy-add-ability-to-filter-for-runtimeClassName.patch
packages/by-name/microsoft/genpolicy/0003-genpolicy-allow-specifying-layer-cache-file.patch
packages/by-name/microsoft/genpolicy/0004-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
packages/by-name/microsoft/genpolicy/0005-genpolicy-propagate-mount_options-for-empty-dirs.patch
packages/by-name/microsoft/genpolicy/0006-genpolicy-support-HostToContainer-mount-propagation.patch
packages/by-name/microsoft/genpolicy/0007-genpolicy-support-for-VOLUME-definition-in-container.patch
packages/by-name/microsoft/genpolicy/genpolicy_msft_settings_coordinator.patch
packages/by-name/microsoft/genpolicy/genpolicy_msft_settings_dev.patch
packages/by-name/microsoft/genpolicy/package.nix

Remove the `volumeMounts` fix since https://github.com/kata-containers/kata-containers/pull/10136 was merged

kata-msft: support images with VOLUME directives

---

packages/by-name/buildVerityUKI/package.nix
packages/by-name/kata/kata-image/package.nix
packages/by-name/microsoft/kata-igvm/package.nix
packages/by-name/microsoft/kata-image/package.nix

Prior, we tried to run `patchelf` (automatically, due to the Nix stdenv) on the executable-marked OS image. This is not necessary and costs a considerable investment of time. The PR excludes the automatic patchelf hook from the build.

nixos-img: disable patchelf on executable-marked OS image

---

overlays/nixpkgs.nix

follow up to  https://github.com/edgelesssys/contrast/commit/01ab07f0fe87e5bb32d2721ad596243caea4c4df

overlays: bump treefmt to 2.1.1

---

packages/by-name/cloud-api-adaptor/package.nix
packages/nixos/azure.nix
packages/test-peerpods.sh

Azure needs special care for enabling IMDS within Peerpods. This adds a script to setup IMDS through Proxy ARP (from Peerpods upstream, see https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/podvm/files/usr/local/bin/setup-nat-for-imds.sh), so that all requests to the IMDS from within the pod are routed through an interface that is peered to the Pod VM. Verified to work in 2 distinct Azure peer pods.
It also makes a simplification by excluding `basic.target` in the `wantedBy` list of the Azure readiness report, as it's already contained in the [default dependencies](https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Default%20Dependencies).

packages/nixos: add IMDS setup script

---

cli/genpolicy/genpolicy.go
cli/genpolicy/logtranslator.go
packages/by-name/microsoft/genpolicy/0008-genpolicy-include-reference-in-logs-when-auth-failure.patch
packages/by-name/microsoft/genpolicy/package.nix

The PR includes the debug log level of genpolicy into the Contrast CLI. Thus the resulting mapping is:
Contrast info == Genpolicy warning
Contrast debug == Genpolicy info/debug
As well it patches the existing genpolicy error message in case of an authentication failure, to include the reference to the repository.

cli: genpolicy logging: Add debug log level and repository reference to auth failure

---

e2e/policy/deterministic_test.go
packages/by-name/kata/kata-runtime/0004-genpolicy-enable-sysctl-checks.patch
packages/by-name/kata/kata-runtime/0009-genpolicy-allow-image_guest_pull.patch

[This commit](https://github.com/edgelesssys/contrast/blob/f50e93b16f7cca03e0c8fd5aa70943567fe1d69c/packages/by-name/kata/kata-runtime/0004-genpolicy-enable-sysctl-checks.patch) introduced a reproducibility issue for the workload policies.
Ticket:  [AB#4297](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4297)
Take a simple example pod and generate it multiple times for K3S-QEMU-TDX (or any upstream Kata platform). The policy and hash will change from time to time.
```
while true; do
/nix/store/8di8ps56s9acndipiqynak6qilrffl97-contrast-1.2.0-pre-cli/bin/contrast \
generate --skip-initializer --reference-values K3s-QEMU-TDX test.yaml >/dev/null 2>&1
cat test.yaml | yq '.metadata.annotations["io.katacontainers.config.agent.policy"]' | base64 -d | …
```

cli: fix nondeterministic policy generation

---

coordinator/main.go
initializer/main.go
internal/atls/issuer/issuer.go
internal/atls/issuer/issuer_linux.go
internal/atls/issuer/issuer_universal.go
internal/attestation/snp/issuer/issuer.go
internal/attestation/snp/issuer/thim.go
internal/attestation/tdx/issuer/issuer.go

It is currently not possible to build the SDK / CLI on platforms other than Linux. One of the issues is that the imported packages include Linux specific code.
These components don't require it, so they shouldn't depend on it to allow for cross-platform usage.
[AB#4959](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4959)
- move the issuer code into its own sub-package
- only let the components that require it (coordinator and initializer) import the issuer package

sdk: remove Linux dependencies

---

.github/workflows/e2e.yml
.github/workflows/e2e_aks_runtime.yml
e2e/aks-runtime/aks_runtime_test.go
e2e/genpolicy/genpolicy_test.go
e2e/getdents/getdents_test.go
e2e/internal/contrasttest/contrasttest.go
e2e/openssl/openssl_test.go
e2e/policy/deterministic_test.go
e2e/policy/policy_test.go
e2e/regression/regression_test.go
e2e/servicemesh/servicemesh_test.go
e2e/volumestatefulset/volumestatefulset_test.go
e2e/workloadsecret/workloadsecret_test.go
justfile

We invoke different e2e tests with the same nix command. This nix command already defines flags that are therefore shared between all current (and future) e2e tests. Let's make it easy to introduce new shared flags while maintaining the possibility that some tests define their own additional flags.
Also introduce a new namespace suffix flag.

ci: suffix ci k8s namespaces with "-ci"

---

e2e/aks-runtime/aks_runtime_test.go

Before, when another pod was deployed into the same namespace because of our logging architecture in the CI, the test failed.

e2e/aks-runtime: filter pods for test container

---

packages/nixos/system.nix

We're configuring a tmpfs with 50% of the VMs memory capacity in kata.nix, but this configuration is only applied by systemd-remount-fs.service, which we thus need to enable. That service tries to remount all filesystems, though, so we need to define them correctly in the first place so that they can be remounted. In our case, that meant defining the / mount as read-only.
This fixes the regression test failures on main: https://github.com/edgelesssys/contrast/actions/runs/12250498650.

kata-image: allow remount service to manage /run

---

packages/nixos/kata.nix
packages/nixos/system.nix

Previously, our bare-metal Kata image weighed in at around 838MB. This PR reduces its size to about 561MB. It does so by incorporating the following changes:
- Remove Nix (CLI, daemon and store database) from the image closure. Since our image is immutable anyways, we do not need to include this anyways. Removing this saves around 188MB in image size.
- Remove Perl and Python interpreters from the image closure. These are only required for parts Nix' traditional "activation" mechanism, all of which have non-interpreter alternatives available. A tangible example for this is the population of `/etc`, which traditionally was implemented in Perl, but now has an overlayfs-based alternative for available. This saves around 90MB in image size.
Minimizations for the GPU-enabled image are …

packages/nixos: minimize image size

---

internal/attestation/certcache/cached_client.go
internal/attestation/certcache/cached_client_test.go

This PR adds logic to the cached_client.go to allow caching Certificate Revocation Lists (CRLs). Still the CRLs are always queried from the AMD's certification server (KDS) first.
Only in case of an request failure, the cache is used as fallback to allow continuing. When the cache of the CRL is expired, the HTTPs request failure is returned as an error.
In addition the test cases where adapted to cover the different branches of VCEK and CRL caching.

kds-cache: add fallback cache for CRLs on request failure

---

.github/workflows/rpm_updates.yml

Now, since the Kata image is built with NixOS, we don't need to update its RPMs anymore.

ci: don't update RPMs for Kata image

---

.github/workflows/e2e.yml
.github/workflows/e2e_aks_runtime.yml
e2e/aks-runtime/aks_runtime_test.go
e2e/internal/contrasttest/contrasttest.go
packages/scripts.nix

Currently, downloading logs from an e2e cluster may fail since the cluster may be undeployed before the download is initiated. This PR fixes that problem by undeploying the cluster _after_ the logs were downloaded.

e2e: fix log collection download

---

.github/workflows/e2e_peerpods.yml

Directory paths in the `pull_request` trigger need to include wildcards, otherwise actions will look for a file of that name and never match.
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#patterns-to-match-file-paths

ci: correctly trigger peerpods e2e on image changes

---

e2e/regression/testdata/nginx.yml
packages/by-name/kata/kata-runtime/0019-genpolicy-allow-non-watchable-ConfigMaps.patch
packages/by-name/kata/kata-runtime/package.nix

Small ConfigMaps are mounted watchable, but large ones are not. We do not really care enough about the exact mount source, since it's provided by the host anyway, so we allow mounting from watchable and non-watchable spaces.

kata: support large ConfigMaps

---

nodeinstaller/internal/config/kata_runtime.go
nodeinstaller/internal/config/kata_runtime_test.go
nodeinstaller/node-installer.go

This is a cherry-pick from #1043. We don't have that particular bug in the other configs, but better to have the test than not.

node-installer: add test for kata config

---

.github/workflows/release.yml
docs/docs/examples/mysql.md
docs/sidebars.js
internal/kuberesource/parts.go
internal/kuberesource/resourcegen/main.go
internal/kuberesource/sets.go
justfile

This adds a demo application running a MySQL server with an encrypted volume mount, similar to the `volume-tester`. For this, the `cryptsetup` init container uses the workload secret to set up a LUKS partition that is mounted to `/var/lib/mysql`. The demo is also provided as a release artifact as `mysql-demo.yml`.

docs: add demo for workload secrets

---

.github/workflows/release.yml

There is some bug in v2.2.0, see https://github.com/softprops/action-gh-release/issues/555
Reverting the bump from https://github.com/edgelesssys/contrast/commit/d19413cd18aba8dac6a1b5dbad19c04d0975d513#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L334

deps: downgrade softprops/action-gh-release to v2.1.0

---

coordinator/internal/authority/credentials.go

This PR updates the fixed expiration timespan of the kds-cache inside of the coordinator to 9 months, which allows to keep Contrast's attestation running even if the KDS server is unavailable at the moment. The expected cache size will be 40 MB,  estimated for a upper bound of 5000 nodes in the deployment.

kds-cache: adjust cache expiration time to 9 months

---

e2e/volumestatefulset/volumestatefulset_test.go
justfile

In https://github.com/edgelesssys/contrast/pull/1045 we changed where we mount the stateful volume from `/srv/state` to `/state`. Adjust the path where we create the test file accordingly. Since we don't ship any deployment that sets up this path anywhere, expect for the newly written example, there are no customers that can depend on it, apart from us. Generally, while our deployment is only an example, we should try to keep the path stable.
Additionally, remove the unused `--skip-undeploy` flag from the e2e target in the justfile in order for the target to work again.
To test: `just e2e volumestatefulset`

e2e/vmss: align test path with volume path 

---

internal/kuberesource/sets.go

Backport of #1081 to `release/v1.2`.
---

[release/v1.2] kuberesource: pin container images for emojivoto/mysql demo by hash

---

packages/by-name/qemu-static/0003-guest_memfd-Introduce-an-object-to-manage-the-guest-.patch
packages/by-name/qemu-static/0004-guest_memfd-Introduce-a-helper-to-notify-the-shared-.patch
packages/by-name/qemu-static/0005-KVM-Notify-the-state-change-via-RamDiscardManager-he.patch
packages/by-name/qemu-static/0006-memory-Register-the-RamDiscardManager-instance-upon-.patch
packages/by-name/qemu-static/0007-guest-memfd-Default-to-discarded-private-in-guest_me.patch
packages/by-name/qemu-static/0008-RAMBlock-make-guest_memfd-require-coordinate-discard.patch
packages/by-name/qemu-static/0009-increase-min-granularity-for-memfd.patch
packages/by-name/qemu-static/package.nix

Upstream QEMU can't launch SNP VMs with VFIO devices. Apply the patches from this patch series: https://patchwork.kernel.org/project/kvm/cover/20240725072118.358923-1-chenyi.qiang@intel.com/. We also need another patch to support large devices (such as GPUs).
Note that I didn't yet test GPU support with the binary built by qemu-static, but I did test the patches on a separate non-nix QEMU build. We might need additional changes to make GPU support work for Contrast.

qemu-static: add patches for VFIO support on SNP

---

packages/nixos/kata.nix

Previously, we only wrote Kata agent output to the console / TTY (which is also what it does upstream [^1]). This makes the output appear in the Kata runtime logs on the Host via the `vmconsole=` field. However, when debugging from within the pod VM, it's helpful to also have the logs in there so that they can be searched in with `journalctl`. This makes it so the output of the agent is written to both the console _and_ the journal.
[^1]: https://github.com/kata-containers/kata-containers/blob/3.10.1/src/agent/kata-agent.service.in

packages/nixos: write Kata agent output to console and journal

---

packages/by-name/kata/kata-runtime/0020-genpolicy-support-guest-hooks.patch
packages/by-name/kata/kata-runtime/package.nix

This adds a patch that integrates support for setting guest hooks to genpolicy, which is a prerequisite for GPU containers, which require guest hooks.

packages/kata-runtime: add guest hook support to genpolicy

---

internal/manifest/manifest.go

Our reference values of SNP attestation have a hard dependency on the productLine used during attestation. This includes the derivation of trustedRoots, as well as the trustedMeasurements.  By design, we start a validator configured with specific verifyOpts for each reference value. 
This led to the error "VCEK could not be verified by any trusted roots", because validators configured with the wrong productLine tried to fulfill the attestation verification. Therefore this PR adds the explicit setting of the productLine in verifyOpts, to reflect the dependency of our reference values on the productLine. As expected we then run into the error below prior to validation, which reveals that a validator is configured for the wrong productLine:
`time=2024-12-18T10:46:20.815Z level=ERROR …

attestation.snp: reflect dependency of validators on productLine in verify.Options

---

internal/manifest/manifest.go

Backport of #1082 to `release/v1.2`.
---
Our reference values of SNP attestation have a hard dependency on the productLine used during attestation. This includes the derivation of trustedRoots, as well as the trustedMeasurements.  By design, we start a validator configured with specific verifyOpts for each reference value. 
This led to the error "VCEK could not be verified by any trusted roots", because validators configured with the wrong productLine tried to fulfill the attestation verification. Therefore this PR adds the explicit setting of the productLine in verifyOpts, to reflect the dependency of our reference values on the productLine. As expected we then run into the error below prior to validation, which reveals that a validator is configured for the wrong …

[release/v1.2] attestation.snp: reflect dependency of validators on productLine in verify.Options

---

packages/nixos/image.nix

to make image builds reproducible between systems with nix store optimization enables/disabled.

nixos/image: use erofs-utils' --hard-dereference flag

---

packages/by-name/kata/kata-kernel-uvm/package.nix

This adds a kernel build with GPU support to the `kata.kata-kernel` package.

packages/kata-kernel: add GPU variant

---

e2e/internal/kubeclient/deploy.go
e2e/internal/kubeclient/kubeclient.go

The DynamicClient created from the embedded RESTClient was lacking an encoder which resulted in 
```
encoding is not allowed for this codec: *versioning.codec
```
errors during test cleanup. Afaict this is a breaking change with `client-go@v0.32.0`, introduced by https://github.com/kubernetes/kubernetes/pull/124059 (the constructor from config uses `UnversionedRESTClientForConfigAndClient`, which the embedded RESTClient does not, apparently).

e2e: create DynamicClient directly

---

e2e/internal/kubeclient/deploy.go
e2e/internal/kubeclient/kubeclient.go

Backport of #1100 to `release/v1.2`.
---
The DynamicClient created from the embedded RESTClient was lacking an encoder which resulted in 
```
encoding is not allowed for this codec: *versioning.codec
```
errors during test cleanup. Afaict this is a breaking change with `client-go@v0.32.0`, introduced by https://github.com/kubernetes/kubernetes/pull/124059 (the constructor from config uses `UnversionedRESTClientForConfigAndClient`, which the embedded RESTClient does not, apparently).

[release/v1.2] e2e: create DynamicClient directly

---

.github/workflows/release.yml
packages/scripts.nix

While we introduced a new platform with the last release, we missed to publish the runtime.yml for those platforms.

release: publish runtime.yml for metal platforms

---

packages/contrast-releases.json
packages/contrast-releases.nix
packages/update-contrast-releases.sh

We now have both demos in deployment, we'll have to see if that fits our needs.

contrast-releases: add mysql demo and runtime.yml for metal platforms

---

.github/workflows/release.yml
packages/scripts.nix

Backport of #1107 to `release/v1.2`.
---
While we introduced a new platform with the last release, we missed to publish the runtime.yml for those platforms.

[release/v1.2] release: publish runtime.yml for metal platforms

---

packages/contrast-releases.json
packages/contrast-releases.nix
packages/update-contrast-releases.sh

Backport of #1110 to `release/v1.2`.
---
We now have both demos in deployment, we'll have to see if that fits our needs.

[release/v1.2] contrast-releases: add mysql demo and runtime.yml for metal platforms

---

flake.nix
justfile
packages/contrast-releases.nix

Fix in https://github.com/edgelesssys/contrast/commit/61b5f35286fbb679d4abe29510b718b12389ccb9 was broken.
Also the shell wasn't working anymore as intended, as runtime/coordinator weren't installed anymore.

contrast-releases: fix runtime.yml conditional and demo shell

---

coordinator/internal/authority/credentials.go
internal/atls/atls.go
internal/attestation/snp/validator.go
internal/attestation/tdx/validator.go
sdk/common.go

This PR is a follow-up on #1027 and aims to enhance the logging of the different validation processes on the coordinator to reach better readability of the logs. 
-  Name was introduced as unique identifier in Validator struct and mapping to manifest.json, following the naming convention:
`<attestation>-<reference-values-index>[-<product>]`
The index corresponds to the position of the reference value separated by attestation type in manifest.json.
-  It was ensured that if all validators fail, the joined error message is printed and the formatting was reworked for readability. 
-  Single validation failures are printed on DEBUG only instead of ERROR level using the validator name and nonce.

attestation: add name to Validator as unique identifier

---

e2e/internal/contrasttest/contrasttest.go
e2e/workloadsecret/workloadsecret_test.go

This PR introduces the patchManifest() method in contrasttest.go to allow executing PatchManifestFunc on the current manifest, which obtain different modifications. 
- type PatchManifestFunc was introduced to allow using modification functions on the current manifest.
- existing patchReferenceValues (implements patchManifestFunc) was reduced to the modifcations of the reference values.
- patchWorkloadSecretID (implements patchManifestFunc)  was added to allow overwriting a certain workload secret.
- a workload secret test case was added, to check that setting the same WorkloadSecretID in two different deployments will result in the identical contrast-secrets.

e2e: allow usage of different PatchManifestFunc + add test for equal WorkloadSecretID 

---

.github/workflows/release.yml

Some workflows are executed from main branch, which makes the workflow difficult to test. This PR adds the ability to set the ref explicitly so it can be pointed to the same branch when testing the workflow.

ci/release: allow setting main ref for testing

---

.github/workflows/e2e_manual.yml
.github/workflows/release.yml
cli/genpolicy/config.go
cli/main.go
e2e/internal/contrasttest/contrasttest.go
internal/kuberesource/parts.go
internal/manifest/referencevalues.go
internal/platforms/platforms.go
justfile
nodeinstaller/internal/config/kata_runtime_test.go
nodeinstaller/internal/constants/constants.go
nodeinstaller/node-installer.go
nodeinstaller/node-installer_test.go
nodeinstaller/testdata/expected-bare-metal-qemu-snp-gpu.toml
packages/by-name/contrast/package.nix
packages/contrast-releases.nix
packages/scripts.nix
packages/update-contrast-releases.sh

This adds a new `K3s-QEMU-SNP-GPU` platform that can be used for testing GPU-specific features on our on-prem infrastructure that uses this setup. This intentionally does not yet add any specific actions done if that platform is selected.

Add {Metal,K3s}-QEMU-SNP-GPU platforms

---

.github/workflows/release.yml

Backport of #1118 to `release/v1.2`.
---
Some workflows are executed from main branch, which makes the workflow difficult to test. This PR adds the ability to set the ref explicitly so it can be pointed to the same branch when testing the workflow.

[release/v1.2] ci/release: allow setting main ref for testing

---

.gitignore
justfile

This allows fast testing of custom resource yaml. 
Namespace of resources in .custom should be `custom-<namespace-suffix>`. (Or hack the just.namespace manually, if required for testing.)
Currently tested to work with `just default custom`.

just: enable deploying custom resources

---

cli/cmd/generate.go

The same variable is only used in https://github.com/edgelesssys/contrast/blob/main/internal/kuberesource/mutators.go#L36 and not referenced here.

cli: remove unused skip initializer variable

---

internal/kuberesource/parts.go
packages/containers.nix
service-mesh/main.go

This allows configuring the envoy invoked by the service mesh with additional options like for setting the log level.

service-mesh: pass args to envoy, set log level to debug

---

packages/nixos/gpu.nix

This reduces the size of the GPU-enabled image to 2.2G, from over 3G previously. It does so by de-duplicating NVIDIA drivers and disabling unnecessary NVIDIA tools like `nvidia-settings`.

nixos: minimize GPU image

---

cli/cmd/generate.go

This allows to keep existing service mesh parts including modifications.

generate: add flag to skip service mesh injection

---

internal/kuberesource/parts.go
packages/containers.nix
service-mesh/main.go

Backport of #1124 to `release/v1.2`.
---
This allows configuring the envoy invoked by the service mesh with additional options like for setting the log level.

[release/v1.2] service-mesh: pass args to envoy, set log level to debug

---

cli/cmd/policies.go
cli/cmd/policies_test.go
internal/kubeapi/kubeapi.go
internal/kubeapi/kubeapi_test.go

Backport of https://github.com/edgelesssys/contrast/pull/1127 to `release/v1.2`.
---
Contrast configures the manifest with a default `WorkloadSecretID` per k8s object. The current default is simply the object name, which can be problematic if multiple objects (e.g. different kinds) share a name.
Combining the default workload secret ID from group, version, kind, namespace and name should ensure different k8s objects get different workload secrets.

[release/v1.2] cli: make default WorkloadSecretIDs unique per k8s object

---

rfc/008-platform-support.md
tools/vale/styles/config/vocabularies/edgeless/accept.txt

This adds an RFC for platform support and representation in Contrast. This is in very much of a bare-bones stage now, so reviews and critique are welcome.

rfc: add platform support RFC

---

e2e/internal/contrasttest/contrasttest.go

Until now we are using the generated reference values in our e2e tests on bare metal, which contain placeholder null values. This PR ensures, that the reference values of our e2e test correctly reflect the bare-metal runners (tdx & snp).
- A ConfigMap, persistently storing the missing reference values of our bare-metal runners was added to our e2e cluster. Thus reachable by any workflow ran on the e2e cluster.
- Reworked e2e testing logic of patchReferenceValues() as stated in [#1104](https://github.com/edgelesssys/contrast/pull/1104#discussion_r1900627363) by moving the invalidation of reference values into an own function

e2e: use real reference values on bare-metal runners

---

packages/by-name/microsoft/genpolicy/0010-genpolicy-support-mount-propagation-and-ro-mounts.patch
packages/by-name/microsoft/genpolicy/package.nix

This PR adds a patch to support volume mounting for the genpolicy binary of the microsoft fork, which is necessary for volumestatefulset and mysql deployments. Updating the release of the microsoft fork in https://github.com/edgelesssys/contrast/commit/a3496ccfaac275f8272fa91fd8b8303081b6bc39 resulted in introducing the required change.

microsoft.genpolicy: support volume mounting

---

internal/kuberesource/parts.go
internal/kuberesource/wrappers.go
packages/containers.nix
service-mesh/main.go

The startup probe for the mesh proxy is redirected onto the same port, causing Envoy to open connections to itself recursively. Unfortunately, this is not visible in the Envoy logs - I only discovered this condition while working on a custom proxy implementation.
Things that are still unclear:
* There is some race condition that causes the redirection loop to only occur ~50% of the time.
* Switching on debug logging makes this condition much rarer.
* Exempting the TPROXY ports with iptables should make the SO_ORIGINAL_DST lookup fail, but the loop happens nonetheless.
* The issue reproduces with opening and holding a single connection, while opening another, but not with just one connection.
Tests:

service-mesh: test readiness with exec probe

---

.github/workflows/e2e.yml
.github/workflows/e2e_aks_runtime.yml
.github/workflows/release.yml
internal/kuberesource/sets.go
justfile
packages/containers.nix

Until now, we used a specific cryptsetup image, containing a couple of filesystem and mount tools that facilitate the LUKS encryption. 
This PR is a first step to include the dependencies of the cryptsetup image in the initializer, while still keeping the bash entry point for now to allow setting up the LUKS device by the initializer. Thus all existing references to the specific cryptsetup image are dropped as part of this PR.
As a follow up the mounting/set up of the encrypted volume done by the bash entrypoint will be moved to a subcommand of the initializer binary. 
K3s-QEMU-TDX: https://github.com/edgelesssys/contrast/actions/runs/12748493847
K3s-QEMU-SNP: https://github.com/edgelesssys/contrast/actions/runs/12748490036
AKS-CLH-SNP: …

initializer: move cryptsetup image into initializer

---

e2e/release/release_test.go

Releases were failing due to the short timeout: https://github.com/edgelesssys/contrast/actions/runs/12784167814/job/35640395847#step:9:38

e2e/release: increase timeout for generate

---

dev-docs/coco/tracing.md

This adds a dev-doc roughly explaining the steps one needs to take to trace the Kata runtime.

dev-docs: add tracing doc

---

.github/workflows/release.yml
e2e/internal/contrasttest/contrasttest.go
e2e/release/release_test.go
internal/kuberesource/mutators.go
internal/kuberesource/mutators_test.go
internal/kuberesource/parts.go
internal/kuberesource/parts_test.go
internal/kuberesource/resourcegen/main.go
internal/kuberesource/sets.go
internal/kuberesource/wrappers.go

The Contrast runtime used to have a static name, and only one runtime could be installed into the `kube-system` namespace. We're changing the naming scheme in this PR: resources of the Contrast runtime (the node installer and its RBAC config) are now named like the runtime handler, which allows installing more than one version.
**User-visible consequence**: the runtime `DaemonSet` is not called `contrast-node-installer` anymore, but something like `contrast-cc-aks-clh-snp-c52b1454`.

runtime: allow installation of multiple Contrast runtimes side-by-side

---

.github/workflows/e2e.yml
.github/workflows/e2e_aks_runtime.yml
.github/workflows/release.yml
internal/kuberesource/sets.go
justfile
packages/containers.nix

This PR introduces the two commits of #1132 again, which have been reverted due to the release problems in #1150 .
Until now, we used a specific cryptsetup image, containing a couple of filesystem and mount tools that facilitate the LUKS encryption. 
This PR is a first step to include the dependencies of the cryptsetup image in the initializer, while still keeping the bash entry point for now to allow setting up the LUKS device by the initializer. Thus all existing references to the specific cryptsetup image are dropped as part of this PR.
As a follow up the mounting/set up of the encrypted volume done by the bash entrypoint will be moved to a subcommand of the initializer binary. 
K3s-QEMU-TDX: https://github.com/edgelesssys/contrast/actions/runs/12748493847
K3s-QEMU-SNP: …

 initializer: move cryptsetup image into initializer

---

initializer/main.go

As part of #1153, we would like to have the possibility to add subcommands to the initializer binary. Therefore this PR integrates the [Cobra library](https://github.com/spf13/cobra) to the initializer, facilitating the creation of subcommands in the initializer in the future.
There is no behavioral change of the initializer and the command to start the initializer is kept equal.

initializer: add Cobra for subcommands

---

internal/kuberesource/sets.go

This makes it so that the images in the Emojivoto deployment are taken from the edgelesssys org, not an individual developer's one. Images are already migrated and published.

kuberesource: serve images from edgelesssys org

---

packages/by-name/microsoft/kata-image/package.nix

This fixes a reproducibility issue in the VM image for AKS, where an non-needed RPM sqlite file would be included in the image.
e2e reproducibility: :green_circle: https://github.com/edgelesssys/contrast/actions/runs/12884449490

microsoft.kata-image: refactor, fix reproducibility issue

---

docs/docs/getting-started/cluster-setup.md
packages/create-coco-aks.sh

Azure's az cli recommends to do so:
```
The new node pool will enable SSH access, recommended to use '--ssh-access disabled' option to disable SSH access for the node pool to make it more secure.
```
Therefore we integrate this step in our setup guide. SSH access to the node does not undermine Confidential Computing security in any way.

docs: disable SSH access to AKS nodes

---

internal/kuberesource/parts.go

Similarly to #1161 , this PR serves as a preliminary step toward moving cryptsetup to a subcommand of the initializer binary. Before translating the Bash entrypoint (used in the initializer binary after merging #1161) into Go code, the script was reworked to allow a cleaner integration of the volume encryption.
There were a few peculiarities in the cryptsetup LUKS standardization that have not been fully addressed in the current version of the entrypoint:
-  **key** is equivalent to **passphrase** (see the LUKS EXTENSION section in the [cryptsetup manual](https://man7.org/linux/man-pages/man8/cryptsetup.8.html)).
-  When using the `--key-file` flag with cryptsetup, the file's contents are unexpectedly treated as a passphrase rather than a cryptographic key.  
- Using the keyfile as …

initializer/cryptsetup: rework bash entrypoint

---

.github/workflows/e2e.yml
.github/workflows/e2e_aks_runtime.yml
packages/scripts.nix

This fixes [this error](https://github.com/edgelesssys/contrast/actions/runs/12703367171/job/35411042848#step:12:131). The error occurred because data was streamed into the export directory while it was made ready for download. The fix just copies the `export` directory to `export-no-stream`, which is then downloaded instead. This ensures that streaming is never interrupted and logs are never missed.

e2e: prevent download of streamed log directory

---

internal/kuberesource/parts.go
internal/kuberesource/sets.go

Using the wrapper removes the empty namespace from the volume claim templates in our stateful sets. This is only an aesthetic fix, the explicit empty namespace also does the right thing.

kuberesource: use only PVC wrapper

---

.github/workflows/e2e_manual.yml
.github/workflows/e2e_nightly.yml
e2e/gpu/gpu_test.go
e2e/gpu/testdata/gpu-pod.yaml
e2e/internal/contrasttest/contrasttest.go
packages/by-name/contrast/package.nix
packages/by-name/kata/snp-launch-digest/package.nix

This adds an E2E test for GPU use on Contrast.
It currently runs on the GPU-enabled bare-metal SNP runner.
The test currently only verifies that the GPU is available via
nvidia-smi, which also verifies that driver and CUDA work correctly.

e2e: add GPU test

---

.github/workflows/e2e_manual.yml
.github/workflows/e2e_nightly.yml
.github/workflows/release.yml
e2e/gpu/gpu_test.go
e2e/gpu/testdata/gpu-pod.yaml
e2e/internal/contrasttest/contrasttest.go
internal/kuberesource/parts.go
justfile
nodeinstaller/internal/constants/constants.go
overlays/nixpkgs.nix
packages/by-name/contrast/package.nix
packages/by-name/kata/contrast-node-installer-image/package.nix
packages/by-name/kata/kata-runtime/0019-agent-remove-CDI-support.patch
packages/by-name/kata/kata-runtime/package.nix
packages/by-name/kata/snp-launch-digest/package.nix
packages/containers.nix
packages/nixos/gpu.nix
packages/nixos/kata.nix

This adds support for running bare-metal Kata containers with GPUs on Contrast.
Please refer to the commit messages for reasoning about the individual code changes.
Requires a nixpkgs containing https://github.com/NixOS/nixpkgs/pull/372320.
An E2E test based on this will follow.

Support bare-metal Kata GPU containers

---

go.mod
go.sum
packages/by-name/contrast/package.nix

We replaced the version with our fork which was 6 months old. ~The issues mentioned have been resolved.~ While the GitHub issues have been resolved, the issue itself still persists. Therefore I've updated the fork.

deps: remove go-sev-guest replace

---

.github/workflows/cleanup-azure-ci-resources.yml
packages/by-name/azure-ci-rg-cleanup/cleanup.sh
packages/by-name/azure-ci-rg-cleanup/package.nix

run: https://github.com/edgelesssys/contrast/actions/runs/12926242566/job/36048840852

ci: cleanup azure ci resources 

---

internal/kuberesource/mutators.go
internal/kuberesource/mutators_test.go
internal/kuberesource/sets.go

The Contrast CLI injects a `volumeMount` for Contrast secrets (TLS certificates and workload secrets) into application containers. This was used to be done for regular containers only, not for initcontainers. 
However, many use cases for initcontainers involve the Contrast secrets - our own demos are a good example. Therefore, we add support for injecting the mount into initcontainers.

cli: inject contrast-secrets mount into initcontainers

---

docs/docs/basics/features.md
docs/docs/deployment.md
docs/docs/features-limitations.md
docs/docs/getting-started/bare-metal.md
tools/vale/styles/config/vocabularies/edgeless/accept.txt

This adds documentation on setting up a bare-metal Contrast cluster for use with GPUs, how to deploy the GPU-enabled runtime class, and how to modify pod specs to use GPU devices.

docs: add docs on GPU support

---

nodeinstaller/node-installer.go

This should fix the nightly test failures that fail waiting for the coordinator to come up, explained in detail in the code comments.

nodeinstaller: compare with the template file content

---

.github/workflows/e2e_runtime-reproducibility.yml

This should have used `github.ref_name == 'main'` instead of `github.ref`, which is `refs/heads/main` on main.
But even better, we can check for the `event_name` to be `schedule`, so we can also filter out `workflow_dispatch` events on main.

e2e/runtime-reproducibility: fix teams notifications

---

docs/docs/architecture/secrets.md
initializer/main.go
initializer/mount.go
internal/kuberesource/parts.go
internal/kuberesource/sets.go
packages/containers.nix

This PR translates the bash entrypoint currently used for setting up an encrypted volume with cryptsetup to a  `cryptsetup` subcommand in the initializer binary, which takes the device path and the required mount point as flags. 
- adds wrapper functions of the following commands of the cryptsetup executable: cryptsetup open, isLuks, luksFormat
-  setupEncryptedMount function reimplements the current bash entrypoint of #1140 as a go function
-  introduces new `cryptsetup`  Cobra subcommand to the initializer command, wrapping the setupEncryptedMount function -- follow-up on #1157 
-  const workloadSecretPath is shared between initializer main.go and mount.go
The shared code of mounting mechanisms between the coordinator and initializer was moved to internal/mount in #1163 .
e2e …

initializer: add cryptsetup subcommand

---

internal/kuberesource/mutators.go
internal/kuberesource/parts.go
internal/kuberesource/parts_test.go
internal/kuberesource/wrappers.go

* Remove the unused port-forwarder for a single port.
* Patch out the namespace if empty. This is mostly to align with the other namespaced wrappers.
* Restrict to TCP ports when forwarding k8s services. The current socat script can't deal with UDP.
* Handle SIGTERM by forwarding to the background children. This speeds up pod termination because we don't need to wait for the SIGKILL anymore.

kuberesource: some improvements around the port-forwarder resource

---

docs/docs/architecture/security-considerations.md
packages/by-name/kata/kata-runtime/0021-agent-clear-log-pipes-if-denied-by-policy.patch
packages/by-name/kata/kata-runtime/package.nix
packages/by-name/microsoft/kata-runtime/0001-agent-clear-log-pipes-if-denied-by-policy.patch
packages/by-name/microsoft/kata-runtime/package.nix

Access to logs can now be blocked by policy with an adjustment to the settings, see https://docs.edgeless.systems/contrast/architecture/security-considerations#logs.
Logs access is still allowed by default.

kata: enable blocking logs access

---

nodeinstaller/node-installer.go

Commit ff6bfe1 introduced an `os.ReadFile` operation for the containerd config template used by k3s, assuming that the template file would always be present. However, a fresh installation of k3s does not come with a template file:
https://docs.k3s.io/advanced#configuring-containerd.
On a fresh k3s installation, the nodeinstaller will not find the template file, (falsely) assume that there is no config and use an embedded default, which happens to be incompatible with k3s.
Going forward, the nodeinstaller will treat an absent template like an empty template.

nodeinstaller: ignore absence of containerd config template

---

packages/containers.nix

As part of  the [cryptsetup rework](
https://github.com/edgelesssys/contrast/pull/1153/files#diff-62e112e08a129f6cf9872c0f537ccf21f9b08e22cf3ee16946c0997ea7aca0a4), the initializer image was extended to run the `mkdir -p /run` command, because it is required by cryptsetup. The code change made the initializer boot qemu vm to emulate the architecture after runAsRoot command. This is not intended for the minor needs of having an existing /run directory, therefore the PR reverts the runAsRoot command and just mounts an empty volume at /run.

fix: add '/run' volume to initializer

---

nodeinstaller/node-installer.go

Backport of #1206 to `release/v1.4`.
---
Commit ff6bfe1 introduced an `os.ReadFile` operation for the containerd config template used by k3s, assuming that the template file would always be present. However, a fresh installation of k3s does not come with a template file:
https://docs.k3s.io/advanced#configuring-containerd.
On a fresh k3s installation, the nodeinstaller will not find the template file, (falsely) assume that there is no config and use an embedded default, which happens to be incompatible with k3s.
Going forward, the nodeinstaller will treat an absent template like an empty template.

[release/v1.4] nodeinstaller: ignore absence of containerd config template

---

coordinator/history/history.go
docs/docs/architecture/secrets.md

These were introduced in the private commits for https://github.com/edgelesssys/contrast/security/advisories/GHSA-vqv5-385r-2hf8 due to lack of CI coverage.

misc: fix linter errors

---

coordinator/main.go

The TERM and INT signal are usually masked for PID 1, which means that the Coordinator ignores these signals and the container runtime needs to send a KILL signal to terminate it. This results in 30 wasted seconds between the pod deletion request and the deletion itself, which is most annoying in interactive development workflows. Thus, we handle the signal by cancelling the main context, which in turn results in a graceful listener shutdown.

coordinator: handle signals

---

packages/containers.nix

Especially `util-linux` comes with a lot of baggage that we don't  need in the Coordinator image. What we actually depend on are `mount` and `blkid`.
The `blkid` from busybox produces output incompatible to util-linux, and harder to parse. Fortunately, there's a minimal version of util-linux that provides `blkid` and `mount`: `libuuid`.

containers: reduce image size of initializer and coordinator

---

justfile

Due to re-installation of K3s, the Kubeconfig got regenerated and thus needs an update here.

just: bump SNP Kubeconfig secret version

---

dev-docs/e2e/bare-metal-runner.md
dev-docs/e2e/tcb-specs.json
tools/vale/styles/config/vocabularies/edgeless/accept.txt

This PR adds some documentation on the ConfigMap used for the e2e clusters, as introduced in #1115. It describes how the ConfigMap can be created and updated in case of changes to the bare-metal runner specifications.

docs: bare-metal runner specs

---

e2e/internal/contrasttest/contrasttest.go

We saw an increased delay from scheduling the node installer to completion of the installation when using the GPU runtime. This is due to the larger VM image size, which increases the time it takes to download the container image and copy over the resources. Increasing the wait time should accommodate for this.

e2e: increase wait time for nodeinstaller

---

docs/docs/getting-started/bare-metal.md

Instead of recommending to use the NVIDIA Kata manager, which has proven to be very unstable in the past and comes with a lot of clutter on the node (e.g. the Kata pod-VM image), we now point at the NVIDIA Container Toolkit, which is the canonical tool by NVIDIA to generate CDI specifications.

docs: point to nvidia-ctk for CDI generation

---

coordinator/internal/authority/credentials.go
internal/attestation/snp/issuer/issuer.go
internal/attestation/snp/validator.go
internal/constants/constants.go
sdk/common.go

With this change, the aTLS issuer will send the VCEK and CRL in the aTLS handshake. This allows the Coordinator to cache VCEK/CRL and send them to the client. The client (CLI) doesn't need to request the KDS anymore, so operations against the Coordinator (set, verify) can also be done if the KDS is unreachable to the client, assuming the Coordinator managed to cache both at an earlier point in time. The client will verify the VCEK and CRL for valid signature by AMD ARK/ASK keys, so a malicious Coordinator sending manipulated VCEK/CRL will be detected.

atls: send VCEK and CRL

---

docs/docs/getting-started/bare-metal.md
packages/nixos/gpu.nix

This documents the requirement of CC-enabled GPUs in Contrast, which was
previously not mentioned in the docs at all.

docs: document incompatibility with non-CC GPUs

---

packages/by-name/kata/contrast-node-installer-image/package.nix
packages/by-name/microsoft/contrast-node-installer-image/package.nix

Our runtime handler suffix used to be derived from the guest VM image only, missing the following Contrast components that influence runtime behaviour or attestation:
* node installer
* Kata configuration files
* embedded coordinator policy
While this is not a security issue, it may cause problems when installing multiple Contrast versions side by side. For example, 1.4.0 and 1.4.1 have the same runtime handler name.
This PR resolves the issue at least for release versions, by mixing the version into the runtime handler suffix generation input. While we could also make the version itself part of the suffix, the runtime handler name is already long enough to bring the node installer name close to the limits for k8s objects.

runtime: derive handler from version

---

cli/cmd/generate.go
docs/docs/architecture/secrets.md

The CLI fails with a segmentation fault if a StatefulSet without annotations is among the pod resources. This PR adds a nil check for this situation.

cli: don't panic on absent pod spec annotations

---

cli/cmd/generate.go
cli/cmd/generate_test.go

This is an amendment to #1230. We now don't panic even if the entire pod template metadata is missing.

cli: don't panic on absent pod template metadata

---

e2e/internal/contrasttest/contrasttest.go
e2e/workloadsecret/workloadsecret_test.go

We've seen an increased amount of nightly failures for the workload secret test since #1104 introduced a new subtest. This PR aims to improve the situation by:
* using the test's timeout exclusively for the restart operation (the `ct.Set` command has its own timeout)
* restarting the pods in parallel and only waiting serially
While looking at the test, I saw that `FactorPlatformTimeout` has an explicit list of slow platforms. I think we should not silently default to the shorter timeout, because it's easy to forget to update this switch statement when a new platform is introduced.

e2e: improve workloadsecrettest timeout behavior

---

e2e/policy/policy_test.go

This is a follow-up fix for #1227, where I accidentally reused the `require` object in the closure instead of allocating a new one. That caused the test to only execute the `Eventually` block once.

e2e: use correct testing context in policy test

---

e2e/regression/testdata/apache-httpd-centos.yml
e2e/regression/testdata/apache-httpd-fedora.yml
e2e/regression/testdata/keycloak.yml
e2e/regression/testdata/mongodb.yml
e2e/regression/testdata/mysql-centos.yml
e2e/regression/testdata/mysql-fedora.yml
e2e/regression/testdata/nginx.yml
e2e/regression/testdata/prometheus.yml
e2e/regression/testdata/redis.yml
internal/kuberesource/parts.go
internal/kuberesource/sets.go
internal/platforms/platforms.go
nodeinstaller/internal/constants/configuration-clh-snp.toml
nodeinstaller/internal/constants/configuration-qemu-snp.toml
nodeinstaller/internal/constants/configuration-qemu-tdx.toml
nodeinstaller/internal/constants/constants.go
packages/by-name/qemu-tdx-static/0001-avoid-duplicate-definitions.patch
packages/by-name/qemu-tdx-static/0002-add-options-for-library-paths.patch
packages/by-name/qemu-tdx-static/0003-i386-omit-some-unneeded-ACPI-tables.patch
packages/by-name/qemu-tdx-static/0004-hw-x86-load-initrd-to-static-address.patch
packages/by-name/qemu-tdx-static/package.nix
tools/tdx-measure/rtmr/rtmr.go

This PR corrects the calculation of the `RuntimeClass` overhead.
First, a bit of background on Kubernetes resource accounting. The total memory footprint of a pod is the sum of the individual container requests/limits and the overhead from the PodSpec or the overhead from the RuntimeClass. This total is accounted towards the node memory commitment, so we should aim to get it right in order to avoid overcommitting and idle resources. 
Ignoring the pod memory requests for now, we have three sources that add to the total memory used by a pod:
* Size of the VM, which is the sum of
* the Kata runtime setting `default_memory`
* the individual container limits
* VM-related processes on the host (i.e. Kata shim, qemu/CLH)
This implies immediately that the **RuntimeClass overhead is the sum of …

nodeinstaller: align default_memory and overhead to actual usage

---

docs/docs/architecture/secrets.md
initializer/main.go
initializer/mount.go
internal/kuberesource/mutators.go
internal/kuberesource/mutators_test.go
internal/kuberesource/sets.go

This implements [RFC 009](https://github.com/edgelesssys/contrast/blob/main/rfc/009-secure-pv-injection.md) and automatically adds the necessary configuration to set up an encrypted mount using the `contrast.edgeless.systems/secure-pv` annotation, which translates to a configured Initializer on `contrast generate`.
A successful run for the `volumestatefulset` test can be found [here](https://github.com/edgelesssys/contrast/actions/runs/13265880625).

cli/generate: automatic cryptsetup configuration

---

internal/kuberesource/sets.go

This addresses e2e failures on main caused by limits too narrow. We should revise memory limit assignment based on the target platform in a follow-up PR.

kuberesource: increase memory limit for emojivoto with mesh

---

internal/attestation/snp/validator.go

Non v3 Reports don't have the eax bits set in the report. We already have the product in the attestation, just use that one.

attestation: get product from attestation instead of report

---

internal/attestation/snp/validator.go

Backport of #1238 to `release/v1.5`.
---
Non v3 Reports don't have the eax bits set in the report. We already have the product in the attestation, just use that one.

[release/v1.5] attestation: get product from attestation instead of report

---

internal/grpc/retry/retry.go
internal/grpc/retry/retry_test.go

Backport of #1239 to `release/v1.5`.
---
If the gRPC connection is terminated before the TLS handshake takes place, the ultimate cause reported by the gRPC library is EOF. In this situation, we should not abort the request, but retry.

[release/v1.5] grpc: retry connecting to coordinator on EOF

---

docs/docs/troubleshooting.md

The error messages will only be propagated as described here after #1244 is merged.

docs: troubleshooting CLI connection errors

---

internal/atls/atls.go
internal/atls/atls_test.go
internal/attestation/snp/validator.go
internal/attestation/tdx/validator.go
internal/grpc/atlscredentials/atlscredentials.go

Validators often need to request resources from the internet, for example CRLs. If these resources are unavailable, validation might time out on the TLS handshake level without much information about the root cause.
This commit allows the atls package to forward the context of the TLS handshake to the individual validators. Missing here and to be added in future commits:
- Creating a context with appropriate timeout in atlscredentials.
- Forwarding the context to the HTTPSGetters for SNP/TDX.

atls: forward context to validators

---

.github/workflows/e2e_nightly.yml

After the addition of hetzner-ax162-snp, we have a SNP runner which doesn't have a GPU. Therefore introduce a new tag (discovery is already tagged with "snp-gpu") and use it as requirement for the runner.

ci: require "snp-gpu" tag for SNP-GPU platform

---

docs/docs/getting-started/bare-metal.md

Let's always point to the latest version of Longhorn so the user always installs the latest version.

docs: point to latest longhorn docs

---

e2e/regression/testdata/ephemeral-volume.yml
packages/by-name/kata/kata-runtime/0022-genpolicy-support-ephemeral-volume-source.patch
packages/by-name/kata/kata-runtime/package.nix

The Kubernetes resource definitions were lacking support for [ephemeral volumes](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes). This PR backports an upstream fix that allows mounting temporary block devices from CSI and adds a regression test case.

genpolicy: support ephemeral volume source on bare metal

---

coordinator/history/aferostore.go
coordinator/history/history.go
coordinator/history/store.go

This adds the `Watch()` function to the `Store` interface of the Coordinator. This function returns a channel which receives updates to the store, and a cancel function which can be used to stop watching.
The `NewStore()` method is separated and brought to a new file, so it can be controlled via a `enterprise` build tag.

Expand coordinator store interface

---

coordinator/internal/authority/authority.go
coordinator/internal/authority/credentials.go
coordinator/internal/transitengineapi/crypto.go
coordinator/internal/transitengineapi/crypto_test.go
coordinator/internal/transitengineapi/transitengineapi.go
coordinator/internal/transitengineapi/transitengineapi_test.go

This PR adds basic http handling functionality for the encrypt and decrypt endpoints of the transit engine API, allowing the auto-unsealing process for user-managed Vaults. The PR introduces the following points:
- add GetState() of authority, to always ensure operating on current manifest
- underlying cryptographic functionality for AES-GCM 256
- http-handler functions for encrypt and decrypt endpoints
- message-level implementation of encryption/decryption request and response
- key derivation based on workloadSecretID specified as URL parameter
- support for associatedData request parameter of Vault
- authorize transit engine requests to name parameter with client cert policy hash
- implement Vault json error bodies

transitengineapi: add http handler enc/dec

---

coordinator/internal/authority/credentials.go
coordinator/internal/authority/userapi.go
internal/constants/constants.go
internal/grpc/atlscredentials/atlscredentials.go
internal/grpc/dialer/dialer.go

This is factored out from #1244. We want to explicitly configure timeouts on the server side that are smaller than on the client side, otherwise the client will only ever see a connection timeout, which can mean a lot of things. If the server times out, the client will now receive a TLS error 80, which can then be diagnosed with the documentation from #1245. 
Contrary to the documentation, I found that `MinConnectionTimeout` is rather a `ConnectionTimeout` that will be applied to the TCP+TLS connection.

atls: add handshake timeout to aTLS servers and clients

---

e2e/workloadsecret/workloadsecret_test.go

This test has been failing frequently on bare metal because the pod takes longer than a minute to start up, which is probably due to slow guest pulls. Increasing the bare timeout to a minute results in a 2 minute timeout after scaling.

e2e: increase timeout for scaling deployment in workloadsecrettest

---

nodeinstaller/internal/constants/constants.go
nodeinstaller/node-installer.go

Some config keys moved between versions 2 and 3, so we need to switch based on the version we find.
Tested on a new Hetzner SNP machine with
```console
k3s version v1.31.6+k3s1 (6ab750f9)
go version go1.22.12
```
Fixes #1264

nodeinstaller: support containerd config v3

---

coordinator/history/aferostore.go
coordinator/history/aferostore_test.go
coordinator/history/history.go
coordinator/history/store.go
coordinator/history/store_enterprise.go
coordinator/main.go
enterprise/coordinator/history/configmapstore.go
enterprise/coordinator/history/configmapstore_test.go
internal/kuberesource/mutators.go
internal/kuberesource/parts.go
internal/kuberesource/sets.go
internal/kuberesource/wrappers.go
packages/by-name/contrast/package.nix
packages/scripts.nix

This implements the Store interface using Kubernetes Config Maps in preparation for the distributed Coordinator. For now, this can be tested by manually setting the `enterprise` build tag during the build process.

enterprise: add config map backed history store

---

coordinator/main.go

Yesterday evening the coordinator crashed in Privatemode's production deployment. However, the only log we are seeing is `Error detected, shutting down`. This is because the errors collected with the errgroup are only returned by the call to `Wait()` and `run`'s error is never printed. This PR should fix that.
Please let me know if you think other places should be touched as well.
In case you want to dig through the OpenSearch logs:
- [this](https://search-e2e-logs-y46renozy42lcojbvrt3qq7csm.eu-central-1.es.amazonaws.com/_dashboards/app/discover/#/doc/308385c0-b09b-11ef-a730-7138182413c7/continuum-k8s-logs-2025.10?id=GjD1gJUBhc9VUFOP1lgJ) is the crashing log statement
- [this](https://search-e2e-logs-y46renozy42lcojbvrt3qq7csm.eu-central-1.es.amazonaws.com/_dashboards/goto/8a0b84baf06abeaf …

coordinator: print run error in main

---

docs/docs/getting-started/bare-metal.md

docs: remove mention of kernel 6.11 rcs

---

cli/cmd/recover.go
cli/cmd/set.go
coordinator/main.go
initializer/main.go
internal/atls/atls.go
internal/grpc/atlscredentials/atlscredentials.go
internal/grpc/dialer/dialer.go
sdk/verify.go

During debugging of the latest SNI issue I had to add more logging in my dev state. It would be best if customers could enable this without code changes to make debugging easier.

atls: improve logging

---

enterprise/coordinator/peerdiscovery/peerdiscovery.go
enterprise/coordinator/peerdiscovery/peerdiscovery_test.go
internal/kuberesource/parts.go

This PR adds the `peerdiscovery` enterprise package, which provides a `GetPeers` function, which returns a list of IPs of ready Coordinators to be used for peer recovery.

enterprise: add peer discovery package

---

coordinator/internal/meshapi/meshapi.go
coordinator/internal/meshapi/meshapi_test.go
coordinator/main.go
coordinator/meshapi.go

This is an alternative approach to #1272. Both in its current form as well as with the additions from RFC 010, the meshapi only depends on the state of the coordinator as per creation of the channel. We can thus decouple the authority struct and the meshapi server, the remaining interface being the state passed via context.
Before moving the service implementation into its own package, I consolidated the gRPC server creation, which was mostly duplicated code and used to expose the meshapi server to structs it should not concern itself with.
~I will port the test from #1272 in a separate PR.~

coordinator: move meshapi into its own package

---

coordinator/internal/authority/authority.go
coordinator/internal/authority/authority_test.go
coordinator/internal/authority/credentials.go
coordinator/internal/authority/userapi.go
coordinator/internal/meshapi/meshapi.go
coordinator/internal/meshapi/meshapi_test.go
coordinator/internal/transitengineapi/transitengineapi.go
coordinator/internal/transitengineapi/transitengineapi_test.go

Since we're using the `State` struct in other packages now, we should make sure that it is not accidentally modified by those packages. This commit is a first step in this direction, replacing direct field access with getters.
It's still possible to modify the manifest, though - I'm going to fix this in a future commit.

authority: add getters for State fields

---

e2e/regression/regression_test.go

e2e: include coordinator in regression test resources

---

coordinator/internal/authority/authority_test.go
coordinator/internal/authority/userapi_test.go

This is a follow-up on https://github.com/edgelesssys/contrast/pull/1291#discussion_r1995646165 - being able to run the tests without nix improves iteration velocity.

authority: allow testing without embedded reference values

---

coordinator/history/history.go
coordinator/history/history_test.go
coordinator/internal/authority/authority_test.go
coordinator/internal/authority/userapi_test.go

Propagate watcher events from the low-level store to the history, where they can be used by `authority.Authority` to enter recovery mode.

history: allow watching for LatestTransition changes

---

internal/attestation/snp/validator.go

I saw the `could not parse CRL` message in the logs while verifying the production Privatemode deployment, but without the cause attached it's hard to tell what's going wrong.

attestation: include reason for failed CRL parsing

---

e2e/policy/policy_test.go

We're already spending 20s idle [waiting for readiness checks](https://github.com/edgelesssys/contrast/blob/6d9e46eac8b6eddf4e14f1547bb40f915d757cf3/e2e/internal/kubeclient/deploy.go#L206), so the timeout is probably too aggressive.

e2e: increase timeout for rogue pod test

---

docs/docs/getting-started/bare-metal.md

The instructions pointed to a non-existent sysctl. While replacing it with the actual setting, I used the opportunity to also
* not strictly prescribe the file the setting needs to go into
* suggest that users should check whether their setting is too low, rather than telling them to blindly change the setting
* use systemd commands for applying changes
* tell users how to verify

docs: correct sysctl setting recommendation

---

e2e/internal/kubeclient/deploy.go

Moving away from the bespoke retry mechanism should allow us to see the actual cause of failed retries, instead of `context deadline exceeded`. See also #1244.

e2e: use retry package for kubeclient.WaitFor

---

internal/manifest/manifest.go

The manifest validation errors are joined by `errors.Join` to return all failures during validation, not just the first. The error is then printed in a tree-like structure by the new `validationError` error type.

manifest: join validation errors and return late

---

docs/docs/deployment.md
docs/docs/features-limitations.md
docs/docs/getting-started/bare-metal.md
docs/docs/howto/registry-authentication.md
docs/sidebars.js

Add some missing details with respect to load balancers and registry authentication.
I have some more content for the `How-To` section in mind:
* Exposing the Coordinator with Ingress/Gateway-API
* Working with genpolicy settings
* Determine correct reference values
* Manual recovery of persistence

docs: load balancer and registry authentication

---

cli/cmd/recover.go
cli/cmd/set.go
e2e/internal/contrasttest/contrasttest.go
e2e/internal/kubeclient/kubeclient.go
e2e/regression/regression_test.go
go.mod
go.sum
initializer/main.go
internal/grpc/dialer/dialer.go
packages/by-name/contrast/package.nix
sdk/verify.go

The grpc client wrapper `internal/grpc/dialer` takes a dialer that should be used to establish connections. This allows to inject a fake dialer for testing.
In the application code, we pass a `net.Dialer` instance. This overrides grpc's default dialer implementation, which supports HTTP CONNECT. To enable this feature, pass `nil` in the application code and then don't set a custom dialer for grpc.
I need some hints on how to test this. I thought about cloning one of the e2e tests and run some HTTP proxy in a goroutine.

grpc: use default dialer implementation that supports HTTP CONNECT

---

packages/by-name/kata/genpolicy/package.nix

With this, we should not need to manually disable all tests that are added upstream in the future.

kata: disable genpolicy integration tests

---

coordinator/internal/authority/authority.go
coordinator/internal/authority/userapi.go
coordinator/internal/meshapi/meshapi.go
coordinator/internal/meshapi/meshapi_test.go
coordinator/internal/seedengine/seedengine.go
coordinator/internal/transitengineapi/transitengineapi_test.go
internal/ca/ca.go
internal/meshapi/meshapi.pb.go
internal/meshapi/meshapi.proto
internal/meshapi/meshapi_grpc.pb.go

The recover handler verifies the peer Coordinator's policy and role and sends a `RecoverResponse` struct so the calling Coordinator can reconstruct its state.
The initial proto definition of the `RecoverResponse` defined in [RFC 10](https://github.com/edgelesssys/contrast/blob/main/rfc/010-distributed-coordinator.md#peer-recovery) is reduced to:
```proto
message RecoverResponse {
bytes Seed = 1;
bytes Salt = 2;
bytes MeshCAKey = 3;
bytes LatestManifest = 4;
}
```
The root CA key can already be derived by the seed and salt. The certificates can be generated afterward (this happens automatically when calling the constructor of the `CA` with given root CA and mesh CA keys).

meshapi: add recover handler

---

coordinator/internal/authority/authority_test.go
internal/manifest/manifest_test.go
internal/manifest/referencevalues.go

We currently only allow two static policies. This changes will detect modification of the guest policy in the manifest early to give the user a proper error.

manifest: validate guest policy

---

coordinator/internal/authority/authority.go
coordinator/internal/authority/authority_test.go
coordinator/internal/authority/userapi.go
coordinator/internal/authority/userapi_test.go
coordinator/internal/transitengineapi/transitengineapi_test.go
coordinator/main.go

The Coordinator has an internal in-memory state and an external state managed by a `Store` implementation. There's currently a two-way synchronization between the two:
* `SetManifest` requests result in store updates.
* Out-of-band store updates result in state refreshes (implemented in `syncState`).
The latter mechanism is not suitable for distributed Coordinators as specified in RFC010, because it derives new mesh certificates on persistency changes, although the Coordinator that wrote the update already derived its own mesh cert. Thus, we need to replace the store-to-state update happening in `syncState` with a peer recovery attempt. It's important to note that `syncState` was misguided to begin with, even for a single coordinator, because an out-of-band update could not really happen …

coordinator: add notion of staleness

---

internal/kuberesource/sets.go
justfile

I needed to bump the mem requests for mysql to be able to start it. Since the mysql deployment is not tested nightly, I think this broke when we introduced the various sidecars or adjusted our VM overhead we add.
I also bumped the emojivoto-sm-ingress (does both ingress and egress SM), which succeeded in the nightly, but failed when testing. This is because in the just target we add dmesg sidecar containers. If I remove them, I can deploy emojivoto with the memory numbers from the main branch.

resourcegen: bump mem requests

---

docs/docs/architecture/snp.md
docs/sidebars.js
docs/versioned_docs/version-1.7/architecture/snp.md
docs/versioned_sidebars/version-1.7-sidebars.json
tools/vale/styles/config/vocabularies/edgeless/accept.txt

I reviewed the docs page. Content LGTM, so I didn't make changes in that respect.
Apart from language improvements, notable changes are:
* Added one or two introductory sentences to some of the sections.
* Removed some fields from the attestation report table. Please let me know if you think these should stay.

docs: improve language of SNP attestation

---

.github/workflows/require_label.yml

Got tired of this one job always being shown as skipped instead of passing.

ci: make check green on prs without do-not-merge label

---

go.mod
go.sum
internal/kuberesource/parts.go
nodeinstaller/node-installer.go
packages/by-name/contrast/package.nix

Previously, we only parsed the containerd/k3s restart time with second precision, which lead to unnecessary restarts as we couldn't if the restart happened after or before the config mtime. With this change, we will use micro second precision.
However, there is a bug in the systemd version/build used by azurelinux on AKS, which won't include the micro seconds for unknown reason. So instead of invoking systemctl, we talk to dbus directly to get the raw start time.
However, while we already mount the host path under `/host` into the node-installer, and the dbus socket is under `/var/run/dbus` on the host, `/var/run` is usually a symlink to `/run`, and depending on the way distros create this symlink, it might point out of `/host` to the `/run` inside the container. This is the case on …

node-installer: fix timestamp precision in unit restart detection

---

coordinator/internal/probes/probes.go
coordinator/internal/probes/probes_test.go
coordinator/main.go
docs/docs/architecture/observability.md
e2e/internal/contrasttest/contrasttest.go
e2e/openssl/openssl_test.go
internal/kuberesource/mutators.go

This PR adds the probes specified in [RFC 10](https://github.com/edgelesssys/contrast/blob/main/rfc/010-distributed-coordinator.md).
It also removes the `CONTRAST_METRICS_PORT` environment variable. Instead, contrast prometheus metrics are activated by setting the `CONTRAST_METRICS` variable and are always served on port 9102. An http server on this port will now always be started to serve the probes, `CONTRAST_METRICS` only adds the prometheus service to this server.

coordinator: add startup, liveness and readiness probes

---

coordinator/internal/meshapi/meshapi.go
internal/attestation/extension/extension.go
internal/oid/oid.go

This PR adds an extension to the issued mesh certificates holding the workloadSecretID, if set in the manifest entry. Therefore allowing for faster authorization without any manifest look-ups.

meshapi: add workload secret as extension

---

go.mod
go.sum
internal/manifest/manifest.go
internal/manifest/referencevalues.go
packages/by-name/contrast/package.nix

This allows more fine grained control over the SNP reference values.

manifest: add and validate SNP PlatformInfo

---

coordinator/internal/transitengineapi/transitengineapi.go
coordinator/internal/transitengineapi/transitengineapi_test.go

This PR adds a json httpError struct to the transit engine API, to allow json error body responses and reuses it for error logging of the handler functions.
Further the test cases were reworked to construct the ciphertext, falling back to the plaintext, in case of an expected error for the encryption. This ensures that the input validation of the decryption endpoints is tested as well and does not fail because of missing ciphertext input.

transitengineapi: json error bodies and logging

---

coordinator/internal/transitengineapi/transitengineapi.go
internal/ca/ca.go

Adds the required auth logic to the transit engine API to accomplish the client authentication of the mTLS handshake. A client can be authenticated based on a valid mesh cert issued by the mesh CA of the current state.

transitengineapi: tls client cert auth

---

coordinator/internal/transitengineapi/transitengineapi.go
coordinator/internal/transitengineapi/transitengineapi_test.go

This PR introduces mTLS to the transit engine API to secure connections based on Contrast mesh certs.
- The client is only authorized to the transit key set of the workloadSecretID in the received meshCert extension. As prior we handle the <name> parameter of existing Vault implementations as our workloadSecretID.
- On initialization the transit engine API derives a private ecdsa key. For each incoming TLS connection of the transit engine API, the coordinator issues itself a fresh mesh cert for this private key of the transit engine API, which is therefore valid for the current state.
The logging mechanism introduced in #1345 and the new authorizationMiddleware is bypassed during testing using a mock transitengine API.

transitengineapi: mTLS with client authorization by workloadSecret 

---

docs/docs/components/runtime.md
nodeinstaller/node-installer.go

With this PR, the containerd config will be backed up before the node installer overwrites it to configure the new runtime. For an atomic update, the new config will be written to a temporary file first and then replace the old config.

nodeinstaller: backup existing containerd config

---

coordinator/internal/authority/authority.go
coordinator/internal/authority/authority_test.go

It turns out that #1317  introduced two race conditions in test code:
1. If the testclock was stepped before the watcher called `clock.After`, the notification about the step would go nowhere and the watcher would wait forever to restart the loop.
2. In `badStore.Watch` we sent a notification about the call happening before actually handing out the channel. This could lead to the caller receiving the new channel, not the one the test logic was closing.
I fixed both, restructured the test code so that the main test logic is easier to understand (by hiding the channel sends and receives in functions of store and clock), and switched from `clock.After` to `clock.NewTimer` because `clock.After` is still documented to leak resources (not sure whether this is still the case, though, as this was …

coordinator: fix race condition in authority test

---

.github/workflows/e2e_manual.yml

ci: use the right GPU runner for manual tests

---

.golangci.yml
enterprise/coordinator/peerdiscovery/peerdiscovery.go

Adding a rules section to the revive plugin disables all rules. Since we don't care about the default package-comment rule right now, I'm explicitly enabling all other recommended linters in this PR. Also includes a linter fix for #1361.

ci: fix enabled linters

---

coordinator/internal/transitengineapi/transitengineapi.go
coordinator/main.go

This PRs activates the transit engine API in a subroutine of the coordinator. For now the default port to expose the transit engine API will be 8200, following the standard of different Vault implementations.

transitengineapi: activate and expose in coordinator

---

cli/cmd/common.go
cli/cmd/recover.go
cli/cmd/set.go
sdk/common.go
sdk/verify.go

This allows reusing an existing cache, which will be used from the enterprise recovery code that verifies the peer coordinator. 
I'm leaving the `GetCoordinatorState` signature for now because we have a rework of the `CachedHTTPSGetter` scheduled, which would require changing the signature once more.

sdk: take cache as input for ValidatorsFromManifest

---

coordinator/history/history.go
coordinator/history/history_test.go
coordinator/internal/authority/authority.go
coordinator/internal/authority/userapi.go

I'd like to use this function from enterprise code to implement RFC010, so I moved it to the history package (where it arguably makes more sense, too) and added a test.

coordinator: move WalkTransitions function to history package

---

coordinator/main.go
initializer/main.go
internal/constants/constants.go
nodeinstaller/node-installer.go
packages/by-name/contrast-enterprise/package.nix
service-mesh/main.go

This will help to differentiate enterprise from non-enterprise components, identify the version of running containers as well as guide users to the right place to report issues.

treewide: print unified preface string on startup

---

.github/workflows/e2e_manual.yml
.github/workflows/e2e_nightly.yml
e2e/atls/atls_test.go
packages/by-name/contrast/package.nix

What we are trying to test:
* Do the grpc/net dailers correctly error when there is a attestation problem?
* Which mismatches in PlatformInfo return an error? One can argue that this is more of a test of the go-sev-guest library, but I think given the [recent changes](https://github.com/google/go-sev-guest/pull/161) it's also a nice place to test those
* Does the IDKeyDigest derivation/check fails if the policy or the measurement changes?
Alternative approach to also test the validator derivation from the manifest (i.e., call `sdk.ValidatorsFromManifest` in the test). In order to test the failure cases (i.e. modified MEASUREMENT), we need access to the underlying validateOpts in those `atls.Validators`, by:
* Casting the Validators form the Manifest back to `snp.Validator`.
* Exporting …

e2e: introduce snp atls test

---

e2e/gpu/gpu_test.go

`nvidia-smi` reports (some?) errors on stdout - for example, when the GPU is missing in the container it will print `No devices were found` on stdout.

e2e: print stdout on gpu test error

---

.github/workflows/update_ci_resources.yml

This adds a GitHub cronjob which periodically applies all YAML resources for the CI clusters from main. This currently includes the bare-metal cleanup cronjob and the tcb-specs config map.
[Successful run for TDX](https://github.com/edgelesssys/contrast/actions/runs/14335559151)

ci: periodically update kubernetes resources

---

packages/cleanup-bare-metal.sh

The cleanup script would error due to an incorrect path in the containerd config. It now tries both paths and continues in case one of them errors.

tools/bm-maintenance: support containerd config v3 in cleanup

---

dev-docs/e2e/bare-metal-runner.md
docs/docs/getting-started/bare-metal.md

Our instructions were lacking the Helm value that makes cc-manager set the GPU to confidential mode. These instructions were taken from [upstream documentation](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-operator-confidential-containers.html#procedure), which is either just wrong or assumes some other component activates CC mode.
---
The other commit includes some minor fixes I found useful while reconfiguring discovery:
* Add instructions for k3s config override. We had these files on some runners in the past, but it appears that they've been lost between reinstalls. The config I'm including here
* allow the `github` user (and others) to access `k3s.yaml` via `sudo` membership
* disable the default storage class, since we're installing longhorn
* increase the …

docs: configure GPU operator for CC mode

---

packages/scripts.nix

Test that failed during nightly: https://github.com/edgelesssys/contrast/actions/runs/14700370693/job/41248703755
Now fixed: https://github.com/edgelesssys/contrast/actions/runs/14704628754

e2e: skip log download if no namespace file exists

---

packages/by-name/image-podvm/package.nix
packages/scripts.nix
treefmt.nix

Sometimes, one toggles a debug arg and commits it by accident. This check should catch it and ensure debug is disabled by default.

treefmt: catch debug default true

---

e2e/workloadsecret/workloadsecret_test.go

We use this in the following steps to compare against, so continuing doesn't make sense if this step fails.
https://github.com/edgelesssys/contrast/actions/runs/14723444334/job/41321362053

e2e/workloadsecret: require first secret to be present

---

packages/scripts.nix

The codegen + apply on renovate bot failed due to the following error: https://github.com/edgelesssys/contrast/actions/runs/14726095314/job/41328978996?pr=1421
This occurs because the go version in the go.mod is bumped if a dependency requires a newer version. Since we try to `go generate` afterwards our code needs to build, which it only does if the go.work also requires this newer version. Therefore, we need to sync the version after each `go mod tidy`.

scripts.generate: sync go directive after each tidy

---

.github/workflows/e2e_aks_runtime.yml

The current aks runtime test fails with confcom 1.2.3 and aks-preview 14.0.0b6, but works with confcom 1.1.1 and aks-preview 14.0.0b6 For easier reproduction, we should print those versions after installing the latest one.

e2e/aks-runtime: print az extensions

---

e2e/aks-runtime/aks_runtime_test.go
e2e/internal/az/aks.go

Fix the e2e rutnime test by downgrading the `aks-preview` extension version. Additionally this PR improves logging if the azure CLI errors.

e2e: better logging in aks runtime test

---

packages/by-name/microsoft/genpolicy/0001-genpolicy-add-rules-and-types-for-volumeDevices.patch
packages/by-name/microsoft/genpolicy/0002-genpolicy-add-ability-to-filter-for-runtimeClassName.patch
packages/by-name/microsoft/genpolicy/0004-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
packages/by-name/microsoft/genpolicy/0005-genpolicy-propagate-mount_options-for-empty-dirs.patch
packages/by-name/microsoft/genpolicy/0006-genpolicy-support-HostToContainer-mount-propagation.patch
packages/by-name/microsoft/genpolicy/0007-genpolicy-support-for-VOLUME-definition-in-container.patch
packages/by-name/microsoft/genpolicy/0009-genpolicy-do-not-log-policy-annotation-in-debug.patch
packages/by-name/microsoft/genpolicy/genpolicy_msft_settings_coordinator.patch
packages/by-name/microsoft/genpolicy/genpolicy_msft_settings_dev.patch
packages/by-name/microsoft/genpolicy/package.nix
packages/by-name/microsoft/kata-image/package-index.json
packages/by-name/microsoft/kata-image/package.nix
packages/by-name/microsoft/kata-runtime/package.nix
packages/by-name/rpm-pin-vendor/package.nix

https://github.com/microsoft/kata-containers/releases/tag/3.2.0.azl3
https://github.com/microsoft/kata-containers/releases/tag/3.2.0.azl3.genpolicy0
https://github.com/microsoft/kata-containers/releases/tag/3.2.0.azl3.genpolicy1
https://github.com/microsoft/kata-containers/releases/tag/3.2.0.azl3.genpolicy2
https://github.com/microsoft/kata-containers/releases/tag/3.2.0.azl3.genpolicy3

microsoft.kata-runtime: 3.2.0.azl2 -> 3.2.0.azl3

---

dev-docs/security-overview.md

This adds a security overview of Contrast based on my understanding. It aims to give an overview of how Contrast is integrated into Kubernetes clusters. Please review it carefully, especially regarding:
- **Completeness**
- **Technical accuracy**

dev-docs: add security overview

---

packages/by-name/microsoft/genpolicy/0011-genpolicy-match-sandbox-name-by-regex.patch
packages/by-name/microsoft/genpolicy/0013-genpolicy-don-t-overwrite-env-vars-from-image.patch
packages/by-name/microsoft/genpolicy/package.nix

Addresses an issue with images that set HOSTNAME in their configuration, and an unrelated issue with `generateName` resources.
Fixed regression test: https://github.com/edgelesssys/contrast/actions/runs/14983444437

microsoft.genpolicy: fix regression in env var checks

---

.github/workflows/asciinema.yml
.github/workflows/bm_maintenance.yml
.github/workflows/cleanup.yml
.github/workflows/e2e.yml
.github/workflows/e2e_runtime-reproducibility.yml
.github/workflows/release.yml

CI runs failed for the AKS-CLH-SNP platform, throwing the following error:
```
Run just get-credentials
WARNING: The behavior of this command has been altered by the following extension: aks-preview
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Can't get attribute 'NormalizedResponse' on <module 'msal.throttled_http_client' from '/nix/store/y9dfql21dz1pdbih9rbj32ihakd3h5zm-python3.12-msal-1.32.0/lib/python3.12/site-packages/msal/throttled_http_client.py'>
Traceback (most recent call last):
File "/nix/store/m1laj52lgyi2nbsipvkxqjxbzf0gl[76](https://github.com/edgelesssys/contrast/actions/runs/15036728921/job/42259774549#step:8:77)4-python3.12-knack-0.12.0/lib/python3.12/site-packages/knack/cli.py", line 233, in invoke
cmd_result = …
```

ci: call nix develop as early as possible

---

packages/nixos/gpu.nix
packages/nixos/image.nix

The nvidia-persistenced build includes a man page that's not reproducible because of a dynamically rendered date. Fortunately, it can be overridden with the `DATE` env var.
* `DATE` overrides the `date` utility here: https://github.com/NVIDIA/nvidia-persistenced/blob/8c620178a92c835ab921811938bea8a4d41ba49e/utils.mk#L112,
* is then used to render a date string here: https://github.com/NVIDIA/nvidia-persistenced/blob/8c620178a92c835ab921811938bea8a4d41ba49e/Makefile#L178
* which is finally included in the man page here: https://github.com/NVIDIA/nvidia-persistenced/blob/8c620178a92c835ab921811938bea8a4d41ba49e/nvidia-persistenced.1.m4#L15
I first tried disabling the man pages altogether, but the persistenced package does not seem to respect that setting. Anyway, I decided to keep man pages …

nixos: exclude non-deterministic dates from NVIDIA man pages

---

dev-docs/e2e/tcb-specs.json
justfile

This updates the tcb spec for TDX after the firmware update on our TDX platform. The config map in the runners cluster is already updated. 
Also, remove constants in just for tcb override and instead use the values from the config map of the used cluster. Notice that it would be less correct to use the locally present tcb spec file, as that would require all devs to rebase when the spec changes, whereas using the config map allows fast switching and less noise.

dev-docs: update tcb specs for TDX

---

cli/cmd/policies.go

Backport of #1452 to `release/v1.8`.
---
Cronjobs used to be skipped by accident, works now.

[release/v1.8] cli: correct manifest generation for CronJob

---

docs/docs/deployment.md
e2e/internal/contrasttest/contrasttest.go
e2e/internal/kubeclient/wait.go
e2e/openssl/openssl_test.go
e2e/release/release_test.go
internal/kuberesource/parts.go
internal/kuberesource/sets.go
justfile
packages/scripts.nix

This PR adds a readiness probe to the Coordinator that checks whether the Coordinator is ready to serve `meshapi` requests, i.e. has a manifest configured that is not stale. The `userapi` can still be reached via the `coordinator:1313` service endpoint, even if unready, to allow initial `SetManifest` calls. Users may need to update any logic that waits for a Coordinator instance to be `Ready` before calling `contrast set`: it now only needs to be in phase `Running`.
---
Internally, we add a new service - `coordinator-ready` - backed by `Ready` Coordinators. This service is used by initializers and in peerrecovery, so that we only hit Coordinator endpoints that can actually serve requests. The idea is described in RFC 010:
https://github.com/edgelesssys/contrast/blob/cc41f2021a307f0dd9c00f4 …

coordinator: consider instances with stale or no manifests unready

---

.github/workflows/e2e_manual.yml
.github/workflows/e2e_nightly.yml
coordinator/main.go
coordinator/main_enterprise.go
coordinator/main_oss.go
docs/docs/howto/coordinator-ha.md
docs/sidebars.js
e2e/internal/kubeclient/deploy.go
e2e/peerrecovery/peerrecovery_test.go
packages/by-name/contrast/package.nix

This PR adds support for deploying multiple replicas of the Coordinator.
Further reading:
* [RFC 010](rfc/010-distributed-coordinator.md)
* [Documentation](https://docs.edgeless.systems/contrast/howto/coordinator-ha) (after v1.9 is released)
---
Testing:

coordinator: distributed deployment with auto-recovery

---

justfile

The `bm-tcb-specs` are explicitly installed into the default namespace, so we should specify it when querying the specs - otherwise, the recipe fails when the context from KUBECONFIG is not the default.

just: don't assume default namespace

---

e2e/internal/kubeclient/deploy.go
e2e/internal/kubeclient/kubeclient.go
e2e/internal/kubeclient/wait.go

We've been running into CI issues where exec into a pod failed with the `container not found` message ([ex](https://github.com/edgelesssys/contrast/actions/runs/15178262019/job/42682507768#step:11:216)). I ran this test a couple of times with additional logging, and found that the pod that we waited for is not the pod we're executing in. Looking closer, I noticed that we just restarted the deployment, which means there are additional pods around that are terminated, but not fully gone yet (because that takes a little while), and we end up executing into the terminating pods, which don't host that container anymore.
This PR fixes the situation by filtering terminating pods from most kubeclient results. We don't currently have a use case for keeping them.

kubeclient: ignore terminating pods

---

go.mod
go.sum
packages/by-name/contrast/package.nix

The used library for AMD SEV-SNP attestation doesn't support Siena. With this, we ship a patched version to support that product line.

deps: patch go-sev-guest with AMD Siena support

---

go.mod
go.sum
packages/by-name/contrast/package.nix

The used library for AMD SEV-SNP attestation doesn't support Siena. With this, we ship a patched version to support that product line.
(cherry picked from commit 7cd1717d7554cb077718bc493045a4a38011637c)

[release/v1.8] deps: patch go-sev-guest with AMD Siena support

---

packages/by-name/microsoft/genpolicy/0011-genpolicy-match-sandbox-name-by-regex.patch
packages/by-name/microsoft/genpolicy/0013-genpolicy-don-t-overwrite-env-vars-from-image.patch

Policies for controller workloads (DaemonSet, Deployment, StatefulSet, ReplicaSet, ReplicationController, Job, CronJob) used to be incorrect if the embedded pod template had `metadata.name` or `metadata.generateName` set, because the permissible pod sandbox names were derived wrongly. This PR corrects the expected generated pod names.
---
The logic we implemented in #1447 ff. does not actually correspond to Kubernetes' implementation. It's surprisingly hard to get authoritative sources for naming schemes ([except for Deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment)), but looking at the controller implementations confirms that `name` and `generateName` from [`PodTemplateSpec.metadata`](https://kubernetes.io/docs/reference/generated/ku …

microsoft.genpolicy: fix sandbox-name policy for pod controllers

---

packages/by-name/microsoft/genpolicy/0011-genpolicy-match-sandbox-name-by-regex.patch
packages/by-name/microsoft/genpolicy/0013-genpolicy-don-t-overwrite-env-vars-from-image.patch

Backport of #1477 to `release/v1.8`.
---
Policies for controller workloads (DaemonSet, Deployment, StatefulSet, ReplicaSet, ReplicationController, Job, CronJob) used to be incorrect if the embedded pod template had `metadata.name` or `metadata.generateName` set, because the permissible pod sandbox names were derived wrongly. This PR corrects the expected generated pod names.
---
The logic we implemented in #1447 ff. does not actually correspond to Kubernetes' implementation. It's surprisingly hard to get authoritative sources for naming schemes ([except for Deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment)), but looking at the controller implementations confirms that `name` and `generateName` from …

[release/v1.8] microsoft.genpolicy: fix sandbox-name policy for pod controllers

---

.github/workflows/release.yml

Release action failed because it wanted to commit changes in LICENSE file, which came over via release artifacts.

release: improve git cleaning between steps

---

internal/mount/mount.go

Since we're using raw block devices for our pods and mount from a container, neither the Kubelet nor the CSI driver is aware of our LUKS mapper + ext4 mount and can thus not clean them up before removing the block device, which may lead to data loss if caches are not synced.
This PR activates two mount options for increased safety of these encrypted volume mounts. They are not strictly necessary for the Coordinator volume mount, but that one will be phased out soon.
* `sync` makes writes synchronous: https://www.man7.org/linux/man-pages/man8/mount.8.html#FILESYSTEM-INDEPENDENT_MOUNT_OPTIONS
* `data=journal` is the most conservative journaling mode of ext4: https://www.kernel.org/doc/Documentation/filesystems/ext4.txt
The `sync` option in particular comes with a high throughput cost, but …

initializer: safer data handling for encrypted mount

---

internal/mount/mount.go

Backport of #1490 to `release/v1.8`.
---
Since we're using raw block devices for our pods and mount from a container, neither the Kubelet nor the CSI driver is aware of our LUKS mapper + ext4 mount and can thus not clean them up before removing the block device, which may lead to data loss if caches are not synced.
This PR activates two mount options for increased safety of these encrypted volume mounts. They are not strictly necessary for the Coordinator volume mount, but that one will be phased out soon.
* `sync` makes writes synchronous: https://www.man7.org/linux/man-pages/man8/mount.8.html#FILESYSTEM-INDEPENDENT_MOUNT_OPTIONS
* `data=journal` is the most conservative journaling mode of ext4: https://www.kernel.org/doc/Documentation/filesystems/ext4.txt
The …

[release/v1.8] initializer: safer data handling for encrypted mount

---

e2e/regression/testdata/prometheus.yml
packages/by-name/kata/kata-runtime/0019-genpolicy-fix-svc_name-regex.patch
packages/by-name/kata/kata-runtime/0020-genpolicy-rename-svc_name-to-svc_name_downward_env.patch
packages/by-name/kata/kata-runtime/package.nix

Backport of #1491 to `release/v1.8`.
---
The genpolicy-settings.json generated by the Contrast CLI contained a regex that didn't allow service names containing numbers, but allowed invalid service names containing dots. This PR corrects the regex to match RFC 1035.

[release/v1.8] kata.kata-runtime: genpolicy fix svc_name

---

e2e/internal/kubeclient/portforward.go

gRPC errors don't wrap their error causes, but only embed them with `#v`. EOFs are usually retriable, so we should relax the EOF check to also match these.
I just ran into this issue twice in the same workflow run: https://github.com/edgelesssys/contrast/actions/runs/15296392968/attempts/1.

kubeclient: retry port-forward on non-wrapped EOFs

---

e2e/volumestatefulset/volumestatefulset_test.go
internal/logger/handler.go

* reduce log level of logger init - this should remove log messages on AKS LB health checks at INFO and above.
* encrypted volume is mounted with `-o sync` already (#1490)

Clean up a few obsolete code paths

---

.github/workflows/cluster_recreate.yml

* the quotation marks added in b344d04d48e699e1dc71d99b41ce65f35af32b6c disabled the curly brace expansion
* ensure correct `az` CLI by calling `nix develop`, like #1449

ci: fix bugs in cluster_recreate

---

cli/cmd/generate.go
internal/manifest/manifest.go
internal/manifest/manifest_test.go
internal/manifest/referencevalues.go

- running `contrast generate` on a resource without a coordinator will now ~~fail~~ inform the user about the missing coordinator on the first invocation, instead of (previously) giving an unrelated info message and failing on the second invocation
- if reference values described in [the docs](https://docs.edgeless.systems/contrast/next/deployment?platform=k3s-qemu-tdx#generate-policy-annotations-and-manifest) are (expectedly) missing, show the old info message, since this is the error case it applies to
- for all other errors, including unexpectedly missing reference values, return the error and fail manifest generation

cli: first invocation of `generate` should fail if resource does not have a coordinator

---

packages/by-name/microsoft/genpolicy/0015-genpolicy-correctly-represent-binaryData-in-ConfigMa.patch
packages/by-name/microsoft/genpolicy/package.nix

This PR adds a patch that fixes `contrast generate` on ConfigMaps that contain `binaryData` fields. The patch is taken from this commit on `kata-containers/kata-containers`: https://github.com/kata-containers/kata-containers/commit/c06bf2e3bb696016be0357c373b0c68e10602b57

msft.genpolicy: correctly represent binaryData in ConfigMaps

---

.github/workflows/bm_maintenance.yml
packages/cleanup-bare-metal.sh
packages/containers.nix
packages/scripts.nix
tools/bm-maintenance/cleanup-containerd.yml

This separates and revises the step to clean up the containerd store on the bare metal servers. This is no longer executed daily, but rather weekly or by `workflow_dispatch`. It uses the `--sync` option from `ctr image rm` to perform garbage collection on all associated resources on all images. If any images were otherwise deleted, leftover content can be cleaned up using `ctr content prune references`.
Successful run with containerd cleanup: https://github.com/edgelesssys/contrast/actions/runs/15418145640

ci: add weekly containerd store cleanup

---

packages/containers.nix
packages/scripts.nix
tools/bm-maintenance/nix-gc.yml

The nix garbage collection only deletes enough bytes, such that at least 1/4 of disk space is always free. With our current setup, that should still be around 400GB. Depending on the server, the `/nix` directory is mounted on a separate partition, which should make this even less of a problem.
Successful run (no store paths should be deleted, since there is enough space): https://github.com/edgelesssys/contrast/actions/runs/15678983961

ci: only cleanup nix store if disk space is low

---

.github/workflows/bm_maintenance.yml

With the `cleanup-containerd` job being executed only once a week, the `notify-teams` job will always be skipped if the `cleanup-containerd` job is skipped, since it is listed in the `needs` section. This is also the case for cancelled jobs, e.g., when a runner is down.
Since we manually check for the outputs of the jobs anyway, we can change the condition from `failure()` to `always()`. That way, even if one of the dependent jobs is skipped or cancelled, it will still be executed.  If no job failed, the notify teams step is then not executed. Cancelled jobs are treated as failed jobs.
Successful run with notification: https://github.com/edgelesssys/contrast/actions/runs/15680569288

ci: notify teams even if previous job is skipped/cancelled

---

packages/by-name/kata/kata-runtime/0026-genpolicy-keep-layers-cache-in-memory.patch
packages/by-name/kata/kata-runtime/package.nix
packages/by-name/microsoft/genpolicy/0016-genpolicy-prevent-corruption-of-the-layer-cache-file.patch
packages/by-name/microsoft/genpolicy/package.nix

`fs2` file locks where used incorrectly: the lock was only being applied to write procedures, not to read (or delete, though this is not directly relevant for our issue).
For large enough strings, parsing takes long enough for a race condition to occur and the file is corrupted. The warning from the logs is the result, since the json file can no longer be parsed.
The reproducer from the ticket actually does not exhibit this behavior since approximately kata-containers 3.17.0, since improvements were made to the string parsing; however, for large enough json strings in the initial state of the later cache file, it can still be triggered.
Upstream PR: kata-containers/kata-containers#11426

kata: add patch preventing corruption of genpolicy's layer cache file

---

e2e/regression/testdata/config-map.yml

This tests consumption of `binaryData` in the regression test

e2e/regression: binaryData in ConfigMap

---

coordinator/internal/peerrecovery/recovery.go
coordinator/internal/peerrecovery/recovery_test.go
coordinator/internal/probes/probes.go
coordinator/internal/probes/probes_test.go
coordinator/main.go

If the Kubernetes API becomes unavailable, the Coordinator will fail the liveness probe and be restarted eventually. This defeats the point of automatic peer recovery, because it is very likely that all Coordinators are experiencing the API downtime at the same time, so will all be restarted and not have any peers to recover from.
This PR replaces the liveness probe with the startup probe, because there are no liveness conditions within the Coordinator that do not explicitly lead to process termination. Checking the startup probe again should suffice for detecting network or VM problems. This is aligned with [k8s best practices](https://codefresh.io/learn/kubernetes-management/kubernetes-liveness-probes/), h/t @thomasten. 
Bundled with this change, the startup probe now includes one round …

coordinator: don't fail liveness probe if Kubernetes API server is unavailable

---

.gitignore

Occasionally when running `just e2e ...`, `.tmp...` directories are created. These are unwanted in the source tree and should be ignored

chore: add .tmp directories to gitignore

---

packages/by-name/buildVerityMicroVM/package.nix
packages/by-name/kata/kata-runtime/package.nix

This is based on https://github.com/kata-containers/kata-containers/commit/c6537192701a5843328191f0ef7b61a9b34cc1b6
The `systemd.unified_cgroup_hierarchy=1` is deprecated in current systemd versions.
First commit just improves readability, no functional change.

nixos: enforce cgroupv2

---

overlays/nixpkgs.nix

Used the wrong url when introducing this, the head of that pull is now gone.

overlays: update libnvidia-container patch

---

coordinator/internal/peerrecovery/recovery.go
coordinator/internal/peerrecovery/recovery_test.go
coordinator/internal/probes/probes.go
coordinator/internal/probes/probes_test.go
coordinator/main.go
internal/kuberesource/parts.go

Reapply #1542, with an additional change: the startup probe gave up after 3s, which is not long enough to attempt peer recovery. Changed that to a minute.

coordinator: don't fail liveness probe if Kubernetes API server is unavailable (reapply)

---

initializer/main.go

Fixes a regression introduced by 830c2ebf63dedb0b3657a30313779913a1fcb648, which did not take LUKS2 lock files into account.

initializer: create /run directory for cryptsetup

---

initializer/main.go

Backport of #1565 to `release/v1.9`.
---
Fixes a regression introduced by 830c2ebf63dedb0b3657a30313779913a1fcb648, which did not take LUKS2 lock files into account.

[release/v1.9] initializer: create /run directory for cryptsetup

---

packages/nixos/gpu.nix

The latest production driver isn't supported by Nvidia RIM, so use this version instead. persistenced isn't available for that version, so use it with another version.

gpu: pin nvidia driver to 570.158.01

---

e2e/gpu/gpu_test.go

The libraries we expose into the container are relied upon by the user, so we need to ensure these are stable, or at least detect changes to warn about them. Note this PR doesn't include library ABI version stability guarantees, which is something we could think about checking, too.

e2e/gpu: check for mounted libs/binaries

---

.github/workflows/bm_maintenance.yml
.github/workflows/e2e.yml
justfile
packages/cleanup-namespaces.sh
packages/scripts.nix
tools/bm-maintenance/cleanup-namespaces.yml

When running `just` on the GPU CI cluster, devs and CI jobs are now both required to get a sync ticket. This primarily prevents failing E2E tests due to a blocked GPU by a dev. A sync ticket is acquired on `just apply` and released on `just undeploy`. The ticket acquired in the `justfile` has a lifetime of 90m, but note that any namespace older than 1h will automatically be cleaned up. This requires https://github.com/katexochen/sync/pull/1.

just: acquire fifo ticket for gpu platform

---

.github/actions/setup_nix/action.yml

'build dir' no longer defaults to TMPDIR:
https://nix.dev/manual/nix/2.30/release-notes/rl-2.30.html#backward-incompatible-changes-and-deprecations

ci: fix nix build dir setup after update to nix 2.30

---

.github/workflows/docs_publish.yml

To harden the workflow, don't run it on any PRs originating from forks.

ci: don't run docs-publish on PRs from forks

---

.github/workflows/docs_publish.yml

This fixes an issue introduced in ce49f90072fba55ed27821c4b4e13606df9d873c.
Docs aren't build anymore on main, as the event.pull_request doesn't exist (the event is push on main).

ci: fix docs build on main

---

e2e/policy/policy_test.go
e2e/volumestatefulset/volumestatefulset_test.go
e2e/workloadsecret/workloadsecret_test.go

Some pods may fail to restart fast enough to satisfy context timeouts. This PR increases the timeouts for all cases where a pod is restarted to 2 minutes.

e2e: increase timeout limits for tests that restart pods

---

nodeinstaller/internal/kataconfig/update-testdata/main.go
packages/scripts.nix

Decided to re-do the bash script in go because it seemed easiest to access `KataRuntimeConfig` directly, and splitting the config update between a bash script and a go bin didn't seem super intuitive.
Having a separate `go.mod` here seems wrong, not sure how else to access the `internal` package though?

nodeinstaller: automatically update testdata on kata config update

---

dev-shells/by-name/kata.nix

image-rs, cdh, and possibly some other parts of https://github.com/confidential-containers/guest-components/tree/main need this.
Didn't think it worth creating an almost identical shell to the kata one...

dev-shells: make kata shell work for cdh

---

.github/workflows/e2e_aks_runtime.yml

This fixes the E2E test since `confcom` depends on openssl-1.1, but it wasn't installed.

e2e/aks-runtime: install openssl-1.1

---

docs/README.md

That directory isn't guaranteed to exist, as there might not be any previews deployed, causing the link checker to fail. Point to top-level of the branch instead.

docs: remove link to pr-preview dir

---

.github/workflows/rim_updates.yml
.github/workflows/rpm_updates.yml

Update PRs were silently closed for some reason: https://github.com/edgelesssys/contrast/pull/1644
Setting a branch for the update fixes it (and prevents rim updates from landing in the rpm update pr), see https://github.com/edgelesssys/contrast/pull/1645

ci: set branch for rim/rpm update PRs

---

e2e/regression/testdata/pod-secret-and-cm/cm.yml
e2e/regression/testdata/pod-secret-and-cm/pod.yml
e2e/regression/testdata/pod-secret-and-cm/secret.yml

Add a test that consumes a secret and a config map in a pod. Needs https://github.com/edgelesssys/contrast/pull/1535 before merging.

e2e/regression: extend test for secrets and config maps

---

packages/nixos/system.nix

Our `/etc` is immutable, but we don't have a machine-id file. This seems to confuse systemd, causing the following errors to be logged (see dmesg container):
```
[    2.686639] systemd[1]: System cannot boot: Missing /etc/machine-id and /etc is mounted read-only.
[    2.686826] systemd[1]: Booting up is supported only when:
[    2.686931] systemd[1]: 1) /etc/machine-id exists and is populated.
[    2.687072] systemd[1]: 2) /etc/machine-id exists and is empty.
[    2.687239] systemd[1]: 3) /etc/machine-id is missing and /etc is writable.
```
I'm not sure what the practical implications are - maybe it's just not an issue because nothing in our image relies on first-boot semantics. The message "System cannot boot" is clearly exaggerated ...

nixos: add empty /etc/machine-id

---

packages/by-name/kata/kata-runtime/0024-genpolicy-add-rule-for-AddARPNeighbors.patch
packages/by-name/kata/kata-runtime/package.nix

Some Kubernetes environments have static ARP cache entries, which need to be propagated to the confidential VM (we assume that they are there for a reason). Running Contrast in such an environment was not possible so far, because the pod sandbox would be rejected due to the static ARP entries.
This PR adds a policy check for static ARP entries. Since traffic leaving through the pod's network interface must be secured anyway, this policy only ensures that the ARP entry does not unexpectedly redirect traffic away from internal network interfaces (i.e., `lo`).

genpolicy: support AddARPNeighbors

---

imagepuller/client/client.go
tools/imagepuller-benchmark/main.go

Opted for printing a warning instead of removing everything time-related.

ci: do not fail imagepuller-benchmark due to time delta

---

go.mod
go.sum
packages/by-name/contrast/package.nix

This supports the new SEV ABI Version 1.58 and ensures compatibility of contrast with SEV firmware >=1.55.45.

snp: add support for attestation report v5

---

internal/manifest/referencevalues.go
nodeinstaller/internal/kataconfig/config.go

We should be aware if we embed structs with unsupported fields.

treewide: disallow unknown fields for embedded

---

overlays/nixpkgs.nix

https://gitlab.com/cryptsetup/cryptsetup/-/raw/main/docs/v2.8.1-ReleaseNotes

overlays/cryptsetup: 2.8.0 -> 2.8.1

---

overlays/nixpkgs.nix

Backport of #1712 to `release/v1.12`.
---
https://gitlab.com/cryptsetup/cryptsetup/-/raw/main/docs/v2.8.1-ReleaseNotes

[release/v1.12] overlays/cryptsetup: 2.8.0 -> 2.8.1

---

packages/containers.nix

Reducing burden to recompile on our side, also this gets faster/more regular security updates.

service-mesh: use envoy-bin package

---

internal/manifest/runtimehandler_test.go

Skip the runtime handler test when no references values are embedded (i.e., outside the nix build) because it will fail otherwise.

internal/manifest: skip runtime handler test without embedded values

---

cli/cmd/generate.go
cli/verifier/no_shared_fs_mount.go
cli/verifier/no_shared_fs_mount_test.go
cli/verifier/verifiers.go

This adds a verifier to be run before `genpolicy` that forbids the following:
1. `volumeMount`s that don't reference a volume of type `configMap`, `downwardAPI`, `emptyDir`, `ephemeral`, `projected` or `secret`
2. `volumeClaimTemplate`s that are not of `volumeMode: Block`

cli/verifier: add `NoSharedFSMount` verifier

---

docs/docs/architecture/components/service-mesh.md
docs/docs/architecture/k8s-yaml-elements.md
docs/docs/architecture/secrets.md
docs/docs/getting-started/deployment.md
docs/docs/howto/vault.md
docs/docs/howto/workload-deployment/TLS-configuration.md
docs/docs/howto/workload-deployment/generate-annotations.md
docs/sidebars.js
internal/kuberesource/mutators.go
internal/kuberesource/mutators_test.go
internal/kuberesource/sets.go
internal/kuberesource/wrappers.go

Previously, we had two places where Contrast annotations could go:
- On the top level resource meta, e.g., service mesh and secure PV annotations.
- On the pod template meta, e.g., pod role, workload secret ID.
With this change, all Contrast annotations are specified in the pod template meta. All annotations are documented in a table in the docs.
This affects all workloads that define one of the following annotations:
- `contrast.edgeless.systems/skip-initializer`
- `contrast.edgeless.systems/servicemesh-ingress`
- `contrast.edgeless.systems/servicemesh-egress`
- `contrast.edgeless.systems/servicemesh-admin-interface-port`
- `contrast.edgeless.systems/secure-pv`
Running `contrast generate` on these workloads will ignore the annotations. To migrate, move the annotations from the top-level …

kuberesource: change annotation position to pod template

---

docs/docs/getting-started/deployment.md
docs/docs/howto/encrypted-storage.md

Deduplication showed to be more difficult as thought, updating the outdated spots for now.

docs: sync missing reference sections

---

e2e/servicemesh/servicemesh_test.go
internal/kuberesource/sets.go
service-mesh/config.go
service-mesh/main.go

The service mesh used to always set up a secure ingress configuration even if the annotation was not set, preventing the exclusive use of egress. This PR allows setting up egress without ingress by setting the special ingress annotation value `DISABLED`.
For testing, we're configuring the vote-bot with a disabled ingress and confirm that there is no `TPROXY` redirection.

service-mesh: allow egress without ingress

---

imagepuller/internal/remote/remote.go
imagepuller/internal/service/service.go
imagepuller/internal/service/stubs_test.go
imagepuller/internal/service/verify.go
imagepuller/internal/service/verify_test.go
imagepuller/internal/test/registry/content.go
imagepuller/main.go

This PR adds more in-depth tests of `getAndVerifyImage` and `storeAndVerifyLayers`, not focusing on the validation side like the evil registry tests did.
However, I've still used the (sometimes) evil registry extensively in this; AFAICT, it's by far the easiest way to test the functions' behaviors depending on what the registry answers, as well as getting an actual oci image for use in the layer-specific tests.
As a result, these tests look very similar to those against the evil registry; I'm ambivalent on keeping them separate or combining them. They *do* serve slightly different purposes, and it might be nice to tell just from the names.

imagepuller: add unit tests

---

cli/verifier/servicemesh_egress.go
cli/verifier/servicemesh_egress_test.go
cli/verifier/verifiers.go

This PR adds a verifier that checks that the `contrast.edgeless.systems/servicemesh-egress` annotation is not empty.
Previously, setting the annotation to the empty string would disable egress but trigger ingress to be activated, which is likely not the intended behavior. The correct way to prevent egress rules setup is to not add the egress annotation.

cli/verifier: check servicemesh-egress annotation isn't empty

---

e2e/openssl/openssl_test.go
initializer/mount.go
internal/cryptsetup/cryptsetup.go
internal/cryptsetup/ext4.go

Moving the ext4 code a little so it can also be used in #1685. The setup is coupled to the integrity setup anyway and easy to get wrong, so integrating that part into the lib.

internal/cryptsetup: provide ext4 setup

---

docs/docs/howto/workload-deployment/deploy-application.md

Applying resources with `kubectl apply -n` won't work, as the namespace wan't included into the policy during generate.

docs: warn about usage of kubectl apply -n

---

nodeinstaller/internal/kataconfig/update-testdata/main.go

In the CI, the step following after generate is responsible for failing on diff and showing the diff in a usable fashion. Currently, the job will just fail without a usable output in case files are updated.

node-installer/update-testdata: don't fail on changes

---

packages/contrast-releases.nix

- removed version was wrong for k3s runtimes
- missed removal of rke2
- missed removal of aks

contrast-releases: fix runtime existence

---

e2e/internal/contrasttest/contrasttest.go
internal/kuberesource/mutators.go
internal/kuberesource/parts.go
internal/kuberesource/resourcegen/main.go

The release artifact used the wrong namespace, so the node-installer couldn't find it. The fix adapts the same namespace handling as with the runtime: default to kube-system, use PatchNamespaces in development/e2e.

kuberesource: default target config to kube-system namespace

---

.github/workflows/e2e_regression.yml

Tests can't be in regression and nightly e2e at the same time, otherwise they are executed twice and their names collide in the logs upload on release.
See https://github.com/edgelesssys/contrast/actions/runs/17490862857/job/49680438660

ci: remove imagestore from e2e regression

---

e2e/regression/testdata/memory-limit/memory-limit.yml

Add a regression test to test the application of memory limits for containers, init containers and sidecar containers.

ci/regression: add memory limit test

---

internal/kuberesource/parts.go
tools/lychee/config.toml

We often see e2e tests that time out while waiting for a connection proxied by socat. This can happen if the target endpoint was not quite available yet, for example when the routes were not yet established. In its default configuration, socat keeps waiting for the SYN/ACK to arrive, possibly until the kernel gives up on the connection.
What we actually want in this case is to abort the connection attempt and retry it. This needs to be done in socat, because the client can't tell the difference between an established connection that's not sending data and a connection being initiated between socat and the backend. Thus, we configure the connection timeout at 2s, which should be plenty for reachable endpoints in the same cluster, but short enough to avoid a test timeout. Adding a retry on …

e2e: abort hanging connections early

---

.github/workflows/bm_maintenance.yml

This should fix the sporadic failures where an E2E test waits forever in the sync queue.

ci/bm-maintenance: upgrade sync-server

---

e2e/openssl/openssl_test.go

This happened in a CI flake the other day. Although the issue was likely an earlier failing test, it would be good to have the openssl connection logs for debugging this situation.

e2e: add openssl logging for unexpected success

---

e2e/internal/kubeclient/deploy.go
e2e/openssl/openssl_test.go

The openssl test is still sporadically failing. From the logs re-introduced in #1801, I see that the server-side certificates seem to match expectations. What I'd like to know now is how the certs passed to the client look like, so I write them to stdout before running the command. `set -x` ensures that we see what's executed and thus understand the output better.
Furthermore, I noticed that pod restarts are not visible in the logs, so I added a log line.

e2e: more debug logging for openssl_test

---

cli/verifier/image_ref_valid.go
cli/verifier/image_ref_valid_test.go
cli/verifier/verifiers.go
cli/verifier/versions_match.go
cli/verifier/versions_match_test.go
go.mod
go.sum
packages/by-name/contrast/package.nix

Version mismatches between the Contrast CLI and the Contrast resources used (specifically, the `coordinator`, `initializer` and `service-mesh-proxy`) can lead to hard-to-debug errors.
Starting with this PR, `contrast generate` will fail if a version mismatch is encountered. The error message will inform you which resource needs updating.

cli/verifier: add `VersionsMatch`

---

.github/workflows/k3s_compatibility.yml

This runs the node installer on a fresh K3s installation and checks if the contrast runtime is correctly configured. This can run on a GitHub runner, as there are no platform-specific requirements for copying the files and configuring a runtime class.

ci: test nodeinstaller compatibility on k3s

---

cli/cmd/generate.go
cli/genpolicy/genpolicy.go
internal/kuberesource/reader.go
internal/kuberesource/reader_writer_test.go

This changes the `YAMLBytesFromFile` function to accept multiple paths, so we can directly use it to generate the combined YAML output during `generate` when the `--output` flag is set. This also fixes the combined output, which was broken after #1798, and adds a unit test for the `YAMLBytesFromFiles` function.

cli: fix combined output yaml
