edgelesssys/contrast

packages/by-name/buildGoTest/package.nix
packages/by-name/contrast-node-installer-image/package.nix
packages/by-name/contrast-node-installer/package.nix
packages/by-name/contrast/package.nix
packages/by-name/genpolicy-kata/package.nix
packages/by-name/igvm-signing-keygen/package.nix
packages/by-name/igvm-tooling/package.nix
packages/by-name/igvmmeasure/package.nix
packages/by-name/kata-agent/package.nix
packages/by-name/kata-igvm/package.nix
packages/by-name/kata-image/package.nix
packages/by-name/kata-kernel-uvm/package.nix
packages/by-name/kata-runtime/package.nix
packages/by-name/ociImageConfig/package.nix
packages/by-name/ociImageLayout/package.nix
packages/by-name/ociImageManifest/package.nix
packages/by-name/ociLayerTar/package.nix
packages/by-name/rpm-pin-vendor/package.nix
packages/by-name/runtime-class-files/package.nix
packages/by-name/service-mesh/package.nix
packages/containers.nix
packages/scripts.nix

Just doing some cleanup, formatting, removing unused args/recs, improving with scopes, inserting some whitespace.

packages: minor nix cleanup

---

README.md
docs/docs/deployment.md
docs/docs/features-limitations.md
docs/sidebars.js

This renames the "Known limitations" section and simplifies its intro.

Rename "limitations" section

---

.github/workflows/docs_publish.yml
.github/workflows/static.yml

Trying to fix some of the CI failures for external contributors. e2e runs will still fail for now. Didn't test this yet.

ci: improvements for external contributors

---

packages/scripts.nix

Not needed anymore after https://github.com/edgelesssys/contrast/pull/541

packages/scripts.fetch-latest-contrast: remove

---

.github/workflows/rpm_updates.yml

see https://github.com/edgelesssys/contrast/pull/549

ci: add workflow to update rpm package pins

---

packages/scripts.nix

Got that wrong in https://github.com/edgelesssys/contrast/pull/553#discussion_r1634727120

packages/scripts: add accidentally removed input

---

docs/package.json
docs/yarn.lock
packages/by-name/contrast-docs/package.nix

Search plugin doesn't work with docusaurus 3.4.0. It generates wrong URLs. Downgrade until cmfcmf/docusaurus-search-local#205 is resolved.

docs: fix search

---

.github/workflows/release.yml

Signed-off-by: miampf <miampf@proton.me>
(cherry picked from commit 517187c6ce2103325f3609baee82ff91a412f9b8)

[release/v0.7] release: fix update of contrast-releases.json

---

packages/by-name/microsoft/kata-image/package-index.json

Automated updated created by [rpm_updates workflow](https://github.com/edgelesssys/contrast/blob/main/.github/workflows/rpm_updates.yml).

deps: update pinned rpm packages

---

justfile

Instead of transforming the current `just default` target into an E2E-test, which disrupts the dev workflow by doing all steps like `generate`, `apply`, `set` and `verify` at once in the E2E test, this adds a new `just e2e` target which can run both the `openssl` and `servicemesh` tests without deleting the namespace afterward.

just: add e2e target

---

docs/versioned_docs/version-0.7/features-limitations.md

Add notion about the availability of bare metal.

docs: add bare metal availability

---

docs/versioned_docs/version-0.7/components/service-mesh.md
docs/versioned_docs/version-0.7/deployment.md
docs/versioned_docs/version-0.7/examples/emojivoto.md
docs/versioned_docs/version-0.7/getting-started/install.md
packages/contrast-releases.json

Updating main as part of the 0.7.1 release.

Post 0.7.1 release updates to main

---

dev-docs/aks/life-of-a-confidential-container.md
tools/vale/styles/config/vocabularies/edgeless/accept.txt

Review recommendation: use markdown preview mode.

dev-docs: life of a confidential container

---

docs/versioned_docs/version-0.7/components/service-mesh.md
docs/versioned_docs/version-0.7/deployment.md
docs/versioned_docs/version-0.7/examples/emojivoto.md
docs/versioned_docs/version-0.7/getting-started/install.md
packages/contrast-releases.json

Updating main as part of the 0.7.2 release.

Post 0.7.2 release updates to main

---

docs/versioned_docs/version-0.7/components/service-mesh.md
docs/versioned_docs/version-0.7/deployment.md
docs/versioned_docs/version-0.7/examples/emojivoto.md
docs/versioned_docs/version-0.7/getting-started/install.md
packages/contrast-releases.json

Updating main as part of the 0.7.3 release.

Post 0.7.3 release updates to main

---

justfile

- Add support for undeploying e2e runs with `just undeploy`
- Simplify e2e target. This allows running all existing e2e tests, at the cost of slightly worse error message if the test does not exist. Run undeploy as a dependency, remove special undeploy handling.

just: refactor e2e target, use undeploy target for e2e

---

e2e/internal/contrasttest/contrasttest.go
e2e/internal/kubeclient/kubeclient.go

I hope that this could provide meaningful debugging information for situations like this: https://github.com/edgelesssys/contrast/actions/runs/9869593060/job/27254148527?pr=694.
Example log: https://github.com/edgelesssys/contrast/actions/runs/9872144506/job/27261632120?pr=701#step:12:186.

e2e: log debug info on test failure

---

.github/workflows/e2e_runtime-reproducibility.yml

Run: https://github.com/edgelesssys/contrast/actions/runs/9935664109

e2e: fix reproducibility test, don't fail fast

---

docs/versioned_docs/version-0.8/components/service-mesh.md
docs/versioned_docs/version-0.8/deployment.md
docs/versioned_docs/version-0.8/examples/emojivoto.md
docs/versioned_docs/version-0.8/getting-started/install.md
docs/versioned_docs/version-0.8/troubleshooting.md
packages/contrast-releases.json

Updating main as part of the 0.8.1 release.

Post 0.8.1 release updates to main

---

cli/cmd/recover.go
cli/cmd/set.go
cli/cmd/verify.go
coordinator/main.go
coordinator/meshapi.go
docs/docs/troubleshooting.md
go.mod
go.sum
initializer/main.go
internal/attestation/issuer.go
internal/attestation/reportdata/reportdata.go
internal/attestation/snp/issuer.go
internal/attestation/snp/validator.go
internal/attestation/tdx/issuer.go
internal/logger/handler.go
internal/oid/oid.go
node-installer/internal/constants/constants.go
node-installer/node-installer.go
packages/by-name/contrast/package.nix
packages/by-name/kata/contrast-node-installer-image/package.nix
packages/by-name/kata/kata-runtime/0001-govmm-Directly-pass-the-firwmare-using-bios-with-SNP.patch
packages/by-name/kata/kata-runtime/0002-emulate-CPU-model-that-most-closely-matches-the-host.patch
packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
packages/by-name/kata/runtime-class-files/package.nix

This adds an attestation issuer for TDX and makes the node-installer work with both SNP and TDX. See commit messages for more detailed descriptions.

attestation: add TDX issuer

---

packages/by-name/kata/kata-agent/package.nix
packages/by-name/kata/kata-kernel-uvm/package.nix
packages/by-name/kata/kata-runtime/0001-govmm-Directly-pass-the-firwmare-using-bios-with-SNP.patch
packages/by-name/kata/kata-runtime/0002-emulate-CPU-model-that-most-closely-matches-the-host.patch
packages/by-name/kata/kata-runtime/0003-runtime-agent-verify-the-agent-policy-hash.patch
packages/by-name/kata/kata-runtime/package.nix

https://github.com/kata-containers/kata-containers/releases/tag/3.7.0

kata: 3.6.0 -> 3.7.0

---

justfile

just: add get-credentials-snpbm

---

.vale.ini
docs/docs/architecture/attestation.md
docs/docs/getting-started/cluster-setup.md
docs/docs/troubleshooting.md
docs/versioned_docs/version-0.5/getting-started/cluster-setup.md
docs/versioned_docs/version-0.6/architecture/attestation.md
docs/versioned_docs/version-0.6/getting-started/cluster-setup.md
docs/versioned_docs/version-0.7/architecture/attestation.md
docs/versioned_docs/version-0.7/getting-started/cluster-setup.md
docs/versioned_docs/version-0.8/architecture/attestation.md
docs/versioned_docs/version-0.8/getting-started/cluster-setup.md
docs/versioned_docs/version-0.8/troubleshooting.md
tools/vale/styles/config/vocabularies/edgeless/accept.txt

Suggesting to enable two more Vale rules. What do you think?

vale: enable Microsoft.FirstPerson and Microsoft.Terms

---

packages/by-name/cli-release/package.nix
packages/by-name/contrast/package.nix

This fixes the release build of the CLI.
Fixes: ad7ca97

cli-release: embed reference values

---

packages/by-name/kata/kata-runtime/0004-qemu-don-t-emit-scsi-parameter.patch
packages/by-name/kata/kata-runtime/package.nix
packages/by-name/qemu-static/0001-avoid-duplicate-definitions.patch
packages/by-name/qemu-static/0002-add-options-for-library-paths.patch
packages/by-name/qemu-static/package.nix

This is the first release-candidate with SNP support.

qemu-static: update to 9.1.0-rc0

---

justfile

As the node-installer is now long running, we might want to deploy multiple next to each other, so putting it in the namespace will allow us to do so. Also this allows better cleanup on undeploy.

just: deploy node-installer in namespace

---

e2e/internal/contrasttest/contrasttest.go
internal/attestation/snp/issuer.go
internal/kuberesource/mutators.go
internal/kuberesource/resourcegen/main.go
justfile

Add the supported env vars to the deployment so configuring them is easier. This also let's the Coordinator default to log level debug for now.

resourcegen: add flag to configure logging;  snp/issuer: log quote provider in use

---

.github/workflows/release.yml
e2e/release/release_test.go
internal/kuberesource/resourcegen/main.go
packages/contrast-releases.nix
packages/scripts.nix
packages/update-contrast-releases.sh

Now that we support more than one platform, we have to create deployment files for the different corresponding runtime class names.

release: generate deployment files for all platforms

---

internal/kuberesource/mutators.go
internal/kuberesource/resourcegen/main.go
justfile
packages/containers.nix

Collect with
```
k logs -n openssl-p -c dmesg coordinator-0
```

resourcegen: enable adding dmesg container

---

internal/attestation/certcache/cached_client.go

Unlike VCEKs, these can change over time and the KDS doesn't rate-limit requests to these. Caching and returning old CRLs leads to problems because the go-sev-guest library assumes that it always gets a fresh CRL.

certcache: don't cache CRL URLs

---

e2e/internal/contrasttest/contrasttest.go

Deleting the namespace sometimes fails when the cluster is unavailable (e.g. after a K3s restart). Retry deleting for up to 30 seconds.

e2e: try a little harder to delete the namespace

---

packages/by-name/qemu-static/0003-accel-kvm-check-for-KVM_CAP_READONLY_MEM-on-VM.patch
packages/by-name/qemu-static/package.nix

This patch has already been sent upstream.

qemu-static: fix a behaviour change in Linux 6.11-rc4

---

.gitignore
infra/azure-peerpods/main.tf
infra/azure-peerpods/vars.tf
treefmt.nix

Initial setup to get peer pods working on AKS, based on https://confidentialcontainers.org/docs/cloud-api-adaptor/azure/

infra: terraform resources for peerpods on Azure

---

.github/workflows/e2e.yaml
e2e/volumestatefulset/volumestatefulset_test.go
internal/kuberesource/mutators_test.go
internal/kuberesource/resourcegen/main.go
internal/kuberesource/sets.go
justfile
packages/by-name/contrast/package.nix
packages/by-name/microsoft/genpolicy/0001-genpolicy-add-rules-and-types-for-volumeDevices.patch
packages/by-name/microsoft/genpolicy/0002-genpolicy-add-ability-to-filter-for-runtimeClassName.patch
packages/by-name/microsoft/genpolicy/0003-genpolicy-allow-specifying-layer-cache-file.patch
packages/by-name/microsoft/genpolicy/0004-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
packages/by-name/microsoft/genpolicy/0005-genpolicy-propagate-mount_options-for-empty-dirs.patch
packages/by-name/microsoft/genpolicy/0006-genpolicy-support-HostToContainer-mount-propagation.patch
packages/by-name/microsoft/genpolicy/genpolicy_msft_rules_coordinator.patch
packages/by-name/microsoft/genpolicy/package.nix
packages/containers.nix

This is a precursor to the end-user documentation on how to use the workloadsecret to mount a luks-encrypted CSI disk.

e2e: add test for luks encryted state disk

---

go.work
internal/manifest/manifest.go
packages/by-name/contrast/package.nix
packages/by-name/kata/tdx-launch-digests/package.nix
packages/by-name/tdx-measure/package.nix
tools/tdx-measure/go.mod
tools/tdx-measure/go.sum
tools/tdx-measure/main.go
tools/tdx-measure/mrtd/mrtd.go
tools/tdx-measure/tdvf/tdvf.go

This PR adds a new tool, tdx-measure, uses it to pre-calculate the MRTD and verifies the MRTD.

tdx: calculate & verify MRTD

---

docs/docs/getting-started/cluster-setup.md
packages/create-coco-aks.sh

Seems to work without issues. Tested with the emojivoto project.

AKS: use k8s version 1.30

---

e2e/internal/kubeclient/portforward.go

Right now the port-forwarding is retried immediately, but we should give the system some time to rectify if there was some sort of connectivity problem.

e2e: apply backoff after failed port-forwarding attempt

---

infra/azure-peerpods/main.tf
infra/azure-peerpods/vars.tf
justfile
overlays/nixpkgs.nix
packages/scripts.nix

This PR adds a script/just target for automating the image upload of peerpod VM images and adjusts our Terraform configs to use the image id of the uploaded image.

automate peerpods image upload & use that in Terraform configs

---

e2e/servicemesh/servicemesh_test.go

e2e/servicemesh: set hostname explicitly

---

docs/versioned_docs/version-1.2/components/service-mesh.md
docs/versioned_docs/version-1.2/deployment.md
docs/versioned_docs/version-1.2/examples/emojivoto.md
docs/versioned_docs/version-1.2/examples/mysql.md
docs/versioned_docs/version-1.2/getting-started/install.md
docs/versioned_docs/version-1.2/troubleshooting.md
packages/contrast-releases.json

Updating main as part of the 1.2.1 release.

Post 1.2.1 release updates to main

---

.github/workflows/e2e_manual.yml
packages/scripts.nix

Looks like this was copied from justfile without syntax adjustment.

ci: fix platform case statements

---

.github/workflows/e2e_manual.yml
packages/scripts.nix

Backport of #1114 to `release/v1.2`.
---
Looks like this was copied from justfile without syntax adjustment.

[release/v1.2] ci: fix platform case statements

---

packages/by-name/microsoft/genpolicy/0001-genpolicy-add-rules-and-types-for-volumeDevices.patch
packages/by-name/microsoft/genpolicy/0002-genpolicy-add-ability-to-filter-for-runtimeClassName.patch
packages/by-name/microsoft/genpolicy/0004-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
packages/by-name/microsoft/genpolicy/0007-genpolicy-support-for-VOLUME-definition-in-container.patch
packages/by-name/microsoft/genpolicy/package.nix
packages/by-name/microsoft/kata-igvm/package.nix

https://github.com/microsoft/kata-containers/releases/tag/3.2.0.azl1.genpolicy1

microsoft.genpolicy: 3.2.0.azl1.genpolicy0 -> 3.2.0.azl1.genpolicy1

---

cli/cmd/policies.go

This PR adds support for Kubernetes cronjobs resources. It requires https://github.com/edgelesssys/contrast/pull/1128.

generate: support cronjobs

---

.github/workflows/e2e.yml
.github/workflows/e2e_aks_runtime.yml
.github/workflows/release.yml
internal/kuberesource/sets.go
justfile
packages/containers.nix

PR reverts the two introduced commits to main, which took place during the new release.
- https://github.com/edgelesssys/contrast/commit/1457127694d661223b79d8591e48c01e7c163217
- https://github.com/edgelesssys/contrast/commit/71f2ff79959eb477d2008df256d12165281634c8

revert: cryptsetup intergration to initializer

---

packages/by-name/tdx-tools/package.nix

https://github.com/canonical/tdx/releases

packages.tdx-tools: noble-24.04 -> 3.1

---

docs/versioned_docs/version-1.4/architecture/secrets.md
docs/versioned_docs/version-1.4/components/service-mesh.md
docs/versioned_docs/version-1.4/deployment.md
docs/versioned_docs/version-1.4/examples/emojivoto.md
docs/versioned_docs/version-1.4/examples/mysql.md
docs/versioned_docs/version-1.4/getting-started/install.md
docs/versioned_docs/version-1.4/troubleshooting.md
packages/contrast-releases.json

Updating main as part of the 1.4.1 release.

Post 1.4.1 release updates to main

---

cli/cmd/generate.go

This adds an output flag `--output` (`-o`) to `contrast generate` to specify an output file, instead of working in-place. Because a lot of operations during `contrast generate` are done in-place, the simplest solution is to just operate on a temporary copy of the deployment files, and combine the generated YAML into the specified output file.

cli/generate: add flag for output file

---

docs/versioned_docs/version-1.5/architecture/secrets.md
docs/versioned_docs/version-1.5/components/service-mesh.md
docs/versioned_docs/version-1.5/deployment.md
docs/versioned_docs/version-1.5/examples/emojivoto.md
docs/versioned_docs/version-1.5/examples/mysql.md
docs/versioned_docs/version-1.5/getting-started/install.md
docs/versioned_docs/version-1.5/troubleshooting.md
packages/contrast-releases.json

Updating main as part of the 1.5.1 release.

Post 1.5.1 release updates to main

---

justfile

I've manually uploaded a new secret/kubeconfig. The documentation will follow with all the other setup steps.

just: add kubeconfig of new SNP CI server

---

cli/cmd/set.go

`contrast set` panics if no workload owner key is provided. This is because `clientConnection.privKey` has the value `(*ecdsa.PrivateKey)(nil)`, which is not equal to nil. (The panic happens later in `publicKey()` when the underlying value nil is used.) We can fix this either by assigning nil in `set.go`, or by checking the underlying value in `atls.go`. So only one of the two changes of this PR is needed, but I'm not sure what is the preferred one.

cli: fix panic on set without workload owner key

---

cli/cmd/set.go

Backport of #1251 to `release/v1.5`.
---
`contrast set` panics if no workload owner key is provided. This is because `clientConnection.privKey` has the value `(*ecdsa.PrivateKey)(nil)`, which is not equal to nil. (The panic happens later in `publicKey()` when the underlying value nil is used.) We can fix this either by assigning nil in `set.go`, or by checking the underlying value in `atls.go`. So only one of the two changes of this PR is needed, but I'm not sure what is the preferred one.

[release/v1.5] cli: fix panic on set without workload owner key

---

internal/atls/atls.go
internal/atls/atls_test.go

Encoding aTLS nonces in SNI is problematic when the traffic is routed or inspected by (reverse) proxies. We can add the nonce to the list of ALPN next protocols instead, which suffices at least for the use case of routing by SNI. 
Using ALPN has some more advantages:
1. The specification allows for about 2^16 byte of data in the next protocol list (256 entries with 256B each).  SNI allows for one hostname of 256B per type (and there is only one type, afaik).
2. ALPN protocols are opaque strings (could even be byte slices, actually), while SNI is expected to be a valid domain name.
3. We could transfer even more information to the server using ALPN, for example a range of handshake versions and variants (e.g. TPM), or additional metadata. 
The proposed format for the nonce protocol string …

atls: encode nonce in ALPN protos

---

internal/retry/retry.go
internal/retry/retry_test.go

I'm adding these to allow for easier use of the retrier. First user of this API is #1313.

retry: add a few helpers

---

docs/docs/deployment.md
docs/docs/examples/emojivoto.md
docs/docs/examples/mysql.md

these flags are case sensitive

docs: fix curl flags

---

internal/attestation/certcache/cached_client.go
internal/attestation/certcache/cached_client_test.go

Implement `trust.ContextHTTPSGetter` for `CachedHTTPSGetter` in order to use https://github.com/google/go-sev-guest/pull/156. This is the last step towards ensuring server timeouts are smaller than client timeouts _for SNP_.

attestation: forward context to KDS getter

---

docs/docs/architecture/attestation.md
docs/docs/architecture/snp.md
docs/sidebars.js
tools/vale/styles/config/vocabularies/edgeless/accept.txt

Document the details of (our) SNP attestation most importantly how we derive the public key and ID Block signature in https://github.com/edgelesssys/contrast/pull/1319

docs: SNP attestation documentation

---

coordinator/history/history.go
coordinator/history/history_test.go

This is required for RFC010, so that a recovering client can compare the latest manifest with what the recovering server sent. I factored this out from #1324.

history: allow insecure access to the latest transition

---

coordinator/internal/authority/credentials.go
coordinator/main.go

The enterprise code for peer recovery is going to validate the recovery server, so we need a certcache for it. It seems like a good idea to share the cert cache with the one used for meshapi server validation, because the Coordinators will be recovering each other after each `Setmanifest`. Thus, create the cache in main and inject it into the meshapi server (for now) and into the peer recovery routine (in the future).

coordinator: make KDS cache shareable

---

packages/by-name/cloud-api-adaptor/package.nix
packages/by-name/contrast/package.nix
packages/by-name/igvm-go/package.nix
packages/by-name/kata/kata-runtime/package.nix
packages/by-name/microsoft/kata-runtime/package.nix
packages/by-name/nydus-pull/package.nix
packages/by-name/nydus-snapshotter/package.nix
packages/by-name/service-mesh/package.nix
packages/by-name/snp-id-block-generator/package.nix
packages/by-name/tdx-measure/package.nix

This was made possible through recent upstream changes, see https://github.com/NixOS/nixpkgs/commit/06a152f9a174b9131c0c4e6ff08e662f493e2e44

packages: replace rec with finalAttrs on buildGoModule

---

coordinator/internal/transitengineapi/transitengineapi.go

This PR adds some enhancements to the coding style of the transit engine API and further adds function comments for better readability and maintenance.

transitengineapi: coding style and comments

---

coordinator/internal/authority/userapi_test.go

While refactoring the userapi, I found out that the overrides for TestRecovery requests are broken. The intention was to override the request data with what's in the test case struct, but this did not work as expected for empty seed and empty salt. We did not detect this because the error message was unchecked and we got the expected `InvalidArgument`, but from the latest transition signature check and not from the seedengine constructor.

coordinator: fix TestRecovery overrides

---

.github/workflows/e2e.yml
e2e/atls/atls_test.go
packages/scripts.nix

on TDX (which is skipped): https://github.com/edgelesssys/contrast/actions/runs/14638555551
on TDX (with 2nd commit): https://github.com/edgelesssys/contrast/actions/runs/14639561249
on SNP: https://github.com/edgelesssys/contrast/actions/runs/14638577116

e2e: fix snp atls test name

---

packages/by-name/kata/kata-kernel-uvm/package.nix
packages/by-name/kata/kata-runtime/0001-emulate-CPU-model-that-most-closely-matches-the-host.patch
packages/by-name/kata/kata-runtime/0002-runtime-agent-verify-the-agent-policy-hash.patch
packages/by-name/kata/kata-runtime/0003-genpolicy-read-bundle-id-from-rootfs.patch
packages/by-name/kata/kata-runtime/0004-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
packages/by-name/kata/kata-runtime/0005-genpolicy-rules-remove-check-for-OCI-version.patch
packages/by-name/kata/kata-runtime/0007-genpolicy-allow-image_guest_pull.patch
packages/by-name/kata/kata-runtime/0009-genpolicy-support-mount-propagation-and-ro-mounts.patch
packages/by-name/kata/kata-runtime/0010-tools-don-t-clean-build-root-when-generating-rootfs.patch
packages/by-name/kata/kata-runtime/0011-runtime-allow-initrd-AND-image-to-be-set.patch
packages/by-name/kata/kata-runtime/0014-genpolicy-support-guest-hooks.patch
packages/by-name/kata/kata-runtime/0015-genpolicy-support-dynamic-annotations.patch
packages/by-name/kata/kata-runtime/0018-genpolicy-allow-RO-and-RW-for-sysfs-with-privileged-.patch
packages/by-name/kata/kata-runtime/package.nix

https://github.com/kata-containers/kata-containers/releases/tag/3.16.0

kata.kata-runtime: 3.15.0 -> 3.16.0

---

packages/by-name/microsoft/genpolicy/0001-genpolicy-add-rules-and-types-for-volumeDevices.patch
packages/by-name/microsoft/genpolicy/0004-genpolicy-regex-check-contrast-specific-layer-src-pr.patch
packages/by-name/microsoft/genpolicy/0010-genpolicy-support-mount-propagation-and-ro-mounts.patch
packages/by-name/microsoft/genpolicy/package.nix
packages/by-name/microsoft/kata-agent/package.nix
packages/by-name/microsoft/kata-runtime/package.nix
packages/by-name/microsoft/tardev-snapshotter/package.nix

https://github.com/microsoft/kata-containers/releases

microsoft.kata-runtime: 3.2.0.azl3 -> 3.2.0.azl4

---

.github/workflows/release.yml
.github/workflows/release_publish.yml

:green_circle: release run: https://github.com/edgelesssys/contrast/actions/runs/15000310432
I didn't test the the cleanup on-release.

release: upload artifacts into public bucket

---

cli/cmd/policies.go

Fixes a typo that causes manifest problems

fix: correct manifest generation for CronJob

---

packages/by-name/boot-microvm/package.nix
packages/by-name/buildGoTest/package.nix
packages/by-name/microsoft/kata-image/buildimage.sh
packages/cleanup-bare-metal.sh
packages/debug-qemu-tdx.sh
packages/kata-debug-shell.sh
packages/scripts.nix

As discussed in https://github.com/edgelesssys/contrast/pull/1467#discussion_r2099551554.

treewide: prefer [[ over [ in shell scripts

---

go.mod
go.sum
packages/by-name/contrast/package.nix

This reverts commit 7cd1717d7554cb077718bc493045a4a38011637c.

Revert "deps: patch go-sev-guest with AMD Siena support"

---

go.mod
go.sum
packages/by-name/contrast/package.nix

This reverts commit 7cd1717d7554cb077718bc493045a4a38011637c.
(cherry picked from commit 2bd60050286f3c2cc83ae1b3955ce31fca2966e9)

[release/v1.8] Revert "deps: patch go-sev-guest with AMD Siena support"

---

packages/cleanup-bare-metal.sh

Previously, the script determined unused runtime classes by listing existing runtime classes and excluding the ones which are currently in use. If a runtime class gets deleted on its own (during development, etc.) the data is still there. We can still get the runtime handler by directly looking into the `/opt/edgeless` directory and deleting those files, as well as cleaning up the config.
Without the nydus snapshotter, we also cannot get the runtime handler from the node installer arguments. Instead, we can now directly get it from the resource name.

ci: cleanup data from already deleted runtime classes

---

packages/by-name/kata/kata-runtime/0022-genpolicy-remove-redundant-group-check.patch
packages/by-name/kata/kata-runtime/0023-genpolicy-push-down-warning-about-missing-passwd-fil.patch
packages/by-name/kata/kata-runtime/0024-genpolicy-compare-additionalGIDs-as-sets.patch
packages/by-name/kata/kata-runtime/0025-genpolicy-ignore-groups-with-same-name-as-user.patch
packages/by-name/kata/kata-runtime/package.nix

kata: remove unnecessary genpolicy warnings

---

docs/docs/features-limitations.md
e2e/internal/kubeclient/deploy.go
e2e/internal/kubeclient/wait.go
e2e/regression/README.md
e2e/regression/regression_test.go
e2e/regression/testdata/apache-httpd-pod.yml
e2e/regression/testdata/config-map-immutable.yml
e2e/regression/testdata/config-map.yml
e2e/regression/testdata/cronjob.yml
e2e/regression/testdata/daemonset.yml
e2e/regression/testdata/disruption-budget.yml
e2e/regression/testdata/job.yml
e2e/regression/testdata/limit-range.yml
e2e/regression/testdata/privileged-container.yml
e2e/regression/testdata/replicaset.yml
e2e/regression/testdata/replication-controller.yml
e2e/regression/testdata/role.yml
e2e/regression/testdata/rolebinding.yml
e2e/regression/testdata/secret.yml
e2e/regression/testdata/service.yml
e2e/regression/testdata/serviceaccount.yml

This PR adds common resource types to the regression test.

e2e/regression: add common resource types

---

dev-shells/by-name/kata.nix
flake.lock
flake.nix

Depending on the project, additional packages may need to be added to the list.

dev-shells: add a rust dev shell for upstream work

---

coordinator/internal/peerrecovery/recovery.go
coordinator/internal/peerrecovery/recovery_test.go
coordinator/internal/probes/probes.go
coordinator/internal/probes/probes_test.go
coordinator/main.go

These changes did not pass the peerrecovery test - reverting until I can properly fix them.

coordinator: revert liveness probe changes

---

docs/versioned_docs/version-1.9/architecture/secrets.md
docs/versioned_docs/version-1.9/components/service-mesh.md
docs/versioned_docs/version-1.9/deployment.md
docs/versioned_docs/version-1.9/examples/emojivoto.md
docs/versioned_docs/version-1.9/examples/mysql.md
docs/versioned_docs/version-1.9/getting-started/install.md
docs/versioned_docs/version-1.9/troubleshooting.md
packages/contrast-releases.json

Updating main as part of the 1.9.1 release.

Post 1.9.1 release updates to main

---

flake.nix

The linked issue was closed, let's see if it works.

flake: remove renovate comment

---

initializer/main.go

Previously, we would sleep for 10 seconds between cert requests. We reduce this to 5 seconds and use a ticker instead, so that we retry faster if the request took longer.

initializer: wait less between cert requests

---

imagepuller/go.mod
imagepuller/go.sum
imagepuller/main.go
packages/by-name/imagepuller/package.nix

Needed in order to measure storage usage as part of resource eval ticket.

imagepuller: add flag for setting tempdir location

---

imagepuller/internal/service/verify.go
imagepuller/internal/service/verify_test.go

Refactoring is heavily based on [p/imagepuller-ref](https://github.com/edgelesssys/contrast/commit/be66b44439c82227eaab56c17c03c9f81537f70a), with added improved error handling.

imagepuller: refactor and better error handling

---

docs/docs/architecture/attestation/amd-details.md
docs/versioned_docs/version-1.11/architecture/attestation/amd-details.md

docs: fix broken platformInfo struct table

---

e2e/openssl/openssl_test.go

In the `openssl` e2e test, we check the `dmesg` logs of the Coordinator pod and fail on any unknown errors.

e2e/openssl: check for dmesg errors

---

cli/cmd/verify.go

Policies are compressed in annotations and grpc transport since Contrast v1.12.0. In the verify command, we write the policies to the filesystem so the verifying party can inspect them. With the introduction of the compression, we missed decrompressing before writing the policies to the filesystem.
This change adds decrompression before the files are written, so they are in a human redable form again on disk and ready to inspect.

cli/verify: unzip policy files

---

justfile

We had a race where sometimes the optional config map wouldn't be available when the node-installer started, resulting in falling back to the defaults and patching the wrong containerd config. This change populates the target config into a different file that is applied first, so we can prevent that race.

just: apply node-installer target config before runtime

---

internal/initdata/initdata.go
internal/initdata/initdata_test.go

TBH I find it a bit difficult to gauge what we do (not) need without being able to use the lib anywehere.

cli/initdata: init initdata lib

---

packages/nixos/kata.nix

This commit adds a systemd service for the initdata processor and requires it to complete before the Kata agent starts.
The initdata processor is not doing anything interesting as long as it does not find an initdata device. If an initdata device is found, the processor attempts to validate it against the HOSTDATA/MRCONFIGID digest, but _does not abort if the validation fails_. This is intentional: we don't currently expect initdata to be set, and if it is set, we don't consume any of the files provisioned under `/run/measured-cfg`.

nixos: add initdata processor service and target
